### ISSUE TITLE
setPort not implemented

### ISSUE THREAD

**Issue by nylzhy** [pyserial/pyserial#100]
python(python 3.4.4 version 32 )
```python
port= serial.Serial()
>>> port
Serial<id=0x2a706b0, open=False>(port=None, baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False)
>>> port.setPort('com5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Serial' object has no attribute 'setPort'
```
But there is no problem python 3.4.4 64bit

**Comment by zsquareplusc** [comment]
You probably have different versions of pySerial installed when there is a difference between Python versions.

`setPort()` is deprecated id suggest to just assign to `.port`. But i'll commit a fix too as for now, the deprecated functions are still provided.
