### ISSUE TITLE
Dormant bug in serial.threaded.Packetizer with easy fix

### ISSUE THREAD

**Issue by stxlvt** [pyserial/pyserial#101]
In serial/threaded/\_\_init\_\_.py line 61, change

            packet, self.buffer = self.buffer.split(self.TERMINATOR)

to

            packet, self.buffer = self.buffer.split(self.TERMINATOR, 1)

So that the presence of more than one terminator substring in the buffer does not raise an exception.

**Comment by zsquareplusc** [comment]
Thank you :-)
