### ISSUE TITLE
RFC2217 socket timeout on connect

### ISSUE THREAD

**Issue by russinnes** [pyserial/pyserial#104]
rfc2217.py: 419

self._socket.settimeout(5) (x?) could be moved up, prior to establishing the socket connection. This allows an exception to be raised if the socket doesn't connect, otherwise it blocks if no socket connection can be made.

**Comment by zsquareplusc** [comment]
just moving the line up is not possible as the object is not existing earlier, but fortunately the `socket.create_connection()` method has the possibility to specify the timeout.

also fixed this for the `socket://` connection too
