### ISSUE TITLE
Write a single string hides some characters

### ISSUE THREAD

**Issue by ldpgh** [pyserial/pyserial#105]
It seems not all elements (sitting in the middle) of a single string are carried to the attached microcontroller.

Sending the string char-by-char using a for loop does not have this issue.

Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

OS:   Windows XP Home Edition SP3

pySerial:  VERSION = '2.7'  @ _ _init_ _.py

**Comment by ldpgh** [comment]
Testcase ... test_serial.py

```python
import serial
import time
import sys
import os

try:
  ser=serial.Serial("COM20", 57600, timeout=0.031)
  time.sleep(4.0)
except:
  print "ser.isOpen() =", ser.isOpen(), os.linesep
time.sleep(0.1)

#clean old stuff
for line in ser.readlines(): pass

#test string
test_s1="delay 0.03\n"
print "test_s1 =", test_s1.__repr__(), os.linesep

# OK
for ts1 in test_s1: ser.write(ts1)
time.sleep(0.2)
for line in ser.readlines(): print "line =", line.__repr__()
print " "

# FAILed
ser.write(test_s1)
time.sleep(0.2)
for line in ser.readlines(): print "line =", line.__repr__()
print " "

```

**Comment by ldpgh** [comment]
... and the output in the cmd-window
```
 > > python -i test_serial.py
test_s1 = 'delay 0.03\n'

line = 'delay 0.03\n'
                 ^^^ data read by the microcontroller mirrored back to the host
line = 'f_delay() ... 0.03\n'
line = '\r2a : ii=0    1800000\n'
line = '\r2a : ii=74    30000\n'
line = '\r>>'

line = 'delay 0.0\n'
                 ^^^ data read by the microcontroller mirrored back to the host
line = 'f_delay() ... 0\n'
line = '\r2a : ii=0    0\n'
line = '\r2a : ii=74    0\n'
line = '\r>>'
```

**Comment by ldpgh** [comment]
Found [similar looking question on stackexchange](http://electronics.stackexchange.com/questions/60456/python-serial-between-arduino-and-raspberry-pi-data-is-modified-upon-reception)

**Comment by ldpgh** [comment]
Sending "delay 0.03" to the microcontroller using "hyperterm" works as expected ... nothing disappeared.
`
>>delay 0.03
f_delay() ... 0.03
>>

`

**Comment by zsquareplusc** [comment]
i would not use such short timeouts, only in the range of multiple seconds.

if sending byte-by-byte works better, suggests that the microcontroller is not fast enough at receiving the bytes. maybe using two stop bits helps, tough that only gives the controller only marginally more time. consider using a lower baud rate or optimize the code.

its also possible that the connection requires hardware flow control.

**Comment by ldpgh** [comment]
You assumption seems to be right. Have tested baudrate=4800. Bytes are no longer missing.  Thx. for bringing me back on track ... firmware has been modified.

With this context it's clearly not a pySerial issue and I recommend to close this issue.

**Comment by ldpgh** [comment]
Closed issues due to false_issue.
