### ISSUE TITLE
Pyserial struggles communicating with arduino

### ISSUE THREAD

**Issue by troisiemetype** [pyserial/pyserial#106]
Hi,

I don't know if it's the right, or best place to ask for some help, but here it is:
I am working on a laser projector project. The kind that you use in music shows. This project is made of two parts, a python program running on a computer and featuring a GUI, and an arduino part that drives the projector hardware.
The PC part opens an image file, computes position for each of its pixels, format it in json style (e.g. {"ID":0,"X":300,"mode":1}) then streams it to the arduino.
The arduino parses this json string, get var/value pair, populates a buffer with it, then when done asks for a new json string. For debugging purpose it can also send informations, that are formatted the same way.
The python program has a main loop, that calls the function ones after others: GUI update, sending json serial data, reading serial data.
Writing serial data is simple: it uses the write() method, then sets a flag so that the next writing step will escape, unless the arduino has asked.
For reading, readline() was not good because it was blocking. So instead on each iteration it tests for available data, read() it and add it to a string. If the received byte is an end of line '\n', then it sets a flag and a parser will read the data. Possibly the next write iteration will be made, and the cycle starts again.

Now, here is the problem I have: as I have a huge amount of data to transfer as fast as possible (images are several millions of pixels), I try to limit communication as much as possible. So the arduino sends the minimum, and once I was sure it was working well, I've started to suppress the sending of debugging information from the arduino. Each message that is not sent shows an improve of global speed, until a point where there's just one information that comes from the arduino to the PC. Unfortunately at this point, it's like if the python program can't handle the data speed, and I don't understand why.
With two strings sent by the arduino for each coordinate received (one that gives the board state, and the other for asking next json string), it's about 22 seconds to send 2500 coordinates, including print() of each of these strings. Keeping just the one I need, it hardly can handle 2 to 5 sendings a second.

Here are the settings I'm using: 
baudrate = 115200
timeout = 0

I hope someone will be able to explain me what happens, or tell me what I'm doing wrong. I can, if needed, give some code.

**Comment by troisiemetype** [comment]
Ok, once again I've asked for help, thinking that after a few hours (or day, maybe?) I would not find, then find by myself...
The problem is of course not with the serial. This strange behavior was coming from the leds of the arduino, that flash quite rapidly when a string is being send. But the stream, once received, have to be processed real time by an interrupt, like a stepper in CNC. While there was large string passing through the serial, the process time of position computing was about the same as the serial write/read time. But as the serial diminish, the compute time stays the same: That's why it seemed to process slowly...

By the way, there's still one thing that I don't understand, it's why sometimes the sending starts when I ask, and sometimes not.

**Comment by zsquareplusc** [comment]
I usually receive in a separate Thread. In this case, I'd consider doing most of the bidirectional communication work in a separate worker thread as you want to have that as independent as possible from user input and GUI interaction (it may even be an option to check thread priority can be elevated by the OS, though i never needed that). Having a "headless" worker may also be useful if you consider running it as console application or as part of different GUIs.

Your protocol seems to have inherent flow control, by the Arduino only asking for new data when it's ready. This is good, makes it a lot easier. To get it running you may need to have a special start commando (instruct the Arduino to ask for the first packet) or just start sending one data packet.

It may be useful to track the times when the Arduino asks for a new packet and set a flag in the PC application if the requests are too far apart. This would be an indication for a bad connection (unplugged, reset etc.) and after such an event it may make sense to have the PC restart the connection (not the serial port but the protocol)

**Comment by troisiemetype** [comment]
Thank you for your answer! I've thunk about mutli-threading, but as this is my first python program, I was quite impressed in going that far. Too much complexity for my level, too much new concepts... Anyway, the program is just used for sending data to the arduino (and pre-process it), so when a file is sending, there is nothing else the program needs to do: every area of the GUI are de-activated.
I implemented this ask/answer flow control because I didn't succeed in getting an xon/xoff flow control to work. For every bytes received on the arduino I test the length of he buffer queue in the ISR, and immediately send XOFF signal if needed, but is has no effect. There's surely something I must be missing.
Would you like to have a look to the project, it's here: https://github.com/troisiemetype/python-projecteur-laser and here: https://github.com/troisiemetype/arduino-projecteur-laser.

Again, thank you for having answering that quick!
