### ISSUE TITLE
Suggestion: to_bytes could try to convert from unicode instead of raising error straight away

### ISSUE THREAD

**Issue by Steinarr134** [pyserial/pyserial#112]
I've been converting some code from python 2.7 to also support 3.5 but kept getting a ValueError when calling Serial.write(some_string)

> TypeError: unicode strings are not supported, please encode to bytes

eventually I changed these lines in serialutils.to_bytes(seq):

    elif isinstance(seq, unicode):
        raise TypeError('unicode strings are not supported, please encode to bytes: %r' % (seq,))
into

    elif isinstance(seq, unicode):
        try:
            seq = seq.encode('ascii')
        except:
            raise TypeError('unicode strings are not supported, please encode to bytes: %r' % (seq,))

I've tested this with both python 2.7 and python 3.5 and both seem to work so I figured I should suggest this as a possible improvement.

**Comment by zsquareplusc** [comment]
I understand that these error messages can be a bit frustrating at first, but if you handle bytes and Unicode correctly it makes your programs better and may even catch a bug or two.

However changing the API to add "guessing what the user may want" is not what I want. It would lead to much more subtle bugs that are hard to debug when the API accepts data sometimes but not an other time, depending on the contents.

pySerial provides a low-level interface, therefore the choice of `bytes` as datatype. If you have a text based protocol and want to work with Unicode, you could wrap the serial port using a [io.TextIOWrapper](https://docs.python.org/3/library/io.html#io.TextIOWrapper) see [here](http://pyserial.readthedocs.io/en/latest/shortintro.html#eol).
