### ISSUE TITLE
How to make a safe and blocking write?

### ISSUE THREAD

**Issue by edoz90** [pyserial/pyserial#114]
Hi! 
I'm using pyserial with thread support for reading and writing from arduino (one thread for reading, one for writing). When I write something in the serial the arduino sends me the response.
If I make a sequence of writes obviously the serial buffer is messed up (concurrency on writing and reading): how can I check if the serial if free for writing and/or make the serial.write blocking?

**Comment by zsquareplusc** [comment]
[This example](https://github.com/pyserial/pyserial/blob/master/examples/at_protocol.py) may be interesting. It uses a reader thread and uses a `threading.Lock` to ensure that only one other thread is sending a command at once.
