### ISSUE TITLE
Is method newline() dupplicated in version 3.0?

### ISSUE THREAD

**Issue by yushi-m** [pyserial/pyserial#115]
I couldn't find newline() in pyserial API reference.
http://pyserial.readthedocs.io/en/latest/pyserial_api.html

But newline() is described in shortintro.
http://pyserial.readthedocs.io/en/latest/shortintro.html

Can I use newline() method?

**Comment by zsquareplusc** [comment]
I do no see a `newline` method in neither one of these documents. Maybe you meant [`readline`](https://docs.python.org/3.5/library/io.html#io.IOBase.readline), which is inherited from [`io.IOBase`](https://docs.python.org/3.5/library/io.html#io.IOBase) via `io.RawIOBase`

**Comment by diamondman** [comment]
@yushi-m Any chance you could close out this issue if it is resolved?

**Comment by yushi-m** [comment]
I also confirmed, but newline () is not found.
I'm sorry, but I can't remember because it was old. I will close this issue.
