### ISSUE TITLE
rx buffer shows available only after get more than 32 bits

### ISSUE THREAD

**Issue by guzhaoyuan** [pyserial/pyserial#117]
My OS is ubuntu 14.04 and I am trying to send from one port(ttyUSB0) to another port(ttyUSB1).
But only after the receive port(ttyUSB1) receives more than 32 bits, the rx buffer show there are data available. If I send one byte, no receive data showed and I can not read that byte.
I tested using c++ on ubuntu 14.04, the same problem.
But the same code works on OS X el capitan 
How to solve this?

**Comment by zsquareplusc** [comment]
My guess would be that the USB Serial adapter is buffering these. What `in_waiting` reports will depend on the driver, but I would not be surprised if numerous adapters only report data that is already in the buffer of the OS.

Different timeout settings may cause the driver to behave differently, alternatively try USB Serial adapters with a different chipset.

**Comment by guzhaoyuan** [comment]
It's my fault that I used the default setting. The problem solved by useing none stop bit and set Parity Check.
