### ISSUE TITLE
Bytecode compilation issue in Python 2.7.x

### ISSUE THREAD

**Issue by yegorich** [pyserial/pyserial#123]
`python -m compileall .` produces following error in `./serial/aio.py`:

```
Compiling ./serial/aio.py ...
  File "./serial/aio.py", line 366
    def open_serial_connection(*,
                                ^
SyntaxError: invalid syntax
```
Python 3.x compiles without error.

**Comment by zsquareplusc** [comment]
Yes, that's Python 3 syntax. The module does not work with Python 2 anyway. But I can look if there is a workaround.

**Comment by zsquareplusc** [comment]
Well if that is fixed, the next issue will be `yield from`...

**Comment by yegorich** [comment]
Can you exclude aio.py from installation, when using Python 2?

**Comment by rob-smallshire** [comment]
I've submitted #131 which modifies the install script to not install aio when running on Python 2. This will allow us to continue to use Python 3 syntax in the aio module, which will only ever work on Python 3.4+ anyway.
