### ISSUE TITLE
The Serial class in the .NET/Mono (IronPython) backend does not implement the _reconfigure_port method

### ISSUE THREAD

**Issue by sabWA256** [pyserial/pyserial#127]
There is no _reconfigure_port(self) function in serialcli.py but it is expected by the parent class SerialBase in serialutil.py. This causes SerialBase to generate the message *AttributeError: 'Serial' object has no attribute '_reconfigure_port'*.

The SerialBase class implemented in serialutil.py expects _reconfigure_port(self) to be implemented by subclasses. This is not explicitely stated in the module, but it is clear from examining the code.
For example, from serialutil.py:

```python
@baudrate.setter
def baudrate(self, baudrate):
    """\
    Change baud rate. It raises a ValueError if the port is open and the
    baud rate is not possible. If the port is closed, then the value is
    accepted and the exception is raised when the port is opened.
    """
    try:
        b = int(baudrate)
    except TypeError:
        raise ValueError("Not a valid baudrate: %r" % (baudrate,))
    else:
        if b &lt;= 0:
            raise ValueError("Not a valid baudrate: %r" % (baudrate,))
        self._baudrate = b
        if self.is_open:
            self._reconfigure_port()
```

The Serial(SerialBase) class implemented in serialcli.py has _configurePort(self) 
but _configure_port(self) does not exist:

```python
def _reconfigurePort(self):
    """Set communication parameters on opened port."""
    if not self._port_handle:
        raise SerialException("Can only operate on a valid port handle")
```
 Here is the output of a test run using IronPython. Note the traceback at the end.

>C:\test>ipy test_advanced.py
>Some tests for the serial module.
>Part of pyserial (http://pyserial.sf.net)  (C)2002 cliechti@gmx.net
>
>Intended to be run on different platforms, to ensure portability of
>the code.
>
>These tests open a serial port and change all the settings on the fly.
>If the port is really correctly configured cannot be determined - that
>would require external hardware or a null modem cable and an other
>serial port library... Thus it mainly tests that all features are
>correctly implemented and that the interface does what it should.
>
>Testing port: 'COM1'
>test_BaudrateSetting (__main__.Test_ChangeAttributes) ... ERROR
>test_BytesizeSetting (__main__.Test_ChangeAttributes) ... ok
>test_DoubleOpen (__main__.Test_ChangeAttributes) ... ok
>test_ParitySetting (__main__.Test_ChangeAttributes) ... ok
>test_PortOpenClose (__main__.Test_ChangeAttributes) ... ok
>test_PortSetting (__main__.Test_ChangeAttributes) ... ok
>test_RtsCtsSetting (__main__.Test_ChangeAttributes) ... ok
>test_StopbitsSetting (__main__.Test_ChangeAttributes) ... ok
>test_TimeoutSetting (__main__.Test_ChangeAttributes) ... ok
>test_XonXoffSetting (__main__.Test_ChangeAttributes) ... ok
>
>
>ERROR: test_BaudrateSetting (__main__.Test_ChangeAttributes)
>
>Traceback (most recent call last):
>  File "test_advanced.py", line 77, in test_BaudrateSetting
>    for baudrate in (300, 9600, 19200, 115200):
>  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\serial\serialutil.py", line 232, in baudrate
>    else:
>AttributeError: 'Serial' object has no attribute '_reconfigure_port'
>
>----------------------------------------------------------------------
>Ran 10 tests in 0.233s
>
>FAILED (errors=1)

For the record, I'm using pySerial 3.0.1 and IronPython 2.7.5 (32-bit).

**Comment by zsquareplusc** [comment]
Thank you
