### ISSUE TITLE
problem with ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by speedy-10** [pyserial/pyserial#138]
Hello,
I installed python3-serial with:
sudo apt-get install python3-serial
Using the Python-Shell I got the following failure:
`
>>> import serial
>>> s = serial.Serial(0)
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    s = serial.Serial(0)
  File "/usr/local/lib/python3.5/dist-packages/serial/serialutil.py", line 162, in __init__
    self.port = port
  File "/usr/local/lib/python3.5/dist-packages/serial/serialutil.py", line 206, in port
    raise ValueError('"port" must be None or a string, not {}'.format(type(port)))
ValueError: "port" must be None or a string, not <class 'int'>`

Even if I tried to install by `sudo python3 setup.py install
`

I got the same failure.

What can I do?

**Comment by zsquareplusc** [comment]
[numbers are no longer supported](http://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial), specify the port as string, e.g. `"/dev/ttyUSB0"`

**Comment by speedy-10** [comment]
Permissions are denied, what can I do?

>>> ser = serial.Serial('/dev/ttyS1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/serial/serialposix.py", line 244, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyS1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    ser = serial.Serial('/dev/ttyS1')
  File "/usr/local/lib/python3.5/dist-packages/serial/serialutil.py", line 182, in __init__
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/serial/serialposix.py", line 247, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyS1: [Errno 13] Permission denied: '/dev/ttyS1'``

**Comment by speedy-10** [comment]
Solved:
sudo chmod 777 /dev/ttyS0

**Comment by zsquareplusc** [comment]
on Debian based systems is usually solved by adding the user to the group `dialout`
e.g.: `sudo adduser $USER dialout`

**Comment by speedy-10** [comment]
Thanks.
I have one  more problem: 
In  versions before I used:
>>> import serial          # das Modul serial wird importiert
>>> s = serial.Serial(0)   # Objekt s wird erzeugt und öffnet sofort Port 0 (COM1)
>>> s.setRTS(0)            # RTS wird auf 0 gesetzt
>>> s.setRTS(1)            # RTS wird auf 1 gesetzt
>>> s.getCTS()             # CTS wird abgefragt (RTS-CTS geschlossen)
True

An LED was switched on an off:
http://www.hsg-kl.de/faecher/inf/netze/netzHW/

I tried several things, but it doesn't work. The LED is always an until s.close()
[pyserial_test2.txt](https://github.com/pyserial/pyserial/files/346433/pyserial_test2.txt)

. How can I do this with the actual python3-serial?

**Comment by zsquareplusc** [comment]
The same way as before. But you quickly toggle to output, maybe you need to wait a bit using `time.sleep(1)`, so that the LED is enabled long enough?

**Comment by speedy-10** [comment]
I tried it in the Shell and waited long enough.

**Comment by zsquareplusc** [comment]
I have run the tests for pySerial successfully on a Linux machine with different USB-Serial adapters. And these include RTS/DTR signals.

Did something else on the setup change too? Your link above says it using an LED from RTS to GND and assumes that the port delivers +/- 12V. However, the later may no be true, the specification allows signals down to +/-3V. Many USB-Serial adapters have around +/-6V and the LED may be not as bright as you expect.

Then the cable may be an issue (only RX/TX/GND connected or a null modem cable that exchanges pins). You could also connect the LED to the TX line and use BREAK to toggle the output state. There are also serial port tester boxes that connect a red and green LED (anti-parallel) from the control lines to GND so depending on high/low state one or the other LED is on, as long as there is power.

**Comment by speedy-10** [comment]
Now I tried a different PC and it works fine as before 16.04, so my PC has a problem with the mainboard. I'm sorry that I didn't test this before. 
Thanks for all the help!

**Comment by yzk23** [comment]
> Solved:
> sudo chmod 777 /dev/ttyS0

Work for me. Thx

**Comment by AnwarKamel** [comment]
sudo chmod 777 /dev/ttyUSB0
