### ISSUE TITLE
IronPython Does Not Recognize

### ISSUE THREAD

**Issue by StepMaher** [pyserial/pyserial#142]
Hi all,

Quick question regarding usage with IronPython. For some reason it doesn't recognize PySerial (see common `ImportError` below).

![image](https://cloud.githubusercontent.com/assets/10765460/17248661/ebf24044-5569-11e6-99e2-29bef8eb1c1b.png)

I installed the library using the Command Prompt. Am I missing something? Or do I need to re-install using a different way?

Thanks in advance for the help,
/SPM

**Comment by zsquareplusc** [comment]
You do not mention how you installed it. `ipy setup.py install` i guess? As a last resort, you could also copy the `serial` directory manually to `site-packages`.

**Comment by StepMaher** [comment]
Sorry, by "using Command Prompt" I meant I used `ipy setup.py install` and verified that all the files are in the site-packages directory.
