### ISSUE TITLE
Class Serial in protocol_loop.py references variable before assigning to it

### ISSUE THREAD

**Issue by RichardLangFromNZ** [pyserial/pyserial#143]
pyserial 3.1.1

Class` Serial` from "\urlhandler\protocol_loop.py" assigns `buffer_size` member variable in it's` __init__` method, but calls it's superclass `__init_` first, which in some circumstances attempts to open the port via. the `open()` method, which references `buffer_size`...

**Comment by zsquareplusc** [comment]
Thank you
