### ISSUE TITLE
Serial.__enter__ does not open the port

### ISSUE THREAD

**Issue by fmoor** [pyserial/pyserial#150]
Serial.__enter__ does not open the serial port even though __exit__ closes the port.

**Comment by zsquareplusc** [comment]
Yes, it is working as designed. If a port argument is passed to the [Serial](http://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial) instance, it opens the port, [serial_for_url](http://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.serial_for_url) opens the port too, unless you add an argument. In these cases opening happens at instantiation, so `__enter__` does not need to do anything.

I've added docs: http://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.__enter__
