### ISSUE TITLE
Documentation:  Windows Version Support

### ISSUE THREAD

**Issue by modal** [pyserial/pyserial#151]
Can pyserial support for Windows versions be explicitly spelled out in the **README.rst** and  **pyserial/documentation/pyserial.rst** files?    

Prior Reference Issues:  [148](https://github.com/pyserial/pyserial/issues/148), [132](https://github.com/pyserial/pyserial/issues/132)

**Comment by zsquareplusc** [comment]
I can not provide such a list with reliable results, that is why there isn't one ;-) . I do not have access to many different versions of Windows and do not have the resources to test all releases on so many systems, as the drivers matters too, this test would even need to be done with several different adapters (and driver versions?). MSDN also eradicated references to their older OSes, so you can not even check the documentation for a review :/

On the other hand, I'm not aware of any differences between current Windows versions, unless you count Win98... Also `list_ports` is a bit more difficult as it has larger differences from driver to driver...

**Comment by mengyyy** [comment]
I use version 3.0.1 on my windows xp sp2 after i try one by one from 3.1.1 to 2.7   
So version from 3.0.1 to 2.7 should work on my  windows xp sp2.

**Comment by zsquareplusc** [comment]
OK, added a note to the docs under [requirements](https://pyserial.readthedocs.io/en/latest/pyserial.html#requirements)
