### ISSUE TITLE
Serial timeouts are the wrong interval when system clock is set.

### ISSUE THREAD

**Issue by neilwhelchel** [pyserial/pyserial#155]
I have been having some really hard to find bugs with serial communication locking up when the system clock gets updated.I tracked it back to the use of time.time() instead of time.monotonic() in serialposix.py.
The problem is that timeouts are calculated by comparing a previous call to time.time() to a current one. This is a big problem if the system clock is changed backwards. This effectively adds (or subtracts) the changed system time to the timeout. This is what time.monotonic() is intended to avoid.

**Comment by zsquareplusc** [comment]
I know about that, but the function is new in Python 3.3, so it needs a larger helper class with fallback etc. to support all the Python versions that pySerial currently does...

**Comment by neilwhelchel** [comment]
Really good point. One of the ways I worked around this in older Python programs I wrote is to store the when = time.time() + timeout. When checking if time.time() >= when, I also check if time.time() - when > timeout. If so, I redo when = time.time()...
This way, if the system time gets set back you are not stuck for longer than twice timeout (worst case).

**Comment by zsquareplusc** [comment]
Implemented a `Timeout` helper class, even with tests, that also handles the clock changing problem as you describe.
