### ISSUE TITLE
Broken handling of CMSPAR in serialposix.py

### ISSUE THREAD

**Issue by neilwhelchel** [pyserial/pyserial#157]
The logic for clearing the CMSPAR bit in serialposix (and possibly other platforms) seems to be missing. Once you set serial.parity=serial.PARITY_MARK, serial.parity=serial.PARITY_ODD (and others) do not clear the CMSPAR bit in hardware.

**Comment by zsquareplusc** [comment]
well spotted, thanks

**Comment by neilwhelchel** [comment]
Thanks for working on this!
I thought that I would point out that while I know very little about Windows, I do know that somehow mark and space parity are supported. I have a number of Windows applications that use it. I could be wrong here, but I do not think that it is emulated by hacking odd and even parity, I think that the OS actually handles it. In systems that hack the parity, only the given bytes that match the parity to the required mark or space are loaded into the transmit buffer. When the hardware signals an interrupt because the transmit buffer is empty, the parity is then flipped and all of the bytes that match the new parity are loaded. The result is that if you watch this on a scope, you see a pause each time that parity has to be changed to maintain maro or space output. If you watch the applications that I am using, there is no such pause, so that suggests that the hardware is getting set into mark or space parity somehow. (Also, I have a bunch of USB->serial converters, some support stick parity and some do not, the ones that do not support stick parity do not work with these applications in Windows. They silently fail and use either odd or even parity instead of stick parity. Refer to the chip docs for the 16550 bit 5 of the LCR. Some chips mark this bit as "reserved".)
