### ISSUE TITLE
ReInstall pyserial successfull but fails at runtime

### ISSUE THREAD

**Issue by ldpgh** [pyserial/pyserial#158]
(1) Doing pySerial Install on Win7, Python 2.7.12 successfull. Runtime works fine and as expected :-)

(2.0) Had a functional pySerial (revision unknown) installed on WinXP, Python 2.7.5. The reason for the reinstall are the changes as described by (3)
2.1) ReInstall successfull
(2.2) Runtime FAIL. Screen-log ( [pyserial_install_fail.txt](https://github.com/pyserial/pyserial/files/453299/pyserial_install_fail.txt) ) including the install from cmd.exe window.

(3) `list(serial.tools.list_ports.comports())`  seems to behave different between the current pySerial revision and my old installation.
- installation according (1) ... `[<serial.tools.list_ports_common.ListPortInfo object at 0x02314F70>]`
- old installation according (2) ... `[('COM1', 'Kommunikationsanschluss (COM1)', '*******')]`

**Comment by ldpgh** [comment]
FYI: Have reinstalled   pyserial-2.7.win32.exe  ... now working again.

Btw. it is hard to find older versions, because

- http://pythonhosted.org/pyserial/pyserial.html#older-versions

points back to

- https://pypi.python.org/pypi/pyserial.

**Comment by awachtler** [comment]
So the tuple seems to have changed into a class, the workaround to get, e.g. the names, would look so:

`>>> [d.name for d in serial.tools.list_ports.comports()]
['ttyS4', 'ttyUSB0']
`
There are more interesting options as well:
`>>> [d.manufacturer for d in serial.tools.list_ports.comports()]
[None, 'FTDI']
 >>>[d.product for d in serial.tools.list_ports.comports()]
[None, 'FT232R USB UART']
`

Well, things change over time, if not, we still would live on trees :-)

**Comment by zsquareplusc** [comment]
You can still unpack it as tuple to get the three items, but it is now also supporting more when treated as object, as mentioned above.

Regarding uninstalling, that's an interesting topic for Python modules ;-) Older methods to install did not track the files so there was no way to automatically remove. Today the situation should be much better if you use pip. You may need to remove old modules manually by deleting their directories under `site-packages`.

**Comment by ldpgh** [comment]
I'm more worrying regarding the run-time issue in (2.2) ... please have a look in the attached pyserial_install_fail.txt.

**Comment by zsquareplusc** [comment]
This function (`CancelIoEx`) is needed for a new feature and WinXP, a dead, unsupported OS [from the vendor] does not have this one. You'll have to use older software (Python, pySerial and other...) for old that old OS.

(https://pyserial.readthedocs.io/en/latest/pyserial.html#older-versions)

**Comment by ldpgh** [comment]
Ooops ... but just old stuff has a real serial hardware. 

The Doc should be more specific on this topic. 

OK for me to close the issue.

**Comment by zsquareplusc** [comment]
OK, added a note to the docs under [requirements](https://pyserial.readthedocs.io/en/latest/pyserial.html#requirements)

**Comment by ldpgh** [comment]
Just for completeness to find older revisions ... be aware of ..../simple/....
- https://pypi.python.org/simple/pyserial
- http://stackoverflow.com/questions/25104154/pypi-see-older-versions-of-package

**Comment by zsquareplusc** [comment]
@ldpgh Thanks, updated the link
