### ISSUE TITLE
Write in non-blocking mode returns incorrect value on windows

### ISSUE THREAD

**Issue by jabdoa2** [pyserial/pyserial#162]
When setting write_timeout to 0, a write on a socket will always return 0 on windows. Windows does not provide this value in asynchronous mode:

```
lpNumberOfBytesWritten [out, optional]
A pointer to the variable that receives the number of bytes written when using a synchronous hFile parameter. WriteFile sets this value to zero before doing any work or error checking. Use NULL for this parameter if this is an asynchronous operation to avoid potentially erroneous results.
```
From: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365747(v=vs.85).aspx

I suppose it would be correct to just return len(data) in the else branch of https://github.com/pyserial/pyserial/blob/master/serial/serialwin32.py#L315. 

Additionally, it might be helpful to check for those:
`
The WriteFile function may fail with ERROR_INVALID_USER_BUFFER or ERROR_NOT_ENOUGH_MEMORY whenever there are too many outstanding asynchronous I/O requests.
`
And return 0 in this case. This is a problem for pyserial_asyncio on windows: https://github.com/pyserial/pyserial-asyncio/issues/10

**Comment by zsquareplusc** [comment]
Thanks.

The possible error messages you mention should all be caught, but there is no difference in the Exception that is thrown (error details only visible in text).

**Comment by jabdoa2** [comment]
@zsquareplusc thanks. Since all writes succeed currently it would be nice not to fail on those errors once we reached the max IO request limit. I propose we do a similar thing as in posix: Just return 0 bytes in that case.

**Comment by zsquareplusc** [comment]
OK, then we do it differently. committed an update
