### ISSUE TITLE
Test Failed

### ISSUE THREAD

**Issue by nick83ola** [pyserial/pyserial#165]
Installed /usr/local/lib/python3.5/dist-packages/pyserial-3.1.1-py3.5.egg
Processing dependencies for pyserial==3.1.1
Finished processing dependencies for pyserial==3.1.1
~/tmp/pyserial$ cd test/
~/tmp/pyserial/test$ python3 run_all_tests.py 
Patching sys.path to test local version. Testing Version: 3.1.1
found 1 tests in 'test_pty'
found 4 tests in 'test_timeout_class'
found 2 tests in 'test_cancel'
found 5 tests in 'test_readline'
found 1 tests in 'test_iolib'
found 2 tests in 'test_threaded'
found 2 tests in 'test_util'
found 3 tests in 'test_url'
found 1 tests in 'test_rfc2217'
found 10 tests in 'test_advanced'
found 15 tests in 'test'
found 0 tests in 'test_asyncio'
found 2 tests in 'test_rs485'
found 2 tests in 'test_high_load'
found 4 tests in 'test_settings_dict'
.....FF.......................................E.......
======================================================================
ERROR: test_RS485_class (test_rs485.Test_RS485_class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyserial-3.1.1-py3.5.egg/serial/serialposix.py", line 251, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: 'loop://'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/damnick/tmp/pyserial/test/test_rs485.py", line 46, in setUp
    self.s = serial.rs485.RS485(PORT, timeout=1)
  File "/usr/local/lib/python3.5/dist-packages/pyserial-3.1.1-py3.5.egg/serial/rs485.py", line 60, in __init__
    super(RS485, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyserial-3.1.1-py3.5.egg/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/pyserial-3.1.1-py3.5.egg/serial/serialposix.py", line 254, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port loop://: [Errno 2] No such file or directory: 'loop://'

======================================================================
FAIL: test_cancel_once (test_cancel.TestCancelRead)
Cancel read
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/damnick/tmp/pyserial/test/test_cancel.py", line 27, in setUp
    self.assertTrue(hasattr(self.s, 'cancel_read'), "serial instance has no cancel_read")
AssertionError: False is not true : serial instance has no cancel_read

======================================================================
FAIL: test_cancel_once (test_cancel.TestCancelWrite)
Cancel write
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/damnick/tmp/pyserial/test/test_cancel.py", line 67, in setUp
    self.assertTrue(hasattr(self.s, 'cancel_write'), "serial instance has no cancel_write")
AssertionError: False is not true : serial instance has no cancel_write

----------------------------------------------------------------------
Ran 54 tests in 26.732s

FAILED (failures=2, errors=1)
damnick@nicola-N552VX:~/tmp/pyserial/test$

**Comment by zsquareplusc** [comment]
Yeah some of the tests make only sense with real hardware. However the default port for tests is set to the `loop://` implementation as that is available everywhere. Despite that, I've updated the loop implementation to cover more features and made the rest of the test skipping.

You can run tests by specifying the port as argument on the command line. `python3 run_all_tests.py /dev/ttyUSB0` for example.
