### ISSUE TITLE
Request: Expose USB interface descriptor index

### ISSUE THREAD

**Issue by jrmrjnck** [pyserial/pyserial#168]
I am trying to connect with a USB device which exposes two CDC/ACM functions (not sure if function is the right word - I'm new to USB terminology). There are a total of four USB interfaces (control+data for two functions). In pyserial, the two functions are detected but they have identical ListPortInfo data, so it's impossible to know which is which.

I took a look at list_ports and it should be possible to get the interface information (at least on Windows and Linux, which is what I need to support).

On Windows, the interface index shows up as `&MI_XX` at the end of the HW ID string. (e.g. `USB\VID_1FC9&PID_0003&REV_0100&MI_02` for the second function on interface index 2).

On Linux, the sysfs path includes the config.interface information following a colon `:`.

**Comment by diamondman** [comment]
@jrmrjnck Looks like your request might be done. Please check, and see if we can get this issue closed :).

**Comment by jrmrjnck** [comment]
I no longer use the hardware which prompted this issue report, so I can't verify it. But since it's not relevant for me any longer, I'm happy to close it.
