### ISSUE TITLE
Serialize serial.Serial object created using pyserial

### ISSUE THREAD

**Issue by sudiptakarmakar** [pyserial/pyserial#170]
I am trying to read/write data off a serial port from multiple processes. Since I didn't want to open the connection every time I send a request, I was trying to serialize the serial object reference (once connection is made) and use that for future requests until disconnection happens. But I can't serialize the object using pickle. What do you suggest I do here?

**Comment by zsquareplusc** [comment]
Serial instances can not be pickled and they can not be shared across processes as the underlying OS resources are not that easily transferable (may depend on OS and process invocation method, though noting is explicitly supported by pySerial).

You can retrieve and apply the settings of an instance using [get_settings](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.get_settings) and [apply_settings](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.apply_settings). But this does not open a port on itself.

Opening the same port with multiple processes at the same time is not supported across all OS. For a portable solution, use one process servicing the port and inter process communication to talk with the others.
