### ISSUE TITLE
Opening/closing serial ports to quickly on a mac kills usb ports

### ISSUE THREAD

**Issue by theicfire** [pyserial/pyserial#176]
I've verified this on osx 10.11.4 and 10.12.1. Whenever I close a Serial instance, and then unplug/replug in the usb ports, the usb port disappears. Here's the code I'm using:

```
import serial
import sys
import glob

def serial_ports():
    """ Lists serial port names

        :raises EnvironmentError:
            On unsupported or unknown platforms
        :returns:
            A list of the serial ports available on the system
    """
    if sys.platform.startswith('win'):
        ports = ['COM%s' % (i + 1) for i in range(256)]
    elif sys.platform.startswith('linux') or sys.platform.startswith('cygwin'):
        # this excludes your current terminal "/dev/tty"
        ports = glob.glob('/dev/tty[A-Za-z]*')
    elif sys.platform.startswith('darwin'):
        ports = glob.glob('/dev/tty.usb*')
    else:
        raise EnvironmentError('Unsupported platform')

    result = []
    for port in ports:
        try:
            s = serial.Serial(port)
            s.close()
            result.append(port)
        except (OSError, serial.SerialException):
            pass
    return result

ports = serial_ports()
print ports
ser = serial.Serial(ports[0], 115200, timeout=1)
ser.close()
```
Interestingly, on 10.12.1, if I omit the ser.close() call, the problem does not happen. The problem still happens on 10.11.4 -- I expect that's for a different reason: 10.11.4 will kill usb ports that are disconnected while an active connection happens, whereas this does not happen for 10.12.1.

**Comment by zsquareplusc** [comment]
Maybe i find someone with a mac who can try to reproduce this. in the meantime you could look at [serial.tools.list_ports](https://pyserial.readthedocs.io/en/latest/tools.html#module-serial.tools.list_ports), which enumerates them without open/close.

**Comment by zsquareplusc** [comment]
Someone else noted that you are opening the `tty` variant of the device. This may cause issues. pySerial is designed to work with raw, binary ports and some OS, e.g. from the BSD family, have two device entries for each serial port, one `tty` type for textual content and a `cua` or similarly named variant for binary communications. You need to use the later.

**Comment by theicfire** [comment]
Oops, after looking to it more, it looks like the core problem is when I open and close the serial port too quickly, that's when the bug happens:

```
import time
ser = serial.Serial('/dev/cu.usbserial-FTFNU2PD')
ser.close()
# time.sleep(1) .. if I sleep here, the problem goes away
ser = serial.Serial('/dev/cu.usbserial-FTFNU2PD')
ser.close()
```

To reiterate: the problem is that if I run the script above on my mac, unplug/replug in the usb device, that port shows up to be dead

**Comment by zsquareplusc** [comment]
If unplugging and plugging-in the same device is involved, it may also be an electronics issue.

Electronic devices need a reset to properly start up. They also need energy and use capacitors to store it. If  a device is unplugged, capacitors discharge, the speed of that may depend on the state the device was in (open/closed). If the power comes back and the capacitors are not fully discharged, it may happen that a device does not reset properly.

So if you unplug that device and wait much longer before plugging in again, does the problem still show up?

**Comment by MAKOMO** [comment]
Not convinced. I observed the very same behavior on OS 10.11, now on 10.12 it did not occur to me anymore. Under OS 10.11 if I disconnected a device without closing the port from within pyserial, the port could only be reanimated by rebooting the machine.

**Comment by zsquareplusc** [comment]
And how is the behavior with other applications?

**Comment by theicfire** [comment]
@zsquareplusc I plugged in a serial device, ran the script, unplugged it, waiting 10 seconds, and then plugged in a keyboard, and the keyboard did not work. What this means to me is that after running the script (one or more times, it will continue to work), the act of unplugging the usb device will kill the usb port.

**Comment by theicfire** [comment]
Welp, I just opened/closed a port quickly in node and had the same problem. Sorry for the bother. Looks like it's a mac problem:
```
var SerialPort = require('serialport');
var open_close = function(redo) {
  var port = new SerialPort('/dev/tty.usbserial-FTFNU2PD');
  port.on('open', function() {
    console.log('open');
    port.close(function() {
      console.log('closed');
      if (redo) {
        open_close(false);
      }
    });
  });

  // open errors will be emitted as an error event
  port.on('error', function(err) {
    console.log('Error: ', err.message);
  })
}
open_close(true);
```

**Comment by MAKOMO** [comment]
Yep. Remember that I saw that under OS X 10.11 also using the Arduino SDK which is written in Java. So this might just be an OS issue and not a pyserial one.

**Comment by gerwindehaan** [comment]
FYI @theicfire @MAKOMO my solution on MacOS 10.11 to similar frequent plug/unplug issues was to stop using an (older) FTDI provided driver (e.g. ```kextstat``` reports ```com.FTDI.driver.FTDIUSBSerialDriver```) and instead use Apple's built-in driver (e.g. ```com.apple.driver.AppleUSBFTDI```), see http://apple.stackexchange.com/questions/236584/ftdi-usb-device-not-removed-after-unplugging/242500
