### ISSUE TITLE
write Integer data to serialPort raises Error on Linux

### ISSUE THREAD

**Issue by Schmetzler** [pyserial/pyserial#178]
I found a bug and I am not well aware on how to upload a patch (just didn't do that before and don't know the workflow).

In file serialposix.py in function `write(self, data)` the data is transformed to bytes:
(line 518) `d = to_bytes(data)`
but at the end (line 558) it `return len(data)`, what fails if data is an integer
it should `return len(d)`
(This error does not occur on windows because line 308 in serialwin32.py just does `data = to_bytes(data)`)

**Comment by zsquareplusc** [comment]
OK, fixed that, but i'ts not the idea to support sending integers. The idea is to work with bytes, just like files and sockets do in Python too.
