### ISSUE TITLE
{}.format() Not Compatible with Python 2.6

### ISSUE THREAD

**Issue by schulzj01** [pyserial/pyserial#185]
When using the latest pyserial in 2.6, the {}.format() methods throw an error: 

`    ispeed = ospeed = getattr(termios, 'B{}'.format(self._baudrate))
ValueError: zero length field name in format`

For python 2.6 compatibility you need to have the argument numbers in the braces: 
   ispeed = ospeed = getattr(termios, 'B{}'.format(self._baudrate))
Becomes: 
   ispeed = ospeed = getattr(termios, 'B{**0**}'.format(self._baudrate))

**Comment by mnaberez** [comment]
pyserial doesn't support Python 2.6 according to its [classifiers](https://github.com/pyserial/pyserial/blob/dc56ac9002a5830442bff1e3c9ff9a34f3bc3e4e/setup.py#L85-L86) and [documentation](https://github.com/pyserial/pyserial/blame/dc56ac9002a5830442bff1e3c9ff9a34f3bc3e4e/documentation/pyserial.rst#L45-L50).

**Comment by zsquareplusc** [comment]
Sorry, see #28 for en [explanation](https://github.com/pyserial/pyserial/issues/28#issuecomment-401915518).
