### ISSUE TITLE
spy:// protocol doesn't work with stdlib urlparse

### ISSUE THREAD

**Issue by jof** [pyserial/pyserial#186]
I'm running into trouble with the latest v3.2.1 against python2.7 distributed with Debian Squeeze.

It seems that the stdlib urlparse keeps a list of protocol schemes which actually support query strings, and as a custom protocol name, "spy" isn't in this list.
As a result, the spy:// protocol URL functionality doesn't work.

Perhaps the spy:// protocol needs to register itself with urlparse as supporting query strings?

**Comment by jof** [comment]
Example code which is working for me in PR #187

**Comment by zsquareplusc** [comment]
Are you sure it's a Python 2.7 and not 2.6? https://wiki.debian.org/Python suggests it's the later.

Python 2.7.12 (on ubuntu) works for me:
```
>>> urlparse.urlsplit("spy://a?b")
SplitResult(scheme='spy', netloc='a', path='', query='b', fragment='')
```
(also tested with `python -m serial.tools.miniterm spy:///dev/ttyUSB0?color 115200`)

**Comment by jof** [comment]
Sorry to let this issue languish. I'm unable to reproduce anymore, but my environment has since upgraded to Debian Stretch and Python 2.7.13
With the latest v3.2.1, I can't reproduce this issue.
