### ISSUE TITLE
rfc2217.Serial() initialization broken

### ISSUE THREAD

**Issue by adrianer** [pyserial/pyserial#188]
When one initializes rfc2217.Serial() with a port, then all the attributes initialized by the parent method here https://github.com/pyserial/pyserial/blob/master/serial/rfc2217.py#L383 will be overwritten with "None" starting with this line: https://github.com/pyserial/pyserial/blob/master/serial/rfc2217.py#L384

The typical error one will get because of this is as follows (when calling write()):

`  File "/usr/local/lib/python2.7/dist-packages/serial/rfc2217.py", line 628, in write
    with self._write_lock:
AttributeError: __exit__`

Looks like this was broken starting in February this year because of PyLint comments... To fix this, all this None initializations of the attributes need to happen *before* calling super() - this way the correctly set ones won't get overwritten...

WORKAROUND:
-call rfc2217.Serial() without the port parameter and afterwards call open() on the returned object.

**Comment by zsquareplusc** [comment]
Thank you.

Ah yes, `super().__init__()` calls `open()` if a port name is given. This will use the attributes that are assigned `None` afterwards. Moving down the `super().__init__()` fixes that.
