### ISSUE TITLE
inWaiting returns port setting not bytes waiting

### ISSUE THREAD

**Issue by Mike-D2** [pyserial/pyserial#193]
I'm operating python 3.4 shell, with pyserial, recently downloaded and installed. I can read from the port ok, BUT the .inWaiting function returns a long string with all of the port settings, not the number of bytes waiting to be read.

**Comment by Mike-D2** [comment]
Sorry - forgot to say this is running on Rasperypie.

**Comment by zsquareplusc** [comment]
Old APIs `inWaiting()` is a function that needs to be called, in the new 3.x API there is a `in_waiting` property. My guess is that you did not actually call the function but got its "repr" which is a text about `bound method inWaiting of Serial<..settings..>`

**Comment by Mike-D2** [comment]
I called com1.inWaiting().... how does one call the function otherwise?
Also, what is the difference between import <module> and from <module> import *? These give completely different results in the program?

**Comment by zsquareplusc** [comment]
that's alright then, what does it print exactly?

pySerial is not designed to be used with `import *`

**Comment by Mike-D2** [comment]
it prints the ?repr? i.e. bound method etc.etc.  
how do I get just an int number of bytes waiting?

**Comment by Mike-D2** [comment]
tried com1.in_waiting :: threw error Serial has on attribute in_waiting

**Comment by Mike-D2** [comment]
fixed this by 
from serial import PosixSerial
then used int(com1.inWaiting)
