### ISSUE TITLE
serialwin32: spurios write fails with ERROR_SUCCESS

### ISSUE THREAD

**Issue by DietmarSchwertberger** [pyserial/pyserial#194]
Hi!
I'm using a USB device in CDC/VCP mode.
With heavy traffic, I get spurious exceptions on write, where win32.WriteFile returns a fail, but the error code is win32.ERROR_SUCCESS.
The data is written successfully to the device, though.
With the modification below things seem OK.
Do you see a risk with adding this to the repository? The non-blocking version seems to ignore this error code as well.

Regards,

Dietmar

serialwin32.py, lines 312...:
```
            success = win32.WriteFile(self._port_handle, data, len(data), ctypes.byref(n), self._overlapped_write)
            if self._write_timeout != 0:  # if blocking (None) or w/ write timeout (>0)
                if not success and win32.GetLastError() not in (win32.ERROR_IO_PENDING,win32.ERROR_SUCCESS):
                    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))

```

**Comment by zsquareplusc** [comment]
Yes, this makes sense. Thanks.
