### ISSUE TITLE
Escape sequences interupt pyserial client

### ISSUE THREAD

**Issue by iiSeymour** [pyserial/pyserial#198]
I'm writing a pyserial client and I'm getting a series of escape sequences from the device I'm connecting to that seems to be trying to discover the terminals capabilities. I'd like to know more about this process and how to handle it, this is not an issue with pyserial so I've posted a questions over [here](http://stackoverflow.com/q/41708420/1066031) on stackoverflow. Any pointers appreciated :smiley:

**Comment by zsquareplusc** [comment]
You'll have to add a filter in your protocol implementation to get rid of the escape sequences. But maybe the device has also a mode for "non-interactive" use where it does not send the escape codes.

**Comment by iiSeymour** [comment]
After digging around in the documentation for the device I found you can turn off terminal capability discovery by appending `+t` to username when authenticating. Filtering the sequencing wasn't the problem, I was already ignoring them, it was the delay after authentication as the device was waiting for a response to `1b 5b 39 39 39  39 42 1b 5a 20` before sending the command prompt.
