### ISSUE TITLE
Problem with inter_byte_timeout

### ISSUE THREAD

**Issue by rydsfoz** [pyserial/pyserial#22]
When run the instructions below:
(...)
self.port = serial.Serial(port, baudrate, timeout = 0.5, write_timeout = 0.5, inter_byte_timeout = 0.5)
print(self.port.get_settings())
(...)
result:
{'dsrdtr': False, 'rtscts': False, 'bytesize': 8, 'timeout': 0.5, 'inter_byte_timeout': None, 'baudrate': 115200, 'xonxoff': False, 'parity': 'N', 'write_timeout': 0.5, 'stopbits': 1}

I get as a result:
**'inter_byte_timeout': None**
instead of the
**'inter_byte_timeout': 0.5**

**Comment by zsquareplusc** [comment]
fixed by the commit referenced above.

**Comment by rydsfoz** [comment]
Thanks
