### ISSUE TITLE
[miniterm.py] Add option to save output to a file?

### ISSUE THREAD

**Issue by marrakchino** [pyserial/pyserial#234]
Hi,
I'm here to enquire about any plans to add a parameter which enables copying serial output to a file (sort of a log file to keep a trace of the serial communication) to **miniterm**.

Regards.

**Comment by ssldemon** [comment]
`miniterm.py @port @baudrate > output.txt`
should do the trick. my output is directed to output.txt when I use that

**Comment by nelqatib** [comment]
Does it preserve printing to standard output? I'm not sure...
The enhancement I asked about was to have both real-time printing to standard output, and (in the background), appending the same output to a file.

**Comment by nelqatib** [comment]
@zsquareplusc would you be interested if I work on this feature?

**Comment by craighurley** [comment]
On *nix based systems, if you want to view the serial traffic in the terminal as well as log to a file:

```sh
miniterm.py @port @baudrate | tee output.log
```
