### ISSUE TITLE
method in_waiting does not work

### ISSUE THREAD

**Issue by tom-ii** [pyserial/pyserial#239]
PS H:\> python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial       #       import serial library for ARDUINO comms
>>> TEMP_ARDUINO = 'COM3'
>>> BAUD_RATE = 57600
>>> TIMEOUT = 2
>>> # get a serial instance (we'll open it later)
... ser = serial.Serial()
>>> ser.baudrate = BAUD_RATE
>>> ser.port = TEMP_ARDUINO
>>> #ser.timeout = TIMEOUT
... ser.open()
>>> ser.in_waiting()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
>>> temp = ser.in_waiting()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
>>>

**Comment by zsquareplusc** [comment]
`in_waiting` is a property so you do not call it (leave away `()`).  The older API includes `inWaiting()` which is a method to be called.
