### ISSUE TITLE
Any plans to provide a conda distribution or conda-forge recipe

### ISSUE THREAD

**Issue by shaunwbell** [pyserial/pyserial#247]
pyserial 2.7 comes packaged with the anaconda python distribution but no clearly reliable fork/source for more recent versions is available

**Comment by bilderbuchi** [comment]
As I was just researching the same question, sounds like a great idea! Maybe you can take a shot at adding this to conda-forge, this seems to be the most promising step? I think it would be welcome, as other packages (optionally) using pyserial are already on conda-forge.
* The recipe of the pyserial in anaconda core is located [here](https://github.com/ContinuumIO/anaconda-recipes/tree/master/pyserial), it looks pretty simple/small.
* A nice step-by-step instruction for how to add recipes to conda-forge is [here](https://conda-forge.org/#add_recipe).

**Comment by shaunwbell** [comment]
Sure, I'll give it a shot... making a conda-forge recipe looks like a well documented process that would be a great learning session for myself.

Stay Tuned

**Comment by shaunwbell** [comment]
staged-recipe for V3.4 added and accepted to conda-forge.  Package should be available shortly.

I've listed myself as the conda-forge maintainer (meaning I bump the version when pyserial releases a new version) and will add anyone appropriate.

**Comment by bilderbuchi** [comment]
awesome, thank you! :+1: :rocket:

**Comment by shaunwbell** [comment]
currently available (build exists for linux only so far) for conda and will have osx and windows builds soon.

conda-forge repository available [https://github.com/conda-forge/pyserial-feedstock](https://github.com/conda-forge/pyserial-feedstock) - contributions and maintainers welcome.

**Comment by zsquareplusc** [comment]
@shaunwbell Thank you!
