### ISSUE TITLE
Is aio.py supposed to exist in the 3.4 whl file?

### ISSUE THREAD

**Issue by nugget** [pyserial/pyserial#254]
The current version pyserial-3.4-py2.py3-none-any.whl published on PyPi includes an aio.py code file which I believe should not be there.  That file was removed from pyserial in June 2016 (commit hash 494cb49837e794ec525e26b198da0e9467c4678b).  The file in the whl is older than that, though, and includes the typo "import logger" referenced in Issue #35 from November 2015.

The pyserial-3.4.tar.gz does not contain the file. Only the .whl.

**Comment by nugget** [comment]
It looks like this issue affects 3.2.1 as well, which contains a newer aio.py file than 3.4.0 does, but which I'm pretty sure should also not be in the .whl package.

**Comment by zsquareplusc** [comment]
interesting.. seems to be an artifact of `.pyc` files... `aio.pyc` was still in the build machine's `serial` directory. i've now removed that and the entire `build` folder where it apparently restored the `.py` file from.

**Comment by nugget** [comment]
This continues to be a problem.  Are there any plans for a release in the near future?  If not, it would definitely be worth re-packaging the .whl file for 3.2.1 at least so that people installing via PyPi don't have problems. 

To be clear -- anyone who has installed pyserial 3.2.0 or 3.2.1 is unable to use the pyserial-asyncio package because of the erroneous file in the whl you have published here on github and on pypi.

**Comment by teharris1** [comment]
Is there an update on this issue? There are issues in 3.2.0 that are also problematic so repackaging to get rid of the incorrect file is very important.

**Comment by teharris1** [comment]
@zsquareplusc is there an update? this seems like a very easy fix. It continues to be an issue for users of our module that references your module. When is your next release?

**Comment by nugget** [comment]
@zsquareplusc would you be willing to add me as a user on pypi so that I can fix this?  All that needs to be done is to replace the distribution files for 3.2.1 and 3.4 to remove the bad file.  This continues to be a real problem and is preventing many projects from using pyserial 3.4.  It seems like such a simple thing to fix -- I'd be happy to do it if possible.

**Comment by zsquareplusc** [comment]
beta release is out, please see #528
