### ISSUE TITLE
macOS ListPortInfo object short name is None

### ISSUE THREAD

**Issue by BrendanSimon** [pyserial/pyserial#262]
On macOS, the `ListPortInfo` object returned by `list_ports.comports()` has the `name` attribute set to `None`.

I have to workaround this using the `device` attribute and convert to a short name using `os.path.basename(device)`

PySerial 3.4
Python 3.6.2
macOS Sierra 10.12.6

**Comment by BrendanSimon** [comment]
Could this be fixed by placing the following at line 36 of `lists_ports_common.py`?

`self.name = os.path.basename(device)`

and can remove the equivalent line at line 27 of `lists_ports_linux.py`

That way the short name is set for all ports, at least as a default and can always be overridden for a specific platform if desired.

**Comment by zsquareplusc** [comment]
fixed in #263
