### ISSUE TITLE
PosixPollSerial.read fails when timeout=None (the default)

### ISSUE THREAD

**Issue by mvgrad98** [pyserial/pyserial#265]
If you do not use a timeout (the default) then the conversion to ms from seconds fails:
`TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`

https://github.com/pyserial/pyserial/blob/797018b53ddee79856e107f067c5873f53f73ee4/serial/serialposix.py#L742

Oddly there is already support for `_timeout` being `None` following the `poll()` call but I can't see how we would ever make it there if `_timeout` was `None`.

**Comment by zsquareplusc** [comment]
i guess that ``*1000`` came in later as the ``poll`` function does not take seconds as otherwise usual in Python APIs..

now using the ``Timeout`` helper class and i've added support for ``cancel_read()`` while at it
