### ISSUE TITLE
Ubuntu 16.04 kernel update from 4.8 to 4.10 breaks communication

### ISSUE THREAD

**Issue by doisyg** [pyserial/pyserial#266]
Hi,
I have a python 2 program using serial communication that works perfectly when running ubuntu 16.04 with kernel 4.8. However after the last ubuntu point release and the update to kernel 4.10 my program stops the serial communication without error after a few cycles. The problem disappear when going back to kernel 4.8 or 4.4. I also tried with kernel 4.12, same problem.
Tried to update pyserial and also rewrote my program to use python 3, same problem.
Any clue what could be the root cause?

**Comment by magicse7en** [comment]
Have you solved this issue ?

**Comment by diamondman** [comment]
@doisyg Could you close this issue?
