### ISSUE TITLE
Why is there no time.sleep in the ReaderThread run method?

### ISSUE THREAD

**Issue by mgiaco** [pyserial/pyserial#268]
Hi, 

I have looked into the ```serial/threaded/__init__.py```  Implementation because I have some timing issues in my app. I also do have some other threads running and if I use a concurrency analysis I found out that the Reader Thread do not wait for any amount of time. 

I am wondering why there is no time.sleep in the reader thread run method. 

So therefore I tried to test with time.sleep(2) as shown below but it dose not solve the issue. Also I do not see any changes in the analysis after the time.sleep what I do not understand.

```python

        self._connection_made.set()
        while self.alive and self.serial.is_open:
            try:
                # read all that is there or wait for one byte (blocking)
                data = self.serial.read(self.serial.in_waiting or 1)
                time.sleep(2)  # add a sleep here for some test
```

many thanks
mathias

**Comment by zsquareplusc** [comment]
The idea is that the port is opened in blocking mode or with a timeout, e.g. 3 seconds. Then `serial.read()` will block if there is no data, so no high CPU load should occur. If the port is accidentally opened with `timeout=0` then this will not block an cause high CPU load instead.

**Comment by diamondman** [comment]
@mgiaco Any chance you could close this question since zsquareplusc gave a good answer?

**Comment by mgiaco** [comment]
sure
