### ISSUE TITLE
Multiple Reader Threads

### ISSUE THREAD

**Issue by oicnysa** [pyserial/pyserial#271]
Hi, I'm rather new to pyserial and stuck with this silly questions.
I need to create multiple ReaderThread instances, to read from numerous serial ports.
Currently I'm doing it in a loop. Som kind of:
```
threads = []
for conf in config:
    thr = ReaderThread(ser, PrintLines).run()
    threads.append(thr)
```
But in this case it creates only first thread and code bellow this instructions is skipped.
Could you suggest how to deal with this situation?
Thank you in advance.

**Comment by zsquareplusc** [comment]
Do not call `run()`, this is what the thread is doing for you. You can call `start()` as you would on a regular Python `Thread` from the `threading` module.

**Comment by oicnysa** [comment]
I've used start() call before, but after connection_made, script suddenly exits(must read logs from serial).

**Comment by oicnysa** [comment]
Just forget to put join. Thank you very much.
