### ISSUE TITLE
Some written packets are dropped in Linux (Ubuntu 16.04.2)

### ISSUE THREAD

**Issue by jclevesque** [pyserial/pyserial#277]
I am using a cdc_adm device through pyserial, and on Linux I have issues. I ran the same code on Windows, OSX and Linux and I only have issues with the Linux version.

It looks like my written packets are not always received by the device. I tried various things, adding a 1 second timeout before writing anything through serial, flushing the input/output before writing, making sure that there is no pending output (through `Serial.out_waiting`), nothing seems to help. My device just never seems to receive the message.

I did find some sort of workaround by sending the message multiple times, like 10-20 times in a loop. 

How would you go about troubleshooting this problem? Should I just keep spamming my messages until I know for sure the device has caught them (in this case, by receiving and looking in status packets sent by the device)? Once again, this issue does not happen on other OSes (OSX, Windows 10), just sending the message once is enough. 

Used default parameters for baudrate and other pyserial settings. 

OS: Ubuntu 16.04.2
Linux kernel: 4.8.0-36-generic x86_64
pyserial version 3.4
python 3.5.2

**Comment by jabdoa2** [comment]
Are you using flow control? Does not sound like a pyserial issue

**Comment by jclevesque** [comment]
What do you mean by flow control? I send a command and then loop reading for the expected change in the device status but it almost never comes. 

Anyways, I ended up read/writing to the device from C++. I still have issues (although fewer), so it could be the device poorly answering requests.
