### ISSUE TITLE
Compatibility to Python 2.6

### ISSUE THREAD

**Issue by xavor92** [pyserial/pyserial#28]
Hey,

I'm developing using Python 2.7 but a user uses 2.6.

Some Modules throw errors because the usage of the str.format() function:
On Python 2.7 an index between the {} is optional, on 2.6 it is not.

I'm on my work PC without git so i can't submit the fix, and I also can't append a zip so you could merge, so sadly I can't do my part beside hinting you.

To fix:
Open IDE, search for every '{}' and replace with '{0}' (or '{0} - {1}') where needed.

Eg:
Your **str** from list_ports_common.py:

```
def __str__(self):
    return '{} - {}'.format(self.device, self.description)
```

My version:

```
def __str__(self):
    return '{0} - {1}'.format(self.device, self.description)
```

I love your work! Keep it up!

**Comment by jrobeson** [comment]
that's not a bug according to : https://pyserial.readthedocs.org/en/latest/pyserial.html#requirements  where it says Python 2.7 is the minimum requirement for pyserial 3.x

**Comment by xavor92** [comment]
Im sorry, I think i missed this bit. But other than that it seems to work fine :)
Anyone has an Idea what other problems can occour?

Thanks, Olli

**Comment by jrobeson** [comment]
I'm not sure, I'll leave it to the maintainer to say.

**Comment by jrobeson** [comment]
ping @zsquareplusc  ?

**Comment by zsquareplusc** [comment]
I'm not in favor of maintaining compatibility to Python 2.6. For one it is an old, no longer maintained release and while those changes seem to be small, at first, it may become a burden in the future an I guess it is a very small user base...

You could always just install an old version.. e.g.  `pip install pyserial==2.7` to get an older release that is still compatible to Python 2.6.
