### ISSUE TITLE
[windows] Serial Number Issues 

### ISSUE THREAD

**Issue by DuaneEllis-TI** [pyserial/pyserial#283]
For USB composite devices, Pyserial cannot extract extract the serial number. 
What Pyserial needs to do is look at the *parent* device 

When Pyserial extracts the "szHardwareID" - it gets a strings like (see below)
What I am seeing appears to be a "device instance string"
References:

a)  https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-instance-ids
b) https://msdn.microsoft.com/en-us/library/windows/hardware/jj649944(v=vs.85).aspx

What is needed is this:

Step 1 - if you cannot find the serial number ...

Call the function:  CM_Get_Parent() - pass:  devinfo.DevInst  for the current device.

This gives you the PARENT device ID (this is an ephemeral number - meaning it changes when you reboot the machine, or plug & unplug devices)  

Step 2:

Call the function CM_Get_Device_ID() - pass the PARENT ID  (from above) and a pointer to a buffer to hold the USB string.

Step 3: Inspect the parent USB Vendor ID & USB Product ID - compare with your base child.

Case 1:  
   They do not match - you are done. You have the USB Hub the device is connected to.
   If a serial number exists, it is in the child... 
   Some do not have serial numbers, see COM 114

Case 2:
   They match - but you can't find the serial number - See COM134 as the example.
   Try the parent again... you should only have to go up 2 or 3 times - 4 at most.
   The serial number - if it exists is on the top most element of the matching device.

Case 3:
    You found the serial number - Great success, and Profit!

Below are several examples, note: in this example I am only traversing up 5 levels of parents.

Some notes:

1) it would be helpful if PySerial could identify the MI_NUMBER as an additional attribute
  This corresponds to the USB interface index, not the "NTH-in-some-order"
  It should be the USB interface index number this never changes.
  Rational:  Some devices have multiple serial ports and you need the NTH port...

2) Composite example : COM98 & COM99  are from the same composite device - two interfaces
    (It happens to be a TexasInstruments Launch Pad - they have 6 USB interfaces)

3)  COM96 is a standalone USB cable from FTDI

4) COM147 - is a device from Ember (now SiLabs) it is a non-composite device.
   This is plugged into the side of my laptop which as an (VID_8087 - aka: Intel) USB Hub

5) COM114 - has no serial number, it has a CP110x usb converter
   And it does not have a "MI_XX" number... it is a non-composite device.

6) COM148 - is a an "ARM MBED" device - fairly common development board from ARM
   See:  https://www.mbed.com/en/  - for details

7)  COM150 - is a Linux USB Serial "Gadget" device

8) COM88 is a "Prolific" USB Serial cable

Example parent chains follow
```
COM61
        HW: FTDIBUS\VID_0403+PID_6001+FTGVOUN1A\0000
        Parent: USB\VID_0403&PID_6001\FTGVOUN1
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&3
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
COM88
        HW: USB\VID_067B&PID_2303\8&348F3717&0&4
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&3
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
        Parent: PCI\VEN_8086&DEV_9CA6&SUBSYS_062E1028&REV_03\3&11583659&0&E8
COM93
        HW: USB\VID_10C4&PID_EA60\0001
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&3
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
        Parent: PCI\VEN_8086&DEV_9CA6&SUBSYS_062E1028&REV_03\3&11583659&0&E8
COM96
        HW: FTDIBUS\VID_0403+PID_6001+FTD5RYSPA\0000
        Parent: USB\VID_0403&PID_6001\FTD5RYSP
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&3
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
COM98
        HW: USB\VID_0451&PID_BEF3&MI_03\9&33735DAE&0&0003
        Parent: USB\VID_0451&PID_BEF3\L110009R
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&2
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
COM99
        HW: USB\VID_0451&PID_BEF3&MI_00\9&33735DAE&0&0000
        Parent: USB\VID_0451&PID_BEF3\L110009R
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&2
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
COM114
        HW: USB\VID_10C4&PID_EA60\8&21D58672&0&6
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&2
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
        Parent: PCI\VEN_8086&DEV_9CA6&SUBSYS_062E1028&REV_03\3&11583659&0&E8
COM134
        HW: FTDIBUS\VID_0403+PID_A6D1+06EB12100A5AA\0000
        Parent: USB\VID_0403&PID_A6D1&MI_00\7&7ED7F17&0&0000
        Parent: USB\VID_0403&PID_A6D1\06EB12100A5A
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&3
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
COM147
        HW: USB\VID_10C4&PID_8A5E\0101CB55
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
        Parent: PCI\VEN_8086&DEV_9CA6&SUBSYS_062E1028&REV_03\3&11583659&0&E8
        Parent: ACPI\PNP0A08\0
        Parent: ACPI_HAL\PNP0C08\0
COM148
        HW: USB\VID_0D28&PID_0204&MI_01\0240000036934E45003840159F3500240E61000097969900
        Parent: USB\VID_0D28&PID_0204\0240000036934E45003840159F3500240E61000097969900
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&2
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
COM149
        HW: USB\VID_10C4&PID_EA60\ZOL-B001-A20000996
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
        Parent: PCI\VEN_8086&DEV_9CA6&SUBSYS_062E1028&REV_03\3&11583659&0&E8
        Parent: ACPI\PNP0A08\0
COM150
        HW: USB\VID_1D6B&PID_0104&MI_02\9&36E837AA&0&0002
        Parent: USB\VID_1D6B&PID_0104\2016BBBK2D5E
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&2
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
COM141
        HW: USB\VID_1CBE&PID_00FD&MI_00\9&1F89E0CD&0&0000
        Parent: USB\VID_1CBE&PID_00FD\0E221E86
        Parent: USB\VID_1608&PID_0181\7&9294DBA&0&2
        Parent: USB\VID_413C&PID_2513\6&4C6DDA4&0&4
        Parent: USB\VID_8087&PID_8001\5&BE46B3F&0&1
        Parent: USB\ROOT_HUB20\4&1D632659&0
```

**Comment by rdpoor** [comment]
+1 to this.  I arrived here via a different route.

My Windows system has an FTDI RS485 USB interface plugged in with serial number `FT3BNM1O` (according to the FTDI utilities).

However in `serial\tools\list_ports_windows.py:207 in iterate_comports(), after executing the line:

                szHardwareID_str = szHardwareID.value

the value of szHardwareID_str = `FTDIBUS\\VID_0403+PID_6001+FT3BNM1OA\\0000`.  Subsequent parsing of that string sets the serial number to be `FT3BNM1OA` (notice the 'A' suffix), which doesn't match the serial number of the device itself.

This means that I cannot use `comports()` to give me the serial number of the attached USB device.  (Bump! :)

**Comment by DuaneEllis-TI** [comment]
@rdpoor - The reason you have an "A" suffix is because you have a DUAL or QUAD ftdi device.

An example is the FTDI 2232 chip - it has 2 channels
Channel 0 - has the A suffix, Channel 1 has the B suffix.

In contrast, the FTDI 232 chip is a single channel..

All FTDI chips include (or support) an EEPROM of some sort (some are on chip, some are optional, it varies depending upon what you purchase)  there is a BIT in the EEPROM for each channel that tells the FTDI driver what mode it should be.

The WINDOWS driver - reads this bit and decides:  Enumerate the channel as COM =TRUE, or FALSE - do not enumerate as COM port.

The LINUX drivers generally ignore this bit.

**Comment by rdpoor** [comment]
@DuaneEllis-TI -- that would make sense, except that the part in question is an FT232R (a single channel device).  Honest.  On Mac OS X:

```
Found the following ports with FT232R parts:
{
  "device": "/dev/cu.usbserial-A932QG17",
  "name": null,
  "description": "FT232R USB UART",
  "hwid": "USB VID:PID=0403:6001 SER=A932QG17 LOCATION=20-1",
  "vid": 1027,
  "pid": 24577,
  "serial_number": "A932QG17",
  "location": "20-1",
  "manufacturer": "FTDI",
  "product": "FT232R USB UART",
  "interface": null
}
```

Same program running with the same USB device on Windows 7:

```
Found the following ports with FT232R parts:
{
  "device": "COM9",
  "name": null,
  "description": "USB Serial Port (COM9)",
  "hwid": "USB VID:PID=0403:6001 SER=A932QG17A",
  "vid": 1027,
  "pid": 24577,
  "serial_number": "A932QG17A",
  "location": null,
  "manufacturer": "FTDI",
  "product": null,
  "interface": null
}
```

**Comment by rdpoor** [comment]
Here's the code in case you'd like to replicate the experiment:

```
import serial.tools.list_ports
import json

# FTDI 232R serial chip
FT232R_VID = 0x0403
FT232R_PID = 0x6001

ports = serial.tools.list_ports.comports()
# filter down to only FT232R devices
ftdi = [p for p in ports if p.vid == FT232R_VID and p.pid == FT232R_PID]
print('Found the following ports with FT232R parts:')
for p in ftdi:
    print(json.dumps(p.__dict__, indent=2))
```

**Comment by vppillai** [comment]
I am also interested in getting a solution for this . I have a bunch of devboards that enumerate as a composite device. There is a way for me to programmatically get the serial numbers and identify the device type from it. However, since this functionality is missing, I cannot determine the COM port of these devices using the serial number.

**Comment by ryan-summers** [comment]
I was also having this issue with a test setup that I was working with where I needed to enumerate the serial number of a composite device on windows. I have implemented the fixes described in the original ticket and would appreciate feedback on the fix!

@DuaneEllis-TI Thanks for the excellent steps to fix this issue.

**Comment by hmaarrfk** [comment]
Even after PR #414, i'm still facing this issue:

```
python -m serial.tools.list_ports -v
COM13
    desc: APT USB Device Serial Port (COM13)
    hwid: USB VID:PID=0403:FAF0 SER=6
COM14
    desc: APT USB Device Serial Port (COM14)
    hwid: USB VID:PID=0403:FAF0 SER=6
COM15
    desc: APT USB Device Serial Port (COM15)
    hwid: USB VID:PID=0403:FAF0 SER=6
3 ports found
```

On linux, I am able to identify the expected Serial Numbers.

**Comment by ryan-summers** [comment]
@hmaarrfk Is there any chance you can attach the USB device tree in Linux here so we can see what the parent device chain looks like for these ports? The implementation in #414 follows the parent device traversal as specified in the original post. It is possible that there is a node in the parent device tree (with an identical VID/PID as the leaf devices) that has an internal serial number of 6. This would cause the backwards traversal to end earlier than anticipated.

**Comment by hmaarrfk** [comment]
Thanks I didn't know about the udevadm command. Will post when I go back to using that setup. Maybe just open an other issue if I can formulate it correctly

**Comment by hmaarrfk** [comment]
Please find attached.
```
udevadm info --attribute-walk /dev/ttyUSB0 > ttyUSB0_attribute_walk.txt
```
[ttyUSB0_attribute_walk.txt](https://github.com/pyserial/pyserial/files/3517876/ttyUSB0_attribute_walk.txt)
[com_ports_found on windows](https://github.com/pyserial/pyserial/files/3517879/com_ports_found.txt)

**Comment by ryan-summers** [comment]
@hmaarrfk Taking a look at your captures doesn't indicate that the issue is related to composite devices, which is what the original post in this thread is above and #414 fixes. It looks like your device only enumerates a single serial interface per device, but that single interface is improperly reporting the serial number (please correct me if I'm wrong here). I think that would warrant a different issue (and I would be happy to help you there). In order to help to implement a fix, I'll need to understand what the device tree looks like on windows. Please navigate to the device within the registry to get more info about it:

Below, I have navigated to a (VID:PID F055:9800), which has a serial number of 327133583436 (note that devices displayed here may not necessarily be plugged in). This specific device is a composite device, so you can see the &MI_00 and &MI_01 extensions below it (since it exposes a USB drive and a serial port). Please navigate to your VID:PID pair and highlight show which devices enumerate underneath the entry within a new ticket.
![image](https://user-images.githubusercontent.com/8771450/63328359-4bdafc80-c330-11e9-8c26-4c0e3fe89765.png)

**Comment by ryan-summers** [comment]
@hmaarrfk Looking at the `list_ports_windows.py` source code indicates that FTDI devices handle serial numbers slightly differently than other USB devices. Can you add in a `print(szHardwareID_sr)` to `serial/tools/list_ports_windows.py` (at line 320 works well) and run the updated script? This should print out the (device identification string)[https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-identification-strings] which we can use to figure out why the wrong serial number is reported.
