### ISSUE TITLE
Crash when port is compared to a non port object

### ISSUE THREAD

**Issue by frmdstryr** [pyserial/pyserial#286]
I have an application that uses a the `comports()` function to populate a combobox. When refreshing the ports, the UI compares the values to see if one of them matches the currently selected port. If no selection exists, the selection is `None` and it compares `port==None` which crashes as shown below.

```python
from serial.tools.list_ports import comports

comports()
Out[18]: []

comports()
Out[19]: [<serial.tools.list_ports_linux.SysFS at 0x7f4a343e4d50>]

ports = comports()

ports[0] == '/dev/ttyUSB0'

AttributeErrorTraceback (most recent call last)
<ipython-input-21-cc75c3accc1d> in <module>()
----> 1 ports[0] == '/dev/ttyUSB0'

/usr/local/lib/python2.7/dist-packages/serial/tools/list_ports_common.pyc in __eq__(self, other)
     72 
     73     def __eq__(self, other):
---> 74         return self.device == other.device
     75 
     76     def __lt__(self, other):

AttributeError: 'str' object has no attribute 'device'

ports[0] == None

AttributeErrorTraceback (most recent call last)
<ipython-input-22-dbbd483fcdf4> in <module>()
----> 1 ports[0] == None

/usr/local/lib/python2.7/dist-packages/serial/tools/list_ports_common.pyc in __eq__(self, other)
     72 
     73     def __eq__(self, other):
---> 74         return self.device == other.device
     75 
     76     def __lt__(self, other):

AttributeError: 'NoneType' object has no attribute 'device'
```

Is it possible to have the `__eq__`  method do an instance check before assuming the object it's comparing against has a `device` attribute?

Thanks!

**Comment by zsquareplusc** [comment]
I see, yes this would help with Python 2.7, but not with Python 3, where sorting lists of mixed types is no longer supported.

I've committed code that makes `__eq__` return false for comparing to a different type, but also to raise an exception in `__lt__` is such a case. That way the error messages in Python 3 make a bit more sense.

Sorry, this will not help fixing your observations mentioned above, unless your only comparing to equality. If that's the case I'd suggest to compare using `is` when checking for `None` as in `if ports[0] is None: ...` which avoids calling the equals operator.

**Comment by frmdstryr** [comment]
Thanks you!
