### ISSUE TITLE
Documentation refers to "readline()" and "realines()"

### ISSUE THREAD

**Issue by marcDesm** [pyserial/pyserial#293]
in the short intro at "http://pyserial.readthedocs.io/en/stable/shortintro.html"

It refers to readline() and readlines() (with an 's' ) Is this a typo?

here's the text:

"Be careful when using readline(). Do specify a timeout when opening the serial port otherwise it could block forever if no newline character is received. Also note that readlines() only works with a timeout. readlines() depends on having a timeout and interprets that as EOF (end of file). "

**Comment by zsquareplusc** [comment]
No, no typo. Those are two different methods. One returns one line, the other a list of lines.

See [io#readlines](https://docs.python.org/3/library/io.html#io.IOBase.readlines).

**Comment by patricktokeeffe** [comment]
Thanks @zsquareplusc for fixing! (I was confused when reading 3.0 docs) This & #285 are prob ok to close.

**Comment by mrx23dot** [comment]
This was a big bug for me,
readline() returns on \n reception, returns bytearray
readlines() waits for timeout, even when \n received, and returns a list of bytearray

please clarify in doc!

**Comment by zsquareplusc** [comment]
@mrx23dot  there is a chapter in the docs about this https://pyserial.readthedocs.io/en/latest/shortintro.html#readline not sufficient or not where you would expect it to find?

**Comment by mrx23dot** [comment]
I missed that, cheers!

**Comment by zsquareplusc** [comment]
updated docs. closing
