### ISSUE TITLE
OSError: [Errno 5] Input/output error (Raspberry Pi 3)

### ISSUE THREAD

**Issue by willnil** [pyserial/pyserial#297]
I am using Raspberry Pi 3 to run the RPLidar A2 Laserscanner. I have tried the python codes in my windows laptop the code works and I can get the scan datas. But when I tested it in the RPi 3 with Raspbian, the following error occured. 
I am new to Python and after I checked online OSError is due to environment factors. So can someone explain to me what is the problem now and maybe solution to it? Is it due to hardware problem? Thanks alot :)

> Traceback (most recent call last):
> File "/home/pi/example.py", line 10, in
> for i, scan in enumerate(lidar.iter_measures()):
> File "/usr/local/lib/python3.5/dist-packages/rplidar.py", line 397, in iter_measures
> raw = self._read_response(dsize)
> File "/usr/local/lib/python3.5/dist-packages/rplidar.py", line 223, in _read_response
> while self._serial.inWaiting() < dsize:
> File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 572, in inWaiting
> return self.in_waiting
> File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 456, in in_waiting
> s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
> OSError: [Errno 5] Input/output error

**Comment by rssw** [comment]
Did you manage to solve this issue?

**Comment by willnil** [comment]
yes
it was because of my hardware problem.
