### ISSUE TITLE
RFC: Update API for list_ports.comports()

### ISSUE THREAD

**Issue by hardkrash** [pyserial/pyserial#3]
The list of lists that is returned by ```serial.tools.list_ports.comports()``` is inflexible and prone to error.

Code and responses are from Python 3.4.3 running on OS X

For example in this invocation of ```comports()``` I get back a reply of

```python
[['/dev/cu.Bluetooth-Incoming-Port', 'n/a', 'n/a'],
 ['/dev/cu.Bluetooth-Modem', 'n/a', 'n/a'],
 ['/dev/cu.usbserial', 'USB-Serial Controller', 'USB VID:PID=67b:2303 SNR=None']]
```

Now I can try matching with a grep on element 2 of each possible port but this is fragile across operating systems.  On OS X we have some os specific USB properties such as location ID and if the device is considered a modem or a plain RS232 serial stream.

Location ID is a 32bit number that maps to a specific location on the USB bus that will not change if the hub topology is not changed upstream of the device.  i.e. if you leave your USB bus alone the location ID will not change.  This is useful for working with USB micro controllers that switch modes.  e.g. from a USB-CDC interface you could issue a command to your part to enter a USB-DFU mode. If you knew your location ID before, you could attach to a DFU interface at that location ID.

As different systems have different serial port metadata, I propose a list of dictionaries to be returned by ```comports()```.

the above example would become

```python
[
  {'device': '/dev/cu.Bluetooth-Incoming-Port'},
  {'device': '/dev/cu.Bluetooth-Modem'},
  {'device': '/dev/cu.usbserial',
    'USB PID': 8963,
    'USB VID': 1659, 
    'name': 'USB-Serial Controller',
    'location_id': 0xfa130000,
  },
]
```
Clearly this dictionary only includes keys that are populated. We could use the  ```collections.DefaultDict``` to default non existent keys to ```None``` for convenience.

Alternatively we could use a named tuple and make the return more static.

Function name could change to maintain compatibly.
Thoughts?

**Comment by zsquareplusc** [comment]
So far I have two use cases for list_ports:
* get a list of port and human readable descriptions, used e.g. in a GUI drop-down box for the user to select a serial port
* use hwgrep://NAME to match one or two specific USB-serial device types

I don't think i've ever used the resulting list of tuples in an application for something else. The first case is solved by using the strings as-is, and the second by using list_ports.grep() or by use of the hwgrep:// URL form and serial_for_url.

Therefore I do not yet see the advantage of having a dictionary as result.

you've added a third one
* firmware update on (USB) devices where the device alters its ID during the upgrade, identify the device in both modes

Though in my experience that one is not such a big problem. As usually only one device is updated at a time, there is only one with a different identification, specific to the updater. So the update tool can easily identify the devices in both modes. And other operating systems may not provide such a location so relying on it is not possible when writing cross platform applications.


* One improvement could be to add the location to the 3rd string in the tuple. Add as many useful identification properties as there are available...
* Yes, a named tuple is probably a good idea (now that we only need to support Python versions that have it)
* A middle ground could also be to use a dedicated result class that acts like a tuple of 3 items when accessing via index but has access to single fields with getattr. e.g. `port, desc, hwid = result` and `result.SNR`, `result.VID` etc. (The stanard libs' `urlsplit` has something similar as result)  (+1)

**Comment by hardkrash** [comment]
My proposal is to add a lower level function that returns a named tuple or dictionary with a minimum of the information necessary to populate comport's information.  With that have comports() call that function.

My experience with DFU is that I update 12 devices in batch.  I pre-load 12 USB device on a hub and attach the hub.  Every factory on the planet needs a DFU tool that supports more than one DFU device at a time.  Only an engineer or a user can get away with 1 at a time limit. So, I wrote a Python based DFU tool that didn't explode when more than one device was in DFU mode.

Other use cases:
- Multiple of the same USB to serial devices that do not have a unique serial number. (example below)
  - I think that windows device driver locking can force a constant comport assignment.
  - Mac You're out of luck!
  - Linux, BSD, or other posix???
- Matching embedded FTDI chips behind a hub buried inside of equipment.
  - Higher bits on location ID are the same as you progress down the USB bus.
  - USB 3.0 port_numbers is a tuple that extends similarly.
- Checking if upstream hubs are MTT to prevent communication bottlenecks with many USB ports.
  - Someone has taken my nice 12 port industrial hub out of a setup and swapped in a 4 port that didn't have MTT nor sufficient power, but the station only needed 4 ports... :boom: 
- Erring out if a user changes physical USB ports. (alternative methods exist, but not as simple)

USB 3.0 specifies a ports parameter that has the same effect.  location ID happens to map exactly to USB 3.0 port_numbers.  My example if location ID is not the only important fact.  USB 2.0 drivers don't have that value.

Just as you coded in a ```'nt'``` console and ```'posix'``` console in miniterm,  It's nice to be able to use the available data from your operating system to meet your needs when you need to.

My internal patched version appended a dictionary to the tuple returned by comports.
I didn't want to preclude hwgrep or grep from working, I do use them often.

```python
pprint(comports()[2])
['/dev/cu.usbserial',
 'USB-Serial Controller',
 'USB VID:PID=67b:2303 SNR=None',
 {'USB Address': 0x4,
  'USB Bus': 253,
  'USB Location': 0xFD120000,
  'USB Manufacturer': 'Prolific Technology Inc.',
  'USB PID': 0x2303,
  'USB Product Name': 'USB-Serial Controller',
  'USB VID': 0x67B,
  'device': '/dev/cu.usbserial'}]
```

Cross platform compatibility should not preclude features that are flexible and robust.  Such as matching dictionaries, named tuples, hwgrep, etc..  I don't think that HW grep should be overloaded too much. Practicality beats Purity :-)

> Special cases aren't special enough to break the rules.
> Although practicality beats purity.
> Tim Peters - PEP 20 - Zen of Python


Here is a IPython session with pyusb and sharing info with pyserial
```
In [1]: import serial.tools.list_ports as slp
In [2]: md = slp.comports()[2][3]
In [3]: md
Out[3]: 
{'USB Address': 0x4,
 'USB Bus': 253,
 'USB Location': 0xFD120000,
 'USB Manufacturer': 'Prolific Technology Inc.',
 'USB PID': 0x2303,
 'USB Product Name': 'USB-Serial Controller',
 'USB VID': 0x67B,
 'device': '/dev/cu.usbserial'}
In [4]: import usb.core
In [5]: dev = usb.core.find(idVendor=md['USB VID'], idProduct=md['USB PID'])
In [6]: dev
Out[6]: <DEVICE ID 067b:2303 on Bus 253 Address 004>
In [7]: dev.port_numbers
Out[7]: (1, 2)
In [8]: loc_id = dev.bus << 24 | dev.port_numbers[0] << 20 | dev.port_numbers[1] << 16  
In [9]: hex(loc_id)
Out[9]: '0xfd120000'
In [10]: loc_id == md['USB Location']
Out[10]: True
```

**Comment by zsquareplusc** [comment]
I've changed the Linux and Windows implementations to return an object that supports indexed access as before but also allows to keep additional information, such as a `vid`, `pid` and `serial` attribute.

I did not find any comprehensive info on how to calculate that location ID. Seems like multiple, but not necessarily the same, things are called like that.

**Comment by zsquareplusc** [comment]
Now also with a `location`attribute. I've chosen to make it a string as seen on Linux: `bus-port[.port]...`
I've updated the Linux and Windows implementations.

**Comment by zsquareplusc** [comment]
The object returned by `list_ports` now supports additional info on Linux, Windows and OSX.
USB info is available as attributes `vid`, `pid` and `serial_number` but also texts like `product` and `manufacturer` are there. The location is now supported on all the mentioned platforms in the same form, under the `location` attribute.
