### ISSUE TITLE
Miniterm works ... my program doesn't :/ 

### ISSUE THREAD

**Issue by SandyWalsh** [pyserial/pyserial#311]
pySerial 3.4, python 2.7.12, Ubuntu 16.04.3 LTS

Trying to write some commands to an Arduino. 

Using miniterm works great ... 
```
> python -m serial.tools.miniterm

--- Available ports:
---  1: /dev/ttyACM0         'ttyACM0'
--- Enter port index or full name: 1
--- Miniterm on /dev/ttyACM0  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
2422224
--- exit ---
```

I can send my "blink#" instructions and get the count echoed back (the 2422224). 

However, when I try to do this via my own python program, no joy ... 

```
import serial
import time

ser = serial.Serial("/dev/ttyACM0", timeout=1)
msg = bytearray(b'blink4\n'.encode())
print ser.get_settings()
print ser.port
print "Writing", msg
print "Wrote: ", ser.write(msg)
print "Out waiting", ser.out_waiting
time.sleep(3)
print "got:", len(ser.read(1))
ser.close()
```

Even more bizarre ... if I open the connection with miniterm in one terminal and then run my program in another terminal it works fine (and the response is picked up in miniterm).

I suspect there's something wonky with the connection info, but I've tried every way of setting 9600/8N1 with the same results. 

The output looks like things are good (except for the response)

```
{'parity': 'N', 'baudrate': 9600, 'bytesize': 8, 'xonxoff': False, 'rtscts': False, 'timeout': 1, 'inter_byte_timeout': None, 'stopbits': 1, 'dsrdtr': False, 'write_timeout': None}
/dev/ttyACM0
Writing blink4

Wrote:  7
Out waiting 0
got: 0
```

I don't have the Arduino IDE open nor any other terminal attached to the Arduino. 

So bizarre ... any suggestions would be greatly appreciated.

**Comment by SandyWalsh** [comment]
Hmm, ok, I put a `time.sleep(1)` after the open. Now it works. 

Could this just be latency in the device driver?

**Comment by SandyWalsh** [comment]
heh, ok, I added a `time.sleep(2)` after the `Serial()` and before the `write()` ... and it works. 

Could this just be driver latency?

**Comment by Buzzology** [comment]
I hit this same issue and found this thread via google so just for anyone else coming across this I think it's the same as this one: https://arduino.stackexchange.com/a/58084/37451. 

Apparently you can also use `setDTR(Flase)` but it didn't seem to work on my nano clone: 
```
    serial1 = serial.Serial()
    serial1.port = PORT
    serial1.baudrate = BAUD_RATE
    serial1.timeout = 1
    serial1.setDTR(False)
    serial1.open()
```
