### ISSUE TITLE
Windows does not enumerate COM ports associated with other devices

### ISSUE THREAD

**Issue by DomAmato** [pyserial/pyserial#314]
I have a USB cellular modem which has 2 COM ports associated with it, one shows up in the device manager under the Ports (COM & LPT) the other under Modems. Performing serial.tools.list_ports only shows the one in the Ports. 

The port under the modems is actually the more important one as it is the one needed to send AT commands to control the modem. I can connect and send/receive data using arduino's serial monitor which properly enumerates the port.

For reference the Modem GUID _{2C7089AA-2E0E-11D1-B114-00C04FC2AAE4}_ is mentioned here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-modem

**Comment by CNXinfengwang** [comment]
Please try to use GUID_DEVINTERFACE_COMPORT in list_ports_windows.py.
in the \Lib\site-packages\serial\tools\list_ports_windows.py file, update the GUID[0]
# repeat for all possible GUIDs
    GUIDs[0].Data1=0x86E0D1E0
    GUIDs[0].Data2=0x8089
    GUIDs[0].Data3=0x11D0
    GUIDs[0].Data4[0]=0x9C
    GUIDs[0].Data4[1]=0xE4
    GUIDs[0].Data4[2]=0x8
    GUIDs[0].Data4[3]=0x0
    GUIDs[0].Data4[4]=0x3E
    GUIDs[0].Data4[5]=0x30
    GUIDs[0].Data4[6]=0x1F
    GUIDs[0].Data4[7]=0x73
    for index in range(guids_size.value):
        bInterfaceNumber = None
        g_hdi = SetupDiGetClassDevs(
            ctypes.byref(GUIDs[index]),
            None,
            NULL,
            DIGCF_PRESENT|DIGCF_DEVICEINTERFACE)

**Comment by DomAmato** [comment]
for some reason changing that GUID made no difference, even if I made double sure that it had changed and that it was valid and devices would enumerate using the winAPI. However changing it to this did work:

```
    GUIDs = (GUID * 8)()  # so far only seen one used, so hope 8 are enough...
    total_guids_size = 0
    guids_size = DWORD()
    tempGUIDS = (GUID * 4)()
    if not SetupDiClassGuidsFromName(
            "Ports",
            tempGUIDS,
            ctypes.sizeof(tempGUIDS),
            ctypes.byref(guids_size)):
        raise ctypes.WinError()
    
    total_guids_size = guids_size.value;
    for index in range(guids_size.value):
        GUIDs[index] = tempGUIDS[index]
    
    if not SetupDiClassGuidsFromName(
            "Modem",
            tempGUIDS,
            ctypes.sizeof(tempGUIDS),
            ctypes.byref(guids_size)):
        raise ctypes.WinError()

    for index in range(guids_size.value):
        GUIDs[total_guids_size+index] = tempGUIDS[index]

    total_guids_size = total_guids_size + guids_size.value;

    # repeat for all possible GUIDs
    for index in range(total_guids_size):
```
Doing this returned the same GUID but without both in the GUID array it would return either the ports or the modems, not both.

With some debug print statements it looks like this:
```
Setting index 0 to GUID {4d36e978-e325-11ce--41-3f-08002b-1f0318}
Setting index 1 to GUID {4d36e96d-e325-11ce--41-3f-08002b-1f0318}
{4d36e978-e325-11ce--41-3f-08002b-1f0318}
{4d36e96d-e325-11ce--41-3f-08002b-1f0318}
{00000000-0000-0000-0000-000000000000}
{00000000-0000-0000-0000-000000000000}
{00000000-0000-0000-0000-000000000000}
{00000000-0000-0000-0000-000000000000}
{00000000-0000-0000-0000-000000000000}
{00000000-0000-0000-0000-000000000000}
COM3: u-blox Modem USB3 AT and Data (COM3) [USB VID:PID=1546:1102 SER=6 LOCATION=1-2:x.4]
COM4: u-blox Modem USB2 AT and Data (COM4) [USB VID:PID=1546:1102 SER=6 LOCATION=1-2:x.2]
COM6: u-blox Modem USB4 GPS (COM6) [USB VID:PID=1546:1102 SER=6 LOCATION=1-2:x.6]
COM7: u-blox Modem USB7 SAP (COM7) [USB VID:PID=1546:1102 LOCATION=1-2:x.4]
COM8: u-blox Modem USB6 Secondary Log (COM8) [USB VID:PID=1546:1102 LOCATION=1-2:x.2]
COM9: u-blox Modem USB5 Primary Log (COM9) [USB VID:PID=1546:1102 SER=6 LOCATION=1-2:x.8]
COM11: u-blox Modem USB1 AT and Data [USB VID:PID=1546:1102 SER=6 LOCATION=1-2:x.0]
COM13: Qualcomm HS-USB Modem 90B2 [USB VID:PID=05C6:90B2 SER=6 LOCATION=1-3:x.2]
COM14: Qualcomm HS-USB MDM Diagnostics 90B2 (COM14) [USB VID:PID=05C6:90B2 SER=6 LOCATION=1-3:x.0]
```

For reference normally 11 and 13 would not enumerate

**Comment by CNXinfengwang** [comment]
Change the GUID  to GUID_DEVINTERFACE_COMPORT works with my setup, for the following 
SetupDiGetClassDevs , please use DIGCF_PRESENT|DIGCF_DEVICEINTERFACE.

**Comment by DomAmato** [comment]
Sorry to take so long to get back but that doesn't work. It will enumerate the device that is listed under Ports (COM & LPT) but not the modem. Changing to what you recommended outputs:

`COM14: Qualcomm HS-USB MDM Diagnostics 90B2 (COM14) [USB VID:PID=05C6:90B2 SER=6 LOCATION=1-3:x.0]`

but not the device that is needed to actually write serial data to, COM13, as I mentioned above.
