### ISSUE TITLE
Listing serial ports on python3 (Mac OS X)

### ISSUE THREAD

**Issue by tfeldmann** [pyserial/pyserial#32]
I tried to use the built-in port listing function but got different results depending on the python version. I'm using Mac OS X 10.11.

``` sh
Python 2.7.5 (default, Nov  4 2013, 18:04:45) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from serial.tools import list_ports
>>> list_ports.comports()
[['/dev/cu.Bluetooth-Incoming-Port', 'n/a', 'n/a'], ['/dev/cu.Bluetooth-Modem', 'n/a', 'n/a']]

Python 3.3.5 (default, Mar 10 2014, 13:25:50) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from serial.tools import list_ports
>>> list_ports.comports()
[]
```

A patch seems to be available here: http://sourceforge.net/p/pyserial/patches/38/
Stackoverflow discussion: http://stackoverflow.com/q/22467683/300783

Edit: I'm using the pyserial version from pypi but will give the beta a try soon!

**Comment by diegoherranz** [comment]
On the sourceforge discussion it says that [it has been committed already](http://sourceforge.net/p/pyserial/patches/38/#a8f1) on this github repo.

This is the commit where it was fixed: 5c4d2d8

**Comment by hoihu** [comment]
I can confirm that this is working (tested on OSX 10.11.4 with the current pyserial version)
@zsquareplusc  / @tfeldmann : I guess this issue can be closed.

**Comment by diamondman** [comment]
@tfeldmann Can you test the new change and close out this issue if everything looks good?

**Comment by tfeldmann** [comment]
Can confirm this is working with macOS 10.14.5 👍

**Comment by Scobber** [comment]
for com in list_ports.comports():
  print(com)

otherwise it will only print handles
