### ISSUE TITLE
Update tools.list_ports documentation

### ISSUE THREAD

**Issue by diegoherranz** [pyserial/pyserial#33]
`list_ports.comports()` has notably changed in 3.0 but [the documentation](https://pyserial.readthedocs.org/en/latest/tools.html#serial.tools.list_ports.comports) hasn't been updated.

Thanks!

**Comment by diegoherranz** [comment]
Thanks for the fast commit.

Just had a quick look and I think that `vid` and `pid` are integers instead of strings.

Thanks again, pyserial 3.0 looks amazing.

**Comment by zsquareplusc** [comment]
Yes those are integers, thanks.

**Comment by diegoherranz** [comment]
Thanks again!
