### ISSUE TITLE
Set eol default to CR or CRLF based on platform introspection?

### ISSUE THREAD

**Issue by cefn** [pyserial/pyserial#336]
Copy-paste into a Micropython terminal works well with GNU screen, but miniterm has a weird artifact when copy-pasting that I would like to diagnose and fix.

Micropython paste mode, (which suppresses python auto-indent) is successfully triggered by CTRL+E in both screen and miniterm.  

It presents as comprehensible and usable with GNU Screen, as invoked like `screen /dev/ttyUSB0 115200`...

```python
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== from time import sleep
=== from machine import Pin
=== from vgkits.ws2811 import *
=== 
>>> 
```

However, for some reason, a paste into Miniterm from within the same desktop terminal, and to the same UART shell on the same device, adds extra newlines or carriage returns into the terminal when copy-pasting, which has the effect of junking the readability of the pasted code. For example, this session invoked like`python3 -m serial.tools.miniterm --raw --encoding ascii /dev/ttyUSB0 115200`.

```python
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== from time import sleep
=== 
from machine import Pin
=== 
from vgkits.ws2811 import *
=== 

>>> 
``` 

Is there some flag I can use to eliminate this behaviour, or is it somehow to do with the way Miniterm actually sets up pipes of characters and is somehow baked into the system? 

# BACKGROUND QUESTION

I would really prefer to use miniterm compared to GNU Screen, for cross-platform compatibility as part of support packages (mostly authored in python) as part of the [vgkits.org](https://vgkits.org) initiative.

For example, I can wrap miniterm easily from within my tool suite.

```python
import sys
from serial.tools import miniterm
import config, command

minicomCommand = "serial.tools.miniterm --raw --encoding ascii ${port} ${baud}"
minicomLookup = config.hardwareConfig()
command.emulateInvocation(minicomCommand, minicomLookup)
miniterm.main()
```

Unfortunately, copy-pasting from a text-editor into the shell for interactive debugging and learning is part of the core way of working I would like to share with learners of python. Is use of Miniterm and use of paste mode across platforms destined to fail?

**Comment by cefn** [comment]
For reference, this was a remaining issue after https://github.com/pyserial/pyserial/issues/238 resolved most other issues relating to command codes, but linefeed issue remained. Sorry not to remember this was also reported as part of that original issue. 

I will report more detail on the use of the --eol flag which was mentioned.

**Comment by cefn** [comment]
Use of --eol CR resolved the issue for Linux. I guess I will have to do some platform introspection to switch the right mode, unless Miniterm chooses to configure the default for eol using platform-specific logic... 

https://github.com/pyserial/pyserial/blob/fac1c13495e1051563b4e4d45093fe80f428f763/serial/tools/miniterm.py#L839-L844

**Comment by zsquareplusc** [comment]
I'd like to have the same settings across all platforms. That makes it easier to diagnose problems with devices. So if a user tries something with miniterm, you do not need to know the OS it is running on.

Specifically for MicroPython, you might get happier with the patched version included here: https://github.com/zsquareplusc/mpy-repl-tool  (`-i` option runs the terminal)
It has some workarounds to work with escape sequences used by MicroPython REPL. So it runs at least partially usable on Windows too...

**Comment by cefn** [comment]
Not sure from what layer the Unix-specific line endings are coming, but I considered this may be a way to **minimise** problems with devices, hopefully **increasing** consistency in performance, at the cost of knowing it uses platform-specific line endings. If I understand the situation, I think something which works on Windows would actually break on Linux because it isn't tracking the os.linesep, meaning you have a different kind of inconsistency. However, I'm pretty clueless where the difference comes from anyway, and you have the experience dealing with diagnosing lots of peoples' problems from lots of environments. Just asking. Thanks for the reference to mpy-repl-tool. When I get done fighting through the launch of VGKits I hope to get back to lots of experimentation.

**Comment by zsquareplusc** [comment]
miniterm defaults to CRLF because modems and such seem to like that for historic reasons. I guess many applications are also happily receiving an extra CR even if they just need LF, so it work in many cases.

Not sure but MicroyPython may accept both, CR and LF as a "new line" command (maybe just in paste mode?)  and therefore inserts empty lines.
