### ISSUE TITLE
Is this code still maintained?

### ISSUE THREAD

**Issue by teharris1** [pyserial/pyserial#339]
This is a really good library and very useful. I would hate for it to go to waste. I know managing an open source lib is tough and time consuming, but I am hoping this can get support. I see a lot of open PRs and issues and the last release was Oct 14, 2016, not counting the two releases that were recalled. But I see a lot of people contributing PRs so clearly there is a need and a desire to help.

**Comment by zsquareplusc** [comment]
Yes it is still maintained, it is just not so easy to find time to look at those issues and pull requests thoroughly....

**Comment by diamondman** [comment]
@zsquareplusc Any chance you could deputize some people to help crush the backlog? I would be happy to give a weekend or two to work on it myself/with others, and maybe propose a short list of actions for you to approve?

**Comment by Harvie** [comment]
Are there any good pyserial alternatives?

**Comment by zsquareplusc** [comment]
beta release is out, please see #528
