### ISSUE TITLE
Cannot detect Windows Arrow Keys

### ISSUE THREAD

**Issue by cefn** [pyserial/pyserial#349]
Hi there,

Having problems sending arrow key events in Command.exe on Windows 10. I am using a serial connection to a Micropython board ( https://vgkits.org/blog/2018/05/08/introductory-video-tutorial/ ) as a worked example.

Not sure if this is a different issue to https://github.com/pyserial/pyserial/issues/207 as the modified version of miniterm indicated in that thread doesn't seem to resolve the issue.

On Mac and Linux, miniterm seems to be fine, launched as documented here...
https://vgkits.org/blog/connecting-with-miniterm/
...and the arrow keys work fine on Mac and Linux too.

However, the Windows invocation documented there creates a console session in which arrow keys and backspace keys are junked.

The invocation I tried most recently on Windows (note this was an attempt to use the 'patched miniterm-MPY') was...

```bash
python miniterm_mpy.py --raw --eol CRLF --encoding ascii COM3 115200
```

This leads to a terminal in which pressing the up key produces first...

```
?H?
```

...and then if you press again it seems to send an up arrow key and shows...

```
 clearPixel()
```

...then if you press again it shows 

```
 clearPixel()[12DsetPixel(0, red)
```
...and finally...
```
 clearPixel()[12DsetPixel(0, red)[16D[K4+4
```

What it should show is single, clear lines drawn from the history one by one as you press up and down like...

```
clearPixel()
setPixel(0, red)
4+4
```

I'd really like to know that I don't have to guide users to run everything inside the Ubuntu subsystem on Windows 10 just to get a terminal to work, but it sounds like that might be true.

**Comment by cefn** [comment]
OK, even with colorama installed, almost all keys are borked. However, the up key seems to work from a single press WITH colorama in a way it didn't before, so I'll investigate this as a lead.

**Comment by cefn** [comment]
OK, things are much improved by running with UTF-8 like..


```
python miniterm_mpy.py --raw --eol CRLF --encoding utf-8 COM3 115200
```

but still many keys are badly mapped and weird character codes appear. For example backspace doesn't delete in the terminal.

**Comment by cefn** [comment]
Now I've been running miniterm_mpy.py in PyCharm to intercept keys and managed to detect the backspace key reliably which seems to be chr(8), but I don't know what its mapping should be (as indicated by the MAP_SPECIAL_KEYS and MAP_F_KEYS dictionaries). While the mappings there for the Arrow keys seem to be well-functioning, the others (such as Home, Delete) seem to be compromised too, when running using...

```
python miniterm_mpy.py --raw --eol CRLF --encoding utf-8 COM3 115200
```

...the arrow keys work, but using the mapping from delete seems to create a junk character followed by K.

I don't mind trying to figure out the proper mappings if I know what the range and domain of the mapping function should be. I found https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idoutputsequencesspanspan-idoutputsequencesspanspan-idoutputsequencesspanoutput-sequences which seems to have commonalities with the tables in MAP_F_KEYS but I still can't seem to derive enough information from these tables to fix the mapping of the backspace key.

**Comment by cefn** [comment]
OK, I've found a configuration in which perhaps all the mapped keys of MAP_F_KEYS and so on are actually working.

```
python miniterm_mpy.py --filter direct --eol CRLF --encoding utf-8 COM3 115200
```

However, while backspace causes the cursor to go backwars, and delete causes characters to be moved from the right as if their predecessors were being deleted, in both cases they don't remove the actual characters within the CMD.exe character grid, so for example, you can type 'hello', then press backspace 5 times, which brings the cursor back under the h but hasn't visibly deleted the word. Meanwhile Micropython believes you HAVE deleted the word, so behind the scenes the right stuff is happening, but it's not visible on screen.

Is this an issue which is better directed to colorama now? My brain is melting from trying to make sense of the layers here, and which part is responsible for issuing matching changes for a backspace action, to make the corresponding characters disappear from the CMD.exe 'buffer'.

Probably I need to wrap up this bug which has gone crazy and was mostly down to not having the right options passed to miniterm. I'll report a new one which is easier to parse so maintainers can ignore all the stream of consciousness above, and I think what remains needs to go to colorama anyway.

**Comment by dominikandreas** [comment]
exactly the same issue here.. @cefn why did you close this issue? as long as it's not resolved, I'd keep it open

**Comment by zsquareplusc** [comment]
i'm working on a [not-so-]mini-terminal here [pySerial-terminal](https://github.com/pyserial/pyserial-terminal). it supports much more of the special keys.
