### ISSUE TITLE
occasional missed packets

### ISSUE THREAD

**Issue by rdpoor** [pyserial/pyserial#352]
## Environment:
* macOS High Sierra (10.13.5)
* QinHeng Electronics HL-340 USB-Serial adapter (VID:PID = 1A86:7523)
* pyserial 3.4
* Python 3.6.2
## Statement of the problem
When performing async read operations, once in a (great) while, no packet is received.
## Details
I'm sending Modbus RTU packets from an embedded device at 19200 baud over an RS485 link to the aforementioned serial adaptor.  Once in a while the `serial.read(256)` operation fails to read any bytes, although my oscilloscope confirms that the bytes were transmitted.  

My code is (approximately):

    serial.baudrate = 19200
    serial.timeout = 0.0
    ...
    serial.write(write_buffer)
    while not end_of_packet:
        read_buffer = bytearray()
        fragment = serial.read(256)
        if len(fragment)>0:
            read_buffer.extend(fragment)
            time.sleep(0.002)
        else:
            # didn't get any bytes this time around -- signal end of packet

I understand that this may not be an issue with pyserial at all -- it could be a USB driver problem, etc.  
## The real question
What tests can I do to refine where the problem lies?  I s'pose a low-level stress test written in C would be useful.

**Comment by zsquareplusc** [comment]
any special cause to use `timeout = 0`? That makes it non-blocking and a simple read loop will eat up all CPU doing mostly empty reads...

see also http://pyserial.readthedocs.io/en/latest/pyserial_api.html#module-serial.threaded

**Comment by rdpoor** [comment]
@zsquareplusc : 

First, an apology and correction: I neglected to show the `sleep(0.002)` in my code following the `read()`.  (I'll go back and correct the original.)

But that doesn't really address your comment.  I'm certainly open to using a blocking read if it can be made to work for this application.  But my choice for a non-blocking read was a very conscious decision: if you're familiar with the Modbus RTU spec, you already know that the end of a Modbus packet is signaled by a gap of 3.5 BIT periods.  You don't know the packet length ahead of time, there's no end-of-frame byte.  And to put it in perspective, 3.5 bit periods at 19.2Kbaud is 156 microseconds (!!).  

My first approach was to use `serial.inter_byte_timeout` to detect end-of-packet, but that doesn't work since its minimum value is 100 milliseconds (and anything less than that is treated as zero).  I  also groveled over the sources for `serial.threaded` and write a number of sketches using `serial.threaded` and variants, but my main takeaway is that by the time you do a context switch, you've already lost the game.  

So ultimately I chose a single threaded approach.  Yes, this approach ties up the GIL while waiting for a packet. But the mitigating factors include:

- Mine is a command line app, so there are no other events pending while this is going on.
- The Modbus spec is a strict master/slave protocol: after sending a request, the Master isn't *allowed* to do anything else until it gets a response from the slave (or a timeout)
-  The timeouts are small.  As I mentioned, the end-of-packet gap is measured in microseconds, a typical request/response timeout is a tenth of a second.

Thoughts?

**Comment by rdpoor** [comment]
@zsquareplusc 

Now that you mention it, I see an improvement to my code (not shown in the example above): Start with a single byte read (blocking) with a timeout.  If it returns a byte, I can enter the CPU intensive loop shown above.  If I get a timeout before getting the first byte, then it means the slave wasn't responding.  

This approach also reduces the expectations made on the OS about buffering bytes before calling a non-blocking read.

I'll try that and if I don't see any missed packets, I'll close this issue.

**Comment by rdpoor** [comment]
As presaged, cannot repeat the symptoms after making the above change.  Closing...

**Comment by zsquareplusc** [comment]
according to http://www.modbus.org/docs/Modbus_over_serial_line_V1.pdf (chapter 2.5.1.1) it's 3.5 character times not bit times, which means it should work to separate packets using `inter_byte_timeout`.

Note that it may not be possible to combine the regular timeout with `inter_byte_timeout` (though it may work on POSIX as the regular timeout is done using select and `inter_byte_timeout` using the serial driver settings).

**Comment by rdpoor** [comment]
> it's 3.5 character times not bit times

Doh!  What's a factor of 10 among friends... ;)

Anyway, the technique of blocking until the first char arrives (with normal timeout in effect), then "reading like heck" with a non-blocking read a short sleep until no new chars arrive appears to be very reliable.  And it has a good chance of working cross-platform (I'll know in a day or two.)

For posterity, here's what I've implemented, but I'd be delighted to learn how I can improve it by taking better advantage of pyserial's API:

    # Normally, you'd want to set up a separate thread for asynchronous reads,
    # but given the nature of master / slave responses, the foreground task
    # can't do much besides wait for a reply from the instrument, so we keep
    # it simple and single-threaded.
    #
    def read_response(self):
        '''
        Read Modbus response, where end-of-packet is indicated by a 
        gap in received bytes.
        '''
        response_packet = bytearray()
        instrument_timeout_at = time.perf_counter() + self._timeout
        in_packet = False

        # Step 1: Try to read one byte (synchronously).  If it times out, that
        # just means the instrument isn't responding.  If we get a byte, we can
        # enter the "fast" read cycle.
        self._serial.timeout = self._timeout
        data = self._serial.read(1)
        if len(data) == 0:
            return response_packet
        response_packet.extend(data)

        # Step 2: got the first byte.  Read the rest of the packet using async
        # reads with short sleeps to detect any gap (signifying end-of-packet).
        self._serial.timeout = 0
        while (True):
            # perform async reads
            data = self._serial.read(256)

            if len(data) > 0:
                # one or more bytes have arrived
                response_packet.extend(data)
                in_packet = True
                time.sleep(self._inter_packet_timeout)  # short sleep

            elif len(response_packet) > 256:
                # interface is spewing data.  make it stop!  :)
                break
            
            else:
                # actively collecting bytes, but none arrived since last tic
                break

        return response_packet
            
        if self._debugging: self.debug_print(debug_str)
        return response_packet
