### ISSUE TITLE
Data Corruption or Miss-Parsed Data Due To Unknown Issue

### ISSUE THREAD

**Issue by knockerclot0715** [pyserial/pyserial#375]
Intro: I'm trying to read serial data out from my PM2.5 sensor through Python 3.7 and which ever the newest version of PySerial that it is currently available.

My Source Code:
`import serial`
`while True:`
`Serial = serial.Serial('COM3', 9600, timeout=1)`
`print(Serial.readline())`
`Serial.close()`

Expected Outcome:
`
b'\xaa\xc0\xc2\x00\x16\x01\xd2\xff\xaa\xab'
`

Actual Outcome:
`
b'\xaa\xc0\xc2\x00\x16\x01\xd2\xff\xaa\xab'
b'\xaa\xc0\xc2\x00\x19\x01\xd2\xff\xad\xab'
b'\xaa\xc0\xc2\x00\x19\x01\xd2\xff\xad\xab\xaa\xc0\xc1\x00\x17\x01\xd2\xff\xaa\xab'
b'\xaa\xc0\xc1\x00\x15\x01\xd2\xff\xa8\xab\xaa\xc0\xc1\x00\x14\x01\xd2\xff\xa7\xab'
b'\xaa\xc0\xc0\x00\x14\x01\xd2\xff\xa6\xab\xaa\xc0\xc0\x00\x15\x01\xd2\xff\xa7\xab'
b'\xaa\xc0\xc0\x00\x19\x01\xd2\xff\xab\xab\xaa\xc0\xc0\x00\x1e\x01\xd2\xff\xb0\xab'
b'\xaa\xc0\xc1\x00#\x01\xd2\xff\xb6\xab\xaa\xc0\xc2\x00$\x01\xd2\xff\xb8\xab'
b'\xaa\xc0\xc3\x00#\x01\xd2\xff\xb8\xab\xaa\xc0\xc3\x00 \x01\xd2\xff\xb5\xab'
b'\xaa\xc0\xc3\x00\x1f\x01\xd2\xff\xb4\xab\xaa\xc0\xc3\x00 \x01\xd2\xff\xb5\xab'
b"\xaa\xc0\xc4\x00$\x01\xd2\xff\xba\xab\xaa\xc0\xc5\x00'\x01\xd2\xff\xbe\xab"
b'\xaa\xc0\xc6\x00-\x01\xd2\xff\xc5\xab\xaa\xc0\xc6\x00/\x01\xd2\xff\xc7\xab'
b'\xaa\xc0\xc8\x003\x01\xd2\xff\xcd\xab\xaa\xc0\xc8\x004\x01\xd2\xff\xce\xab'
b'\xaa\xc0\xc8\x003\x01\xd2\xff\xcd\xab\xaa\xc0\xc7\x000\x01\xd2\xff\xc9\xab'
b'\xaa\xc0\xc6\x00+\x01\xd2\xff\xc3\xab\xaa\xc0\xc6\x00)\x01\xd2\xff\xc1\xab'
b"\xaa\xc0\xc6\x00'\x01\xd2\xff\xbf\xab\xaa\xc0\xc5\x00'\x01\xd2\xff\xbe\xab"
b'\xaa\xc0\xc4\x00#\x01\xd2\xff\xb9\xab\xaa\xc0\xc2\x00!\x01\xd2\xff\xb5\xab'
b'\xaa\xc0\xc0\x00\x1f\x01\xd2\xff\xb1\xab\xaa\xc0\xc1\x00!\x01\xd2\xff\xb4\xab'
`

Notice that starting from line 7 of output, it starts to output symbols such as '!', '#' or '$'. This shouldn't be happening as I would need to convert this data from hexadecimal into deanery values. I have made sure that the correct baud rate is entered: 9600, and the correct port name: 'COM3'. I don't see anything wrong with my code, is it possible that someone help me out here a little bit?

I can provide more technical documentation in regards to the PM2.5 sensor but unfortunately the documentation is in Chinese, I can however translate it if needed. Thanks

PS: Markdown isn't working for me for some reason, so I've attached a screenshot of my source code and the output.

![Source Code](https://user-images.githubusercontent.com/19660509/43874470-a252b5c0-9bbe-11e8-919d-b1a38cb3a064.PNG)
![Output](https://user-images.githubusercontent.com/19660509/43874472-a30e8b38-9bbe-11e8-8021-6f7a410d5a98.PNG)

**Comment by lovechang1986** [comment]
Upload the doc , maybe I can help you

**Comment by lovechang1986** [comment]
Based the doc I can't find the errors!
But two advices:
1 . Do not open and close the serial port frequently， you can choose the in_waiting to wait the data from monitor.
See=serial.serial(m…)
While true:
    Data = see.read (see.in_waiting)

See.close()
2…. decode the bytes or tohex

**Comment by knockerclot0715** [comment]
@lovechang1986 Thanks for your effort mate!

**Comment by zsquareplusc** [comment]
I do not think that there is an error here. The code prints the `repr()` of the packet, which contains mostly unprintable characters so they are output with `\xNN`, but if the bytes happen to represent printable characters it will use that, so e.g. `#` is the same as `\x23`.

The output would probably be easier to read with proper hex encoding using `binascii.hexlify()`.

And as @lovechang1986 suggests, you do not need to open and close the port each time in the loop. In the worst case, the port is opened in the middle of a byte stream and then it might lock onto the wrong bit and receive garbage, at least for the first few bytes. Synchronization is guaranteed again when the line is more than 10 bits idle.
