### ISSUE TITLE
serial.VERSION missing!!!

### ISSUE THREAD

**Issue by prrvchr** [pyserial/pyserial#38]
Hi all,

I don't know if it come from my setup but serial.VERSION is missing... (on 3.0b1 release)

**Comment by zsquareplusc** [comment]
Are you sure that you do not have a mix up of two versions, maybe installed in two different locations?

Happens e.g. on Linux where a packaged version (e.g. `python-serial` on Debian/Ubuntu) is installed at a different place than one with `setup.py`. And some distros have packaged older versions where `VERSION` was not yet added.

**Comment by prrvchr** [comment]
Hi,
My setup is just a copy of .tar file with proper import (I hopes), like you can see on this link:
https://github.com/prrvchr/USBTerminal/tree/master/USB/serial
It works fine with 3.0a0 but not work with 3.0b1 (not yet pushed 3.0b1 on USBTerminal...)

**Comment by prrvchr** [comment]
Ok Comming from my setup...
Sorry.
