### ISSUE TITLE
serial has no attribute SerialBase

### ISSUE THREAD

**Issue by chenzeshu** [pyserial/pyserial#383]
hi guys!

when I used `pyinstaller`  to pack a simple `test.py` which imported `serial`,  it throwed out an error `serial has no attribute 'SerialBase'`

- my environment
```
windows 10
python version 3.6.6
pyserial version 3.2.1
pyinstaller version 3.4
```

- code
```
# test.py
import serial
from serial import Serial

def search_com():
    ser = Serial()
    i = 1  
    error_num = 0 　

    while i < 10:
        name = 'COM' + str(i)
        ser.open
        try:
            ser.is_open
            ser = Serial(name)
            ser.baudrate = 9600
            self.com = name
            print(name)
        except serial.serialutil.SerialException:
            error_num += 1
        i += 1

serch_com()
```

- error:
`serial has no attribute 'SerialBase'`

- my tracking

under the error direction, I went to  line 475 of `serialwin32.py`
```
@SerialBase.exclusive.setter
def exclusive(self, exclusive):
    """Change the exclusive access setting."""
    if exclusive is not None and not exclusive:
        raise ValueError('win32 only supports exclusive access (not: {})'.format(exclusive))
    else:
        serial.SerialBase.exclusive.__set__(self, exclusive)
```  
and the error pointed out `serial.SerialBase` of the last line  is wrong(`serial has no attribute 'SerialBase'`)

- my solution:
uninstall 3.2.1 and install 3.1.1,  then it worked

- question:
why 3.2.1 cannot work with `pyinstaller`?

**Comment by kevindawson** [comment]
Why did you not use the current version?
 * pyserial 3.4 (Jul 23, 2017)
instead of 
 * pyserial 3.2.1 (Oct 14, 2016)

Do you think it would be a good idea to try with the current release, and share your experience :)

**Comment by kevindawson** [comment]
@chenzeshu I am very pleased to here that you are now a member of the happy bunny club ;)

###### Please Close this issue
