### ISSUE TITLE
Miniterm: send data on "Enter"

### ISSUE THREAD

**Issue by ivankravets** [pyserial/pyserial#388]
Firstly, thank you so much for a great tool! Our users use it in pair with @PlatformIO.
They ask very often how to send a bulk of data on "Enter". It's very important for embedded applications. Does miniterm have this functionality or, maybe, API?

Currently, miniterm sends/writes each byte when typing.

Thanks!

**Comment by andyandroid** [comment]
Hi, I add a function sendcmd() to support a bulk of data, please help to check. I am new to github, I am not sure it is standard process. Hope it will help you.
[miniterm](https://github.com/andyandroid/pyserial/blob/master/serial/tools/miniterm.py)

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/commit/605cd36e2783733d57e4ad2a29b17c6f67806a2e

**Comment by ChillarAnand** [comment]
Any plans on adding this feature to miniterm? It would also be helpful it a timestamp is added to the messages.

**Comment by ivankravets** [comment]
@ChillarAnand we resolved that with extra filters https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html#filters

**Comment by ChillarAnand** [comment]
Thanks, @ivankravets `send_on_enter` & `time` filters are useful. 

I ended up writing [a simple client using pyserial asyncio](https://gist.github.com/ChillarAnand/a7be6adeb84a63d48e8dda27aab7ac94) to have consistent format for sent/received messages.

**Comment by zsquareplusc** [comment]
i'd like to not add features like sending on enter or similar things to `miniterm`, but maybe there should be a non-"mini" terminal in pySerial or a separate package (that would be more flexible and allow for more frequent updates). miniterm itself should stay simple enough so that one can test reliably and not depend on too many options that could go wrong.
