### ISSUE TITLE
Is send_break duration in seconds?

### ISSUE THREAD

**Issue by ericksonla** [pyserial/pyserial#397]
My guess is that the duration parameter for send_break is in seconds. Can you confirm or correct please, and it would be great if the docs were updated.

**Comment by jdpatt** [comment]
It's using [time.sleep()](https://docs.python.org/3/library/time.html#time.sleep) which is in seconds.

```
def send_break(self, duration=0.25):
        """\
        Send break condition. Timed, returns to idle state after given
        duration.
        """
        if not self.is_open:
            raise portNotOpenError
        self.break_condition = True
        time.sleep(duration)
        self.break_condition = False
```

**Comment by zsquareplusc** [comment]
Thanks, updated docs :-)
