### ISSUE TITLE
how to open the port with serial.Serial use python3?? 

### ISSUE THREAD

**Issue by LFDwater** [pyserial/pyserial#398]
i  have try:
import serial
ser = serial.Serial("/dev/ttyUSB0",230400)

but error:
AttributeError: module 'serial' has no attribute 'Serial'

and i can make sure not exist file named serial.py which writed by myself

now, i don't know how to do  ~0.0~

**Comment by scshepard** [comment]
Hi,
What the name of the actual device? After plugging in the serial port, try:
# dmesg | grep TTY

Or
# dmesg | tail

Check with:
# ls -l /dev/*TTY*

or
# ls -l /dev/*tty*

Steve
________________________________

**Comment by LFDwater** [comment]
actual device is /dev/ttyUSB0 
i think error is no attribute "Serial" in python3
if use python2
ser = serial.Serial("/dev/ttyUSB0",230400)   can work
but python3 error have no attribute "Serial"
so i try:
ser = serial.open("/dev/ttyUSB0","r")   can work in python3
now, my trouble is how to set baud rate（230400）when open the port named /dev/ttyUSB0

**Comment by LFDwater** [comment]
oh, it's my fault,
i install wrong module,sorry
