### ISSUE TITLE
serial_for_url with do_not_open on loop://

### ISSUE THREAD

**Issue by prrvchr** [pyserial/pyserial#40]
Hi all,

I just realise that I cant use serial_for_url on loop:// if I instanciate with do_not_open=True option and configure port and open() later.
The error message is: could not open port loop:// [Errno2] Aucun fichier ou dossier de ce type: 'loop://'
Tested on 3.0a0 and 3.0b1

edit:
init of serial_for_url(None, do_not_open=True)
a try with serial_for_url("loop://", do_not_open=True) work on open() but you cant change port anymore...

**Comment by zsquareplusc** [comment]
changing the port on the fly, by assigning to `.port` is only supported with native `Serial` port objects and not with the ones created by an URL handlers and especially, it's not possible to change the port type on the fly that way (from one of the URL handlers to an other or native).

Instead you have to close the old port an create/open a new one. It is possible to use `.get_settings`/`.apply_settings` to copy the port settings from one to the other.

**Comment by prrvchr** [comment]
More simply:
serial_for_url do not permit to change port type on the fly...
It can be good to put it in the documentation ...
Thanks
