### ISSUE TITLE
loopback does not contain implementation of out_waiting

### ISSUE THREAD

**Issue by OrangyTang** [pyserial/pyserial#408]
Hello,

I was just doing some testing with a loopback serial connection, but this will throw an error on out_waiting :

`ser = serial.serial_for_url('loop://', timeout=1)`
`print (ser.out_waiting)`

`AttributeError: 'Serial' object has no attribute 'out_waiting'`

It looks like this attribute is not implemented in protocol_loop.py. I've only had a quick look, but it looks like out_waiting could be implemented identically to in_waiting (with the only difference being the log string?

serial.VERSION is 3.4

**Comment by zsquareplusc** [comment]
Yeah why not.. Though `out_waiting` is one of those functions that is not supported on all platforms. Also it's a bit strange for the loop device as the input and output buffers are the same one.. Anyway, added with the commit above.
