### ISSUE TITLE
Suggestion: Integration of the FTDI D2XX Driver (or alternatively libftdi)

### ISSUE THREAD

**Issue by jrast** [pyserial/pyserial#41]
This is a proposal to merge in a Serial class which uses the FTDI D2XX driver which has a much better performance (at least on my laptop) compared with the default Virtual COM Port implementation.
### How to integrate:

Something like this would be nice:
1. Check if the d2xx dll or libftdi is available.
2. If the neither is available switch to the currently used classes
3. If the user want's to connect and d2xx is available, check if the comport is also available through d2xx. 
4. If the device is available, use the d2xx class, otherwise the serial class.
### Existing implementations:

There exist different Versions, but the one I worked with is ft232 which works perfectly out of the box on my machine. 
https://github.com/lsgunth/pyft232

**Comment by zsquareplusc** [comment]
I think this should be done as [URL handler](https://pyserial.readthedocs.org/en/latest/url_handlers.html).

This would be easier to handle with (optional) dependencies to other 3rd party modules and avoid any unexpected "magic" behavior in the `Serial` class.

**Comment by jrast** [comment]
OK, I will have a look into this.

But can you give me some hints on how this would be done with a URL handler? I think I don't really understand them...

**Comment by zsquareplusc** [comment]
I see that the library you have referenced already implements a pySerial (<3.0) compatible class (It would require minor changes, renamed methods names etc. to update for 3.0).

An URL handler is identified by the protocol (the `xxx` part in `xxx://...`) and a module with the name `protocol_xxx` is imported (searched in the registered packages in `serial.protocol_handler_packages`. the `protocol_xxx` module itself just implements a `Serial` class will all the functions required by pySerial. Alternatively the module `protocol_xxx` can also provide a function `serial_class_for_url(url)` that returns a `Serial` compatible object.

See `serial/urlhandler/protocol_socket.py` for a simple example of an URL handler.

for the `ft232`library it would basically be a file `protocol_ftdi.py` with the contents `from libftdi import LibFtdi as Serial` (for pySerial <3.0 but for the version here on github, the ft232 would need an update to the latest pySerial API) and it may need a tweak to handle the URL that is assigned to its `.port` attribute.

**Comment by diamondman** [comment]
@jrast Is this still an issue, or can it be closed?

**Comment by jrast** [comment]
I created a serial.Serial compatible wrapper for D2XX and check during the instanciation of the connection if the port is also available through D2XX to select the correct implementation. So this is no longer relevant.
