### ISSUE TITLE
Problem with rfc2217 & ser2net

### ISSUE THREAD

**Issue by berkinet** [pyserial/pyserial#412]
This is most likely a user error. But, if it is, I am at a loss to resolve it.  I am using pyserial/rfc2217 to connect to a server running ser2net v3.5 (on OpenWRT). The ser2net config is exactly as documented in rfc2217.py:
 &#35;- run a server: run ser2net daemon, in /etc/ser2net.conf:
 &#35;    2000:telnet:0:/dev/ttyS0:9600 remctl banner

However, any attempts to connect fail at:
        if self._write_timeout is not None:
            raise NotImplementedError('write_timeout is currently not supported')

If I comment out that test, the connection succeeds. There does not appear to be any option in ser2net to not sent wait_timeout.

Any ideas how to resolve this?

Thanks.

**Comment by berkinet** [comment]
This appears to be the same, or a very similar, issue to #395

**Comment by berkinet** [comment]
FYI this same problem occurs when using the rfc2217 server in the examples,

**Comment by zsquareplusc** [comment]
The problem seems to root in the Python script that set's up up the serial port with a write timeout. It fails before even connecting to the remote server. Try initializing the `Serial` object without `write_timeout` (the default should be `None`).

**Comment by berkinet** [comment]
\#!. Thanks @zsquareplusc 
Ok... I may be going crazy here. But... In serialutils.py just before line 317 I tested for the value of timeout and it is a logical (I.e. not textual) None. And, as reported above, rfc2217.py fails.  

Then in rfc2217 at line 505 where the exception is raised for _write_timeoout, I  added {!r}'.format(self._write_timeout) to the exception message it prints 2.0

Then, as you suggested,  just before line 317 I explicitly set timeout = None, and rfc2217.py works!

So, somehow the value of timeout, and eventually _write_timeout is getting set to 2.0.

I am baffled.

**Comment by berkinet** [comment]
I realized my version of serialutil.py is old. I updated to the current version and have the same issue. The former lone 317 is now at 387

**Comment by berkinet** [comment]
For clarity, I am working on code imbedded in another product. However, to be sure I was not chasing an old bug, I updated serialutil.py and rfc2217.py to the latest versions and the problem remains.

**Comment by zsquareplusc** [comment]
I'd expect that somewhere in your code (or that product) , either `write_timeout` or the old name `writeTimeout` is set. Most likely as keyword parameter when `serial_for_url()` is called.

**Comment by berkinet** [comment]
writeTimeout was the key. I found where it was being set.  Thanks. I will check with the developer and then close this report.

**Comment by berkinet** [comment]
Case closed. Thanks to @zsquareplusc

**Comment by yozik04** [comment]
Same problem with `pyserial-asyncio`. Linked created issue above. Which side needs a fix? `NotImplemented `in current case means it will be implemented some day?
