### ISSUE TITLE
Read does not honor the timeout on Linux

### ISSUE THREAD

**Issue by cdealti** [pyserial/pyserial#42]
Hello,
  Reading from the serial port with a timeout is not reliable on my system:
* Linux Mint Nadia
* Python 2.7.3
* pyserial 2.7 (but also 2.5) installed both with ```pip``` and the latest tar.gz

I have a CDC-ACM dongle that transmits data periodically.

This simple program does not respect the timeout:

```
import serial
import time

ser = serial.Serial(
                    port        = '/dev/ttyACM0',
                    baudrate    = 460800,
                    bytesize    = serial.EIGHTBITS,
                    parity      = serial.PARITY_NONE,
                    stopbits    = serial.STOPBITS_ONE,
                    timeout     = 0.1
                   )

while True:
   length = 1000000

   t0 = time.time()
   print str(len(ser.read(length))) + ' ' + str((time.time() - t0))
```

Running the above I get:

```
123 0.109111070633
246 0.205754995346
123 0.106971025467
369 0.310961008072
123 0.106863975525
369 0.309740066528
246 0.214066982269
```
Data is read but with an higher latency.
Things go worst if the timeout is set to 1s, in which case data is read with higher latencies (>> 1s).

What's going on? For comparison I've tried the following program that mimics what ```pyserial``` should do:

```
import serial
import time
import select

ser = serial.Serial(
                    port        = '/dev/ttyACM0',
                    baudrate    = 460800,
                    bytesize    = serial.EIGHTBITS,
                    parity      = serial.PARITY_NONE,
                    stopbits    = serial.STOPBITS_ONE,
                    timeout     = None, #block forever
                   )

def read(ser, length, timeout):
   n = 0
   b = bytearray()
   ser.timeout = 0 #non-blocking
   while timeout >= 0 and n < length:
       t0 = time.time()
       ready = select.select([ser], [], [], timeout)
       timeout -= (time.time() - t0)
       if len(ready[0]) != 0:
           bb = ser.read(length - n)
           n += len(bb)
           b.extend(bb)
   return b

while True:
   timeout = 0.1 #seconds
   length = 1000000

   t0 = time.time()
   b = read(ser, length, timeout)
   print str(len(b)) + ' ' + str((time.time() - t0))
```

Whose output is:

```
123 0.101263999939
123 0.101146936417
123 0.101223945618
123 0.100612163544
123 0.100650072098
123 0.101171016693
123 0.10132598877
```

As you can see data is consistently read with the specified latency.
Other runs:

timeout=2.0:

```
2460 2.0148499012
2337 2.01164889336
2340 2.01203608513
2337 2.01602220535
2337 2.01417803764
2337 2.01304197311
```

timeout=2.0, length=10:

```
10 0.000165939331055
10 0.000646114349365
10 0.000133991241455
10 9.58442687988e-05
10 0.000693082809448
10 0.000132083892822
10 0.000753879547119
```

**Comment by jrobeson** [comment]
@cdealti : can you replicate it with the 3.0 beta?

**Comment by cdealti** [comment]
I've not tried yet, but looking at the code at https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py, line 469, it looks like that the timeout handling is not correct. If timeout is large enough and the RX throughput is large enough too, like in my use case above, the ```select``` call will always return with fd being ready. If this happens consistently, like in my use case, you will exit the loop only when the number of bytes read is >= the requested size and the timeout will not play the intended role.

**Comment by cdealti** [comment]
OK, done.
Please note that time.time() works fine for me and it appears to use an high resolution timer.
Not sure if it works nicely on other Posix OSs too.

**Comment by zsquareplusc** [comment]
I guess you have found some buggy behavior, that needs to be fixed, but i'd also advice against using timeouts this way.

Timeouts are not guaranteed to be accurate across all the supported OS. I would also not rely on sub second timeouts. I've seen strange things happen on some other popular OS (processes not getting their time), at least back in the days where Floppies where still sold. ... and I still do not trust them ;-)

**Comment by cdealti** [comment]
Yes, I've read the documentation about the resolution of time.time(). It work for me but I cannot test on other Posix platforms

**Comment by zsquareplusc** [comment]
closing as #47 was merged to fix this
