### ISSUE TITLE
Update project URL on PyPI and pythonhosted

### ISSUE THREAD

**Issue by zwgraham** [pyserial/pyserial#43]
Both the https://pythonhosted.org/pyserial/ and https://pypi.python.org/pypi/pyserial web pages list the old Sourceforge URL as the homepage for pyserial. This should probably be updated.

**Comment by jrobeson** [comment]
ping @zsquareplusc : this is prety important being that 3.0 is tagged.

**Comment by zsquareplusc** [comment]
Both sites have been updated to v3.0
