### ISSUE TITLE
serial.write return value inconsistent

### ISSUE THREAD

**Issue by anotherKeith** [pyserial/pyserial#435]
Documentation bug
Running Python 2.7.14 32-bit on a Win-7 platform.
Pyserial version 3.4

Sending a byte to serial.write results in the byte being returned.
Sending a string results in the number of bytes sent being returned.

```
import serial
import io
import time

ser = serial.Serial(port="COM9", \
      baudrate=9600, \
      parity=serial.PARITY_NONE, \
      stopbits=serial.STOPBITS_ONE, \
      bytesize=serial.EIGHTBITS)

time.sleep(0.1)
ser.flushOutput()
ser.flushInput()

cmdToSend = bytearray.fromhex("0D 0E 0A 0D 0B 0E 0E 0F")
arrLen = len(cmdToSend)
idx = 1
print(40*"=")
for cmd_byte in bytearray(cmdToSend):
    print("index %d of %d = 0x%02x" % (idx, arrLen, cmd_byte))
    idx += 1
    rtn = ser.write(cmd_byte)
    if (rtn != 1):
        print("Serial.write returned:  0x%02X" % rtn)
    rtn = 0
print(40*"=")
rtn = ser.write('I like eat deadbeef!'.encode('utf-8'))
if (rtn != 1):
    print("Serial.write returned: %d" % rtn)
```

Output:
```
========================================
index 1 of 8 = 0x0d
Serial.write returned: 0x0D
index 2 of 8 = 0x0e
Serial.write returned: 0x0E
index 3 of 8 = 0x0a
Serial.write returned: 0x0A
index 4 of 8 = 0x0d
Serial.write returned: 0x0D
index 5 of 8 = 0x0b
Serial.write returned: 0x0B
index 6 of 8 = 0x0e
Serial.write returned: 0x0E
index 7 of 8 = 0x0e
Serial.write returned: 0x0E
index 8 of 8 = 0x0f
Serial.write returned: 0x0F
========================================
Serial.write returned: 20

```

**Comment by zsquareplusc** [comment]
It returns the size in both cases... but the first part of the code passes an integer to `write()`, not a byte string. pySerial makes a call to `bytearray()` (for non `bytes`/`bytearray`/`memoryview` types) which then produces an sequence of that many null bytes.

The tricky part is that Python returns integers for a `for` loop over `bytes` (py 3) and `bytearray` (py 2&3). pySerial has a function `iterbytes` to iterate as single byte strings if you want to avoid that. See also [PEP-0467](https://www.python.org/dev/peps/pep-0467/).

You could argue that it should raise a `TypeError` in that case, however the intention of a call to `bytes()` for unknown types was, that user defined classes that behave like `bytes` can also be sent (e.g. if they implement `__bytes__`).

**Comment by anotherKeith** [comment]
@zsquareplusc : Thanks for the clarification.

This simple statement:
> pySerial makes a call to bytearray() (for non bytes/bytearray/memoryview types) which then produces an sequence of that many null bytes.

...would have saved quite a bit of time if it was included in the API documentation for the serial.write function.
