### ISSUE TITLE
Serial not defined

### ISSUE THREAD

**Issue by andrfgs** [pyserial/pyserial#436]
Cannot use the library. The following program wields an error:

```
import serial

ser = Serial('/dev/ttyS0', 9600, timeout = 1.0, rtscts = 0)
```

This wields the error: 

> NameError: name 'Serial' is not defined

I have already installed the module using pip and pip detects it. Since I'm not using any other environments this should work. So it seems to be a bug.

Using Python3 but Python2 seems to have the same problem

EDIT: the .whl seems to be installed in the directory `/home/pi/.local/lib/python3.5/site-packages/serial`. This is the pyserial library. I double checked and uninstalled the `serial` library (as its usually confused with this) and its not listed through `pip list`. It is clearly pyserial's folder.

**Comment by duanjj0929** [comment]
Please try using **serial.Serial** instead of **Serial**.

**Comment by andrfgs** [comment]
That solves the problem. Either `serial.Serial` (what you suggest) or `from serial import Serial` seem to fix the problem.

By the way, the first time I tried this, it didn't work. But after a pip reinstall, and trying again these modifications it now works.

Any idea why this may happen?

**Comment by ashrafulkhn** [comment]
I am getting the same error.
I am using windows 11.

`from serial import Serial
ModuleNotFoundError: No module named 'serial'`
