### ISSUE TITLE
case else is not aligned with if

### ISSUE THREAD

**Issue by edbird** [pyserial/pyserial#442]
https://github.com/pyserial/pyserial/blob/2d879b2428dacf30d5c8ba077626236b06c7d77f/serial/urlhandler/protocol_loop.py#L156

Line 156 `else:` not aligned with `if`

**Comment by ksunden** [comment]
That's because the else is not for an `if`, but for the `try`, it is code that is only run if _no_ `queue.Empty` exception occurs in the `try` block (as opposed to the `except` block which is only run if the exception occurs, or the `finally` block which is always run)

**Comment by edbird** [comment]
Ok! My apologies - I just saw it this morning and flagged it without giving it too much attention
