### ISSUE TITLE
Example wxSerialConfigDialog.py: Call to deprecated WX item

### ISSUE THREAD

**Issue by dirttraxx** [pyserial/pyserial#444]
`C:\Users\x\Desktop\wxSerialConfigDialog.py:205: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:'EvtHandler.Bind' instead.
  wx.EVT_BUTTON(self, self.button_ok.GetId(), self.OnOK)
C:\Users\x\Desktop\wxSerialConfigDialog.py:206: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:'EvtHandler.Bind' instead.
  wx.EVT_BUTTON(self, self.button_cancel.GetId(), self.OnCancel)`

Using Python 2.7.16 and WX 4.0.5
Fix is change lines 205-206 to
`self.Bind(wx.EVT_BUTTON, self.OnOK,     self.button_ok)`
`self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_cancel)`

**Comment by zsquareplusc** [comment]
Code is updated.
