### ISSUE TITLE
write error with eagain (resource temporarily unavailable)

### ISSUE THREAD

**Issue by trampas** [pyserial/pyserial#45]
I have a program which when I run with threads (on multiple ports at same time) it hangs the python script. Doing an strace it is hanging on the write('AT\r') with error EAGAIN (resource temporarily unavailable).  I removed the threaded call to function and it works but worry it is because of a timing issue rather than treading issue. 

Is this a bug in pyserial? Is there something I can do to work around, not it never timed out! 

Thanks

  def TestForATPort(self,comport):
        try:
            port=serial.Serial(comport,115200,timeout=5,writeTimeout=3)
            
            self.logger.info("trying port %s %s" % (comport, str(port)))
            if port.isOpen():
                try:
                    fcntl.flock(port.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
                except IOError:
                    print('Port %s is busy' % comport)
                    port.close()
                    return False
            else:
                return False
            port.flushInput()
            port.flushOutput()
            port.write('AT\r')         
            s=""
            found=False
            time.sleep(1) #dleay ot have response
            t=time.time()
            while(time.time()-t)<3:
                if (port.inWaiting()>0):
                    try:
                        c=port.read()
                        s=s+c
                        if (c=='\r'):
                            if "\nOK\r" in s:
                                found= True
                                print("found port %s" % comport)
                                break;
                            s=""
                    except Exception as e:
                        self.logger.error("exception %s" % str(e))
                        pass   
            fcntl.flock(port.fileno(), fcntl.LOCK_UN)   
            port.close()
            return found
        except Exception as e:        
            exc_type, exc_obj, exc_tb = sys.exc_info()
            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
            s=str(exc_type) + " " + fname +" "+ str(exc_tb.tb_lineno)
            self.logger.error(s)
            return False
        return False

**Comment by jrobeson** [comment]
you didn't say which version you used. If you haven't tried the 3.0 beta , maybe you wanna give that a shot.

**Comment by trampas** [comment]
I am using 2.7

**Comment by trampas** [comment]
The release notes from 2.7 to 3.0 does not indicate anything was changed that might be related to this issue.

**Comment by trampas** [comment]
I think I see the problem if the os.write() function gets the EAGAIN exception then the write code will ignore the time out and retry the write.  I am not sure this is the desired behavior. Specifically I would assume the timeout should happen and let the higher level application make the decision.  Specifically if the EAGAIN error occurs then timeout should be checked before retrying the write.   


 def write(self, data):
        """Output the given string over the serial port."""
        if not self._isOpen: raise portNotOpenError
        d = to_bytes(data)
        tx_len = len(d)
        if self._writeTimeout is not None and self._writeTimeout > 0:
            timeout = time.time() + self._writeTimeout
        else:
            timeout = None
        while tx_len > 0:
            try:
                n = os.write(self.fd, d)
                if timeout:
                    # when timeout is set, use select to wait for being ready
                    # with the time left as timeout
                    timeleft = timeout - time.time()
                    if timeleft < 0:
                        raise writeTimeoutError
                    _, ready, _ = select.select([], [self.fd], [], timeleft)
                    if not ready:
                        raise writeTimeoutError
                else:
                    # wait for write operation
                    _, ready, _ = select.select([], [self.fd], [], None)
                    if not ready:
                        raise SerialException('write failed (select)')
                d = d[n:]
                tx_len -= n
            except OSError, v:
                if v.errno != errno.EAGAIN:
                    raise SerialException('write failed: %s' % (v,))
        return len(data)

**Comment by trampas** [comment]
I think this might fix the problem I am not sure that the try/except is correct for the select.select() function?

<pre><code>
    def write(self, data):
        """Output the given string over the serial port."""
        if not self._isOpen: raise portNotOpenError
        d = to_bytes(data)
        tx_len = len(d)
        if self._writeTimeout is not None and self._writeTimeout > 0:
            timeout = time.time() + self._writeTimeout
        else:
            timeout = None
        while tx_len > 0:
            try:
                n = os.write(self.fd, d)
                d = d[n:]
                tx_len -= n
            except OSError, v:
                if v.errno != errno.EAGAIN:
                    raise SerialException('write failed: %s' % (v,))
            try:  #not sure if we need the try/except for the code below
                if timeout:
                    # when timeout is set, use select to wait for being ready
                    # with the time left as timeout
                    timeleft = timeout - time.time()
                    if timeleft < 0:
                        raise writeTimeoutError
                    _, ready, _ = select.select([], [self.fd], [], timeleft)
                    if not ready:
                        raise writeTimeoutError
                else:
                    # wait for write operation
                    _, ready, _ = select.select([], [self.fd], [], None)
                    if not ready:
                        raise SerialException('write failed (select)')              
            except OSError, v:
                raise SerialException('write timeout code failure: %s' % (v,)
        return len(data)
</code></pre>
