### ISSUE TITLE
[Windows] Badly detected Serial Numbers for certain devices

### ISSUE THREAD

**Issue by hmaarrfk** [pyserial/pyserial#454]
Windows sometimes fails to correctly detect the serial number for certain FTDI devices I have.

Originally I thought it was related to an other issue:
https://github.com/pyserial/pyserial/issues/283#issuecomment-522336777

But it seems unrelated. 

See https://github.com/pyserial/pyserial/issues/283#issuecomment-522773875 for results of 
```
udevadm info --attribute-walk /dev/ttyUSB0 > ttyUSB0_attribute_walk.txt
```

As requested by @ryan-summers Here is a screenshot of a the device I **think** it is. Note that I have many of these serial devices (Thorlabs brand motors), and this bug only occurs on some of them. At first glance, they all look the same. I'll have to try:

1. Deleting all entries.
2. Attaching the problematic motor.
3. Taking screenshots again.

<details> <summary> Sample, probably useless screenshot</summary>
![image](https://user-images.githubusercontent.com/90008/63358434-05d66680-c339-11e9-9b1a-391608591d30.png)
</details>

**Comment by hmaarrfk** [comment]
Maybe it is reporting the first "6" as the serial number, when it should be probing somewhere deeper to get a number that starts with `27XXXXXX`

**Comment by ryan-summers** [comment]
@hmaarrfk Looking at the list_ports_windows.py source code indicates that FTDI devices handle serial numbers slightly differently than other USB devices. Can you add in a print(szHardwareID_sr) to serial/tools/list_ports_windows.py (at line 320 works well) and run the updated script? This should print out the (device identification string)[https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-identification-strings] which we can use to figure out why the wrong serial number is reported.

**Comment by hmaarrfk** [comment]
Here is a consistent view of the screenshot and the reported information from pyserial (on master)
```
(pyserial_dev) C:\Users\mark\git\pyserial>python -m serial.tools.list_ports -v
FTDIBUS\VID_0403+PID_FAF0+5&3095C79&0&2\0000
COM17
    desc: APT USB Device Serial Port (COM17)
    hwid: USB VID:PID=0403:FAF0 SER=5
1 ports found
```
![image](https://user-images.githubusercontent.com/90008/63374799-8b1d4380-c358-11e9-992d-b685f5238505.png)

Its serial number should be 27504197, (or 27504197A), hex value is '0x1a3ae45'

**Comment by hmaarrfk** [comment]
The FTDI driver is weird these days. They now make you select an option `Enable VCP` in the `Device Manager` so that you can see the COM Port. I had to tick that box.

I took a screenshot of the registry location listed 
https://www.ftdichip.com/Support/Knowledgebase/index.html?wherecanifindport.htm

![image](https://user-images.githubusercontent.com/90008/63375950-b6089700-c35a-11e9-8201-61173e4bea89.png)

**Comment by hmaarrfk** [comment]
The really weird thing is, that it did work at one time in windows since I Have code that says:
```
    if serial_number is not None:
        serial_number = str(serial_number)
        if is_windows:
            # windows for some reason like to add 'A' at the end of the serial
            # numbers
            serial_number += 'A'
```
adding an `A` to the expected serial number string.

**Comment by hmaarrfk** [comment]
This is a dumb driver issue. Sorry for wasting your time.

I looked at the date of the driver that was previous installed, and noticed that it was from 2015.
I uninstalled and reinstalled (Thorlabs) software, and their driver became updated to some 2017 version (I probably had two versions of thorlabs software that conflicted).

With some combination (of their Kenisis) software, I managed to get the driver to update to some 2017 version
![image](https://user-images.githubusercontent.com/90008/63377350-f6b5df80-c35d-11e9-8dc9-92185d35530e.png)

This ends up creating a new entry in the registry, taht contains the expected format of the serial number
![image](https://user-images.githubusercontent.com/90008/63377509-45fc1000-c35e-11e9-94bb-325028cc6802.png)

```
>python -m serial.tools.list_ports -v
FTDIBUS\VID_0403+PID_FAF0+27504197A\0000
COM18
    desc: APT USB Device Serial Port (COM18)
    hwid: USB VID:PID=0403:FAF0 SER=27504197A
1 ports found
```
this ends up adding the usual `A` at the end of the device, but that seems to be related to the fact that it is a dual port chip, and that the first port corresponds to `A` while the second corresponds to `B`. Apparently linux just drops `A`.

I forget where I read this explanation, but it was on this libraries's issues.

Thank you for your help troubleshooting.

**Comment by hmaarrfk** [comment]
This seems to have been reported to FTDI in a 2016 release

```
2.12.16 (March 16, 2016)
WHQL certified release.

Release Fixes

•	Fixed problem with serial number string returned from D2XX API functions when serial number bit is not set in EEPROM.

```

**Comment by hmaarrfk** [comment]
Is there a way to detect the version of the driver used from pyserial?

**Comment by hmaarrfk** [comment]
For reference, (happeend to still have an old window open), this is the version of the driver that was giving problems:

![image](https://user-images.githubusercontent.com/90008/63380615-ed7c4100-c364-11e9-810f-a167df0cc159.png)

**Comment by zsquareplusc** [comment]
no, there is no information about driver version available via pySerial. `list_ports` just extracts the minimum information needed, though the Windows API used there could also retrieve this information. But it's probably more confusing than helpful if it were included by default, as well as not cross platform as other OS handle drivers differently.

**Comment by hmaarrfk** [comment]
Right. I'm just wondering how I can give a more targeted warning message when I detect such an old driver. Cross is compatibility is really annoying, but for our use case, it might be worth adding to the TODO list.

If you know what function I should look into I would be great ful for the pointer

**Comment by ryan-summers** [comment]
@hmaarrfk Most of the windows pyserial code executes from prototypes provided in the Windows API files `setupapi.h` and `cfgmgr32.h` - here is one such function: https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdiclassguidsfromnamea - there may be an API hidden inside of there that allows you to access the installed driver from the device node, but this is getting much deeper into windows serial drivers than most of Pyserial typically does.
