### ISSUE TITLE
serialjava.py can't handle non-contiguous COM port numbers

### ISSUE THREAD

**Issue by DMats** [pyserial/pyserial#46]
I have COM1, COM2, COM3, COM200 and tried to open COM200 using the command:
```
ser = serial.Serial( port=199, baudrate=1500000, timeout=30 )
```
I received an index error 
```
    ser = serial.Serial( port=199, baudrate=1500000, timeout=30 )
  File "C:\jython2.7.0\Lib\site-packages\serial\serialutil.py", line 269, in __init__
    self.port     = port
  File "C:\jython2.7.0\Lib\site-packages\serial\serialutil.py", line 317, in setPort
    self.portstr = self.makeDeviceName(port)
  File "C:\jython2.7.0\Lib\site-packages\serial\serialjava.py", line 143, in makeDeviceName
    return device(port)
  File "C:\jython2.7.0\Lib\site-packages\serial\serialjava.py", line 49, in device
    return ports[portnumber].getName()
IndexError: index out of range: 199
```

I believe the error is on line 48 of serialjava.py.  Change ports.append(el) to something else.  

EDIT:  I'm using pyserial 2.7

**Comment by zsquareplusc** [comment]
I'd try to open the port by name, not by number. The open by number feature is not supported anymore by pySerial 3.x as it is not easy to get a useful numbering.

In pySerial 2.x the port number is just an index to a list of more or less arbitrary choice of ports. In your example, COM200 would most likely be at index 3.
