### ISSUE TITLE
Travis-CI Check Failing (404 Not Found Error)

### ISSUE THREAD

**Issue by jacobian91** [pyserial/pyserial#476]
The latest commit 3a6ae5a and a few of the latest pull requests show the Travis-CI checks failing on Python 3.2 & 3.3 for the same reason, **404 Not Found**.

```
3.2 is not installed; attempting download

Worker information

Build system information

Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.2.tar.bz2
$ curl -sSf -o python-3.2.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
Unable to download 3.2 archive. The archive may not exist. Please consider a different version.
```

**Comment by ksunden** [comment]
Looks like Travis removed old pythons.... We now use Azure pipelines anyway, AFAIK the Travis ones were never disabled but are not heeded by any of the devs.

**Comment by WisdomPill** [comment]
I am making a pull request for dropping python 3.2 and 3.3, even 3.4 might be dropped but in my opinion only if necessary. I hope to get it merged and get the project active again. I already created an issue about that #499

**Comment by WisdomPill** [comment]
I guess this can be closed now please @bufferoverflow or @zsquareplusc close this
