### ISSUE TITLE
Poor RS485Settings exception messages

### ISSUE THREAD

**Issue by astrelsky** [pyserial/pyserial#481]
These exception messages should state that they are not supported on the platform instead of saying the value is unsupported. I had to dig up the source to figure out why any float value I entered for delay_before_tx was invalid.

https://github.com/pyserial/pyserial/blob/3a6ae5a630589a29af8d8bd45616d7aadb2fb3db/serial/serialwin32.py#L183-L204

**Comment by zsquareplusc** [comment]
OK, why not. Added accepted value to the error message.
