### ISSUE TITLE
Readline() does not timeout as long as data keeps coming in

### ISSUE THREAD

**Issue by rgov** [pyserial/pyserial#487]
With this code sample, the second `readline()` call seems to wait indefinitely, despite the timeout setting.

A few curious things:

1. The bug does not reproduce if the timeout is set to 1 or 2 seconds.
2. The bug *does* reproduce if the timeout is set to 3 or more seconds.
3. The bug does not reproduce if the `time.sleep()` calls are removed.
4. The bug does not reproduce if the `time.sleep()` calls are reduced to 1 second each.
5. The bug does not reproduce if the baud rate is not changed. 

```python
import time
from serial import Serial

s = Serial('/dev/cu.usbserial-AH05LL5O', 115200, timeout=3)
time.sleep(1.5)

print('reading')
print(s.readline())

print('increasing baudrate')
s.baudrate = 250000
time.sleep(1.5)

print('reading')
print(s.readline())

print('done')
```

**Comment by rgov** [comment]
Backtrace is:

```
  File "/usr/local/lib/python3.7/site-packages/serial/serialposix.py", line 483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
```

https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py#L540

I'm running version 3.4 but I see that the code has changed. I'll try with a newer version.

**Comment by rgov** [comment]
The `readline()` implementation provided by the `io.RawIOBase` base class calls `serialposix.Serial.read()` repeatedly. Each time, the timeout is passed to `select()`, which immediately returns that the file is ready to be read. But, because the baud rate is too high, we aren't getting a `\n` character, so it loops forever accumulating data.

**Comment by bilalh96** [comment]
can you please update the current workable settings that you found, also the timeout option here as set to 3 , does that mean the readline will read until 3 sec and then the receiving buffer will be closed?

**Comment by rgov** [comment]
There are no workable settings. The timeout only applies to read() and does not apply to readline().

**Comment by bilalh96** [comment]
What's the difference between these two? can you elaborate please

**Comment by rgov** [comment]
In pyserial, `read(n)` reads exactly *n* bytes from the serial device. If a timeout is set, it will read until *n* bytes have been read *or* the timeout is reached, and then return as many bytes as it could read before the timeout.

`readline()` reads a variable number of bytes until a newline is encountered. Internally, it does this by calling `read()` repeatedly. The timeout parameter applies individually to each `read()` call, but not to the overall `readline()` -- it will keep trying to `read()` until it gets a newline, no matter how long it takes.

**Comment by bilalh96** [comment]
thanks a bunch for a detailed explanation. Actually, I want to read serial data from a sensor but like every 10 seconds from it so you can imagine how much it will be for a day and so on. so I am a bit confused whether I should use read or readline. also the sensor is a cheap one so its documentation has got no details like byte size etc. it has only got commands like start , stop , read, etc. Would you me guide a little bit on this , thanks .

**Comment by rgov** [comment]
Your question would be better answered on a site like [StackOverflow](https://stackoverflow.com) than here -- try to avoid jumping onto an existing GitHub issues with a question, because it's not really a conversation forum.

The answer depends entirely on the format of the sensor's output. If it is outputting lines of text, perhaps of different lengths, with each line ending with a newline character, use `readline()`. If it is outputting a message that is always the same number of bytes each time, use `read(n)`.

**Comment by zsquareplusc** [comment]
thanks @rgov for providing the correct explanation for your own question. i'll close the issue.
but this was not the only question about readline, i tried to extend the docs a bit https://pyserial.readthedocs.io/en/latest/shortintro.html#readline

**Comment by ovianao** [comment]
Sorry to jump in here sort of out of turn, but perhaps the confusion lies here, in the documentation:
"Do specify a timeout when opening the serial port otherwise it could block forever if no newline character is received."
.. this implies that if you supply a timeout when opening the serial port, and no newline character is received, then supplying such a timeout would prevent it from blocking forever.  Pehaps this requires re-wording?

**Comment by JJMultiSistemas** [comment]
sinceramente amigo... yo no se programar códigos en lenguajes de
programación, soy un simple aficionado y entusiasta de estas cosas, me
gustaría poder colaborar en cualquier cosa  necesaria
