### ISSUE TITLE
Throw SerialException if can't open port

### ISSUE THREAD

**Issue by Spaghetti-Cat** [pyserial/pyserial#49]
OS: Windows 7 64-bit
Python: v2.7.8
PySerial: v2.7

If I try to open a COM port that doesn't exist on the system, e.g.:

        port = Serial(
            port='COM66', baudrate=500000, bytesize=8,
            parity=serial.PARITY_NONE, stopbits=1, timeout=None)

I get an exception:

```
ERROR:   File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 38, in __init__
ERROR: SerialBase.__init__(self, *args, **kwargs)
ERROR:   File "C:\Python27\lib\site-packages\serial\serialutil.py", line 282, in __init__
ERROR: self.open()
ERROR:   File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 82, in open
ERROR: self._reconfigurePort()
ERROR:   File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 202, in _reconfigurePort
ERROR: raise ValueError("Cannot configure port, some setting was wrong. Original message: %r" % ctypes.WinError())
ERROR: ValueError
ERROR: :
ERROR: Cannot configure port, some setting was wrong. Original message: WindowsError(87, 'The parameter is incorrect.')
```

But shouldn't it throw a SerialException rather than a ValueError? Why a ValueError?

PS: Huge thank you for this great library :)

**Comment by prrvchr** [comment]
Hi,

Documentation say:
SerialException on connection error
ValueError on arg assignment error (out of range)
I think is't a normal behavior

**Comment by Spaghetti-Cat** [comment]
From the documentation:
> SerialException – In case the device can not be found or can not be configured.

That said COM66 is listed on my OS as an available port (even though no device is listed with such a COM port; I think it's some sort of ghost leftover), accordng to `serial.tools.list_ports` so I will try with a completely unrgeistered port like COM200 on Monday, to see if it throws `SerialException`.

**Comment by zsquareplusc** [comment]
Changed it. `ValueError` should be for parameters out of range, but the failure described above is reported by the OS when applying valid parameters, thus `SerialException` is better suited.
