### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Flameeyes** [pyserial/pyserial#493]
Hi folks, is there any chance that a new release can be made? I'd like to depend on the cp2110 support I introduced last year, but right now there's no way for me to express that :(

**Comment by keelung-yang** [comment]
Me too

**Comment by klanmiko** [comment]
yea. Latest release is 2 years behind master

**Comment by harryberlin** [comment]
you can simply copy the serial folder to your project source. may you must append to sys.path for importing

**Comment by timrid** [comment]
There has still been no change. Are there any plans to make a new release in the future?

Of course copying is also possible, but it is not fun to copy the package into every project.

**Comment by zsquareplusc** [comment]
beta release is out, please see #528
