### ISSUE TITLE
miniterm keybind for 's'

### ISSUE THREAD

**Issue by jpkotta** [pyserial/pyserial#497]
The menu keybinding for 's' is both suspend and Space parity.  The way it's implemented you can't set Space parity (I personally don't care about this, but clearly it's a bug).

Also the suspend binding is not listed in the help.

https://github.com/pyserial/pyserial/blob/master/serial/tools/miniterm.py#L540

**Comment by zsquareplusc** [comment]
Yeah this was an oversight, changed suspend to Z. Its mentioned in the docs but not the help. The problem with the help is that it's already over 20 lines long and some operating systems still open terminal windows with a default size of 80x25...
