### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by WisdomPill** [pyserial/pyserial#499]
Dear @bufferoverflow and @zsquareplusc 

I am a long time user of the library, lately I started playing with asyncio and I was curios about pyserial with asyncio, I noticed there is a library (pyserial-asyncio) that depends on pyserial and it is made by the same community but the support is outdated for that library and this one as well. My question is: is this repository active? Does someone plan to keep supporting this amazing library? I would be glad to help and make some pull requests like dropping python 3.2 and 3.3 for the beginning and make pyserial more integrated with asyncio. I see many pull requests without an answer and many things were other people like me would be glad to help with.
Best regards, WisdomPill

**Comment by WisdomPill** [comment]
@bufferoverflow or @zsquareplusc any news? Please let some people help with maintaining this library. It is used by a big part of the python community and it is showcased in many tutorials.

I am open to step in and help, I am interested also in the async version.

Can you please at least say something about the status of the project?

**Comment by changyuheng** [comment]
Hi @WisdomPill, please check out [aioserial](https://github.com/changyuheng/aioserial). It's fully compatible with [pyserial](https://github.com/pyserial/pyserial).

**Comment by jacobian91** [comment]
@bufferoverflow @zsquareplusc, It would be great to see development start again with this. I will second what @WisdomPill said about being a big part of the python community. I personally depend on it for work to talk to various hardware systems in a manufacturing environment.

**Comment by kevindawson** [comment]
hi all, it's a long time since I did #380 
there was no reply then also
@WisdomPill it might be worth considering that the founders are _no more..._
I am happy to assist in making a **Quorum**

**Comment by zsquareplusc** [comment]
pong

**Comment by kevindawson** [comment]
ping @WisdomPill

**Comment by WisdomPill** [comment]
Yes @kevindawson, as I said in the opening message, I am open to help since I think it's a shame that such a library is not maintained. It has been years since last release and the issues keep piling up. Also because it is the main choice when you look for serial communication with python. I think at least one or two people should actively be able to respond and review the proposed changes.

**Comment by kevindawson** [comment]
@WisdomPill but for others to get involved - (spread the love) - we need a commit bit(s) - the backlog of **pull requests** needs to be addressed. the issues need to be collated - test updated - it's going to require a team - and most importantly an **active** dictator to led/arbitrate.
thoughts???

**Comment by bufferoverflow** [comment]
@kevindawson @WisdomPill How many MR's have you reviewed here? On how many issues have you commented?

**Comment by kevindawson** [comment]
hi @bufferoverflow - I noticed that previously when I had an issue that this module was not actively being developed - so I had to do it myself - as an active open source bod - I gave my fix back as a **pull requests** and like so many before me noticed that nothing happened.
On a recent troll through I noticed @WisdomPill comments and thought - why not - I will give some assistance - so here we are - balls in your court now - do you want to be proactive and would like some assistance - that's the Question - over to you ;)

**Comment by bufferoverflow** [comment]
I think provide maintainers rights to people who just provided one PR is a risk:
- https://github.com/pyserial/pyserial/pulls/WisdomPill
- https://github.com/pyserial/pyserial/pulls/kevindawson

At Apache Software Foundation we did vote for new committers based on their contributions and activity within the community.
Finding maintainers that are really committed and taking care on having tests answering questions is a difficult task. So I recommend to engage, help to manage the issue tracker and one day you might become a maintainer.

**Comment by WisdomPill** [comment]
Well @bufferoverflow I personally did not do much, I raised a question and I have interest in open source code. I do not pretend to be a committer or owner of the project, I was asking because such a library, that is also showcased on pretty much every article about serial communication is left abandoned. I saw people raising the question about releases and I saw that PR get merged once a year, so I guess you need some help, at least in triaging issues or something. People (including myself) are discouraged in helping on a library that does not get attention from the owners. I am not trying to go to war or to accuse people of not behaving, I am just trying to push for some support/maintainers in this awesome library that `pyserial` is. I have interest in integrating asyncio since I use it a lot in my day to day job and to me it would be of great benefit.

**Comment by WisdomPill** [comment]
Yes @bufferoverflow I agree with you, are there other people that have made more contributions that are interested in following more the project?

**Comment by kevindawson** [comment]
_it's not about asking for new committers_ it's about being proactive with all **issues** & **pull requests** 

it's that time again
```txt
So long and Thanks for all the Fish!
```

**Comment by zsquareplusc** [comment]
The PRs are not so easy..
- it is difficult to test as a lot of OS types and versions are supported by the library. No one has access to all of them.
- some aspects only concern e.g. one USB device which may not be available to confirm that the change helps
- it includes hardware so automated testing is very difficult
- almost no PR comes with doc updates or tests
- the library seems to be widely used. something suboptimal may be better than breaking something for everyone else

so helpful would be if other people could help testing PRs and confirm or deny that it improves something.

**Comment by cmcqueen** [comment]
@zsquareplusc : It's a difficult situation this project is in, if you don't want to make any changes without testing on all supported hardware, but you don't have all the hardware that is supported.

Perhaps you could take the approach that you should just go ahead and make changes, and rely on issues to be reported if something breaks.

Maybe you could try maintaining a table of "last known working version" for each hardware. But, I suspect if people download it and it works on their hardware, they're not going to tell you. But they are much more likely to tell you if it *isn't* working.

So, I reckon:

* Accept PRs.
* Rely on issue reporting for hardware breakages.
* Contact people who originally added hardware support, to see if they can provide any follow-up support.
* If needed, improve structure of the code so hardware-specific code is well partitioned, so changes for one hardware are least likely to break other hardware.

**Comment by zsquareplusc** [comment]
beta release is out, please see #528
