### ISSUE TITLE
[miniterm] My reworking with additional features diverged from your recent changes.

### ISSUE THREAD

**Issue by hardkrash** [pyserial/pyserial#5]
I just finished a few features for miniterm on my fork and discovered that you also were reworking miniterm.  

While I agree with the bulk of the changes, switching the reader and writer to bytes from str I believe is too high in the stack.  My rework involved splitting out the representation engine to functions and applying them to both the input from the serial port and to the local echo function.  These operations are in the unicode world.  When leaving the console world then the conversion to bytes is appropriate.

Please see  https://github.com/hardkrash/pyserial/commits/feature/miniterm_features
Features include:
- Pretty printing of ASCII C) codes.
- Color mapping of local and remote text. (Should be turned into a runtime option, default off)
- File input bugfixes.

On a side note:
It would be interesting to take the local echo concept from Mosh. https://mosh.mit.edu
Where the text is locally echoed and highlighted until the remote echos the text.

**Comment by zsquareplusc** [comment]
I think the code should be further divided, splitting of the "repr" modes into a separate class(es) an calling it a "filter" or something alike. The operation is to turn a byte string into a unicode string, which could be useful for reuse.

What I want to have is, that miniterm is a "dumb" terminal, at least with its default options (it currently isn't that on non-windows platforms). The idea behind that is, that I want to use miniterm to debug connections where anything could be received from binary data, to text, to garbage. "Real" terminal programs often implement VT100 or higher and then stop displaying incoming data correctly. So ideally, the default mode of miniterm would even strip/change escape sequences.

* "dumb terminal": show every character, allow basic control codes (LF, CR, TAB, BS, ...)  (default)
* "show controls": show most control characters, except newline
* "show ASCII only": controls and >127 are converted
* "hexdump": well, hex dump everything
* "raw": take the byte as-is, send to stdout without any translation

Color and Unicode are a problem on Windows, maybe colorama solves the first problem, but on the Windows machines I had to deal with, the console is set to latin1/cp1252 and python setting the default encoding only to ASCII.

**Comment by zsquareplusc** [comment]
I've changed the structure a bit, allowing to set the codec for the serial port and then applying transformations in the string domain. There are still some edges, (hex must be done as encoding not text transformation to work correctly, Unicode in the Windows is erhm.... "suboptimal")

**Comment by zsquareplusc** [comment]
I guess the sources for miniterm are "stable" again and your concerns are (mostly) addressed.
