### ISSUE TITLE
can't import the serial module

### ISSUE THREAD

**Issue by saberbin** [pyserial/pyserial#501]
I use pip installed the pyserial. And installed successful.
` pip install pyserial
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyserial
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl (193 kB)
Installing collected packages: pyserial
Successfully installed pyserial-3.4`
But I can `import serial`？I can't get any method to fix it.
`>>> import serial
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
>>> import pyserial
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import pyserial
ModuleNotFoundError: No module named 'pyserial'`

**Comment by WisdomPill** [comment]
Please post the outcome of the following command `pip freeze`

**Comment by saberbin** [comment]
I first install a package named serial, and I uninstalled it to installed the pyserial .Then I found Ican install the pyserial.And I create a new python virtualenv to install pyserial, and it work.Sorry to border you.Thank you.
