### ISSUE TITLE
Serial Reader freezes after a while in windows using python3. I have to close it and open it again

### ISSUE THREAD

**Issue by javieresquivel** [pyserial/pyserial#505]
I'm using the timeout=0 for non-blocking and the way i get the data is like this:

while True:
        en_espera = ser.in_waiting
        if en_espera > 0:
                lectura = ser.read(21).decode("utf-8")        
        time.sleep(1)

The program runs normal for a while but after the time (I don't know how much because always is different) the program freezes and i have to close it and open it again

There is something i have to consider to avoid this? 
thanks.

**Comment by GreenToxicPain** [comment]
Hello. I also got some issues with pyserial. Let me help me with this one (I guess my advice will work for you). Try to read from port all bytes:

byte_number = 21
some_buffer = []
while True:
....while len(some_buffer) < byte_number:
........en_espera = ser.in_waiting
........if en_espera:
............some_buffer += ser.read(en_espera)
....lectura = some_buffer[:byte_number]
....some_buffer = some_buffer[byte_number:]
time.sleep(1)

**Comment by javieresquivel** [comment]
It wasn't a pyserial problem. It's related to this https://www.reddit.com/r/node/comments/d0ggmb/disable_quickedit_mode_on_windowscmd/
