### ISSUE TITLE
Overlapped I/O objects not cancelled properly in Windows

### ISSUE THREAD

**Issue by jeffmerrill** [pyserial/pyserial#51]
The _close() method in serialwin32.py does not close out pending overlapped I/O objects (self._overlappedRead and self._overlappedWrite) correctly. These I/O events should be cancelled before they are destroyed. The current implementation can cause Python to crash with "Segmentation fault" if .close() is called while an I/O event is still pending. This happens because the library attempts to access memory that has already been garbage collected.

I wrote an implementation of _close() based on this MSDN article (https://msdn.microsoft.com/en-us/library/windows/desktop/aa363789(v=vs.85).aspx) that seems to fix the issue:

    def _close(self):
        """internal close port helper"""
        if self.hComPort:
            # Restore original timeout values:
            win32.SetCommTimeouts(self.hComPort, self._orgTimeouts)

            if self._overlappedRead is not None:
                rc = win32.DWORD()
                err = win32.GetOverlappedResult(self.hComPort,
                                             ctypes.byref(self._overlappedRead),
                                             ctypes.byref(rc),
                                             False)
                if not err:
                    win32.GetLastError()

                    err = CancelIoEx(self.hComPort, self._overlappedRead)
                    if not err:
                        win32.GetLastError()
                        raise SerialException("CancelIoEx failed (%r)" % \
                                              ctypes.WinError())
                        
                self._overlappedRead = None
                
            if self._overlappedWrite is not None:
                wc = win32.DWORD()
                err = win32.GetOverlappedResult(self.hComPort,
                                            ctypes.byref(self._overlappedWrite),
                                            ctypes.byref(wc),
                                            False)
                if not err:
                    win32.GetLastError()

                    err = CancelIoEx(self.hComPort, self._overlappedWrite)
                    if not err:
                        win32.GetLastError()
                        raise SerialException("CancelIoEx failed (%r)" % \
                                              ctypes.WinError())
                    else:
                        err = win32.GetOverlappedResult(self.hComPort,
                                            ctypes.byref(self._overlappedWrite),
                                            ctypes.byref(wc),
                                            True)
                
                self._overlappedWrite = None
            
            # Close COM-Port:
            win32.CloseHandle(self.hComPort)
            self.hComPort = None

**Comment by zsquareplusc** [comment]
I've never experienced a crash myself but closing the port is certainly not optimal. This fix looks good except that I would not rise exceptions in case of failure. I don't think that the user can do anything useful if that happens...

Do you want to provide this fix as merge request or should I copy&paste?

**Comment by jeffmerrill** [comment]
The crash doesn't always happen. You have to close it with a particular
timing to expose the issue. I can fix as a merge request. On question, in
the case where I am raising the exception, should I do anything? Just go
ahead and try to close despite the failure?

**Comment by zsquareplusc** [comment]
I guess the crash only happens if data is received within a small critical time window.

re: exception: The current philosophy is that one can call `close()`, even on an already closed port and get no error.

One option is do nothing but leave a comment for the future.
The [warnings](https://docs.python.org/3.5/library/warnings.html) module would be an option but i've not yet used that in pySerial.
Or if the exception is extremely unlikely to happen, leave it in. e.g. it should not raise an exception if one tries to close a port from an unplugged USB-Serial device.

**Comment by zsquareplusc** [comment]
the implementation above was for an older version of pySerial. I've added `cancel_read()`/`cancel_write()` methods instead and call them in `close()`.

**Comment by skewty** [comment]
pyserial 3.4  Windows Version 10.0.17763.864

`serialwin32.py:448  def _cancel_overlapped_io(self, overlapped):`
the method is sometimes called with `overlapped = None` which causes error at `ctypes.byref(overlapped),`.

Is this a regression or something new?

**Comment by skewty** [comment]
Regarding my comment above.  I tracked the issue down to a call to `cancel_write()` being called by [aioserial](https://github.com/changyuheng/aioserial).

To me, the `None` checks done in `serialwin32:227 def _close(self)` should be in `cancel_read()` and `cancel_write()`.   Both `cancel_read()` and `cancel_write()` are public where `_close()` is not.

Outside code has no way of checking the protected values `_overlapped_read` and `_overlapped_write` to do the check themselves.
