### ISSUE TITLE
examples/Tcp_serial_redirect.py only flows one way 

### ISSUE THREAD

**Issue by jdmarques** [pyserial/pyserial#512]
From https://pyserial.readthedocs.io/en/latest/examples.html it states that,

" TCP/IP - serial bridge
This program opens a TCP/IP port. When a connection is made to that port (e.g. with telnet) it forwards all data to the serial port and vice versa. "

I've tried this example but I only get data in the serial -> socket direction. The "vice versa" doesn't work, socket -> serial.
Is the example documentation mistaken or is it the code?

**Comment by zsquareplusc** [comment]
The current version in the repo works for me. Sending and receiving data in both directions.
