### ISSUE TITLE
Add baud rate 74880

### ISSUE THREAD

**Issue by sclukey** [pyserial/pyserial#52]
Would it be possible to add support for the 74880 baud rate? I know it is non-standard, but unfortunately it is used by the ESP 8266 module for it's bootloader, so it would be nice to have.

For context, the Arduino IDE recently added it because of this: arduino/Arduino@db75e677da18d10b5f55f3bdca877b14c196c089

Thanks

**Comment by zsquareplusc** [comment]
This is already supported on popular platforms (win32, OSX, Linux).

The `BAUDRATES` attribute only mentions popular baudrates but on the platforms mentioned above, you can specify arbitrary baudrates. Some serial drivers / hardware may not "hit" the desired baudrate very accurately in some cases (limitations of clock dividers in the hardware).

76800 ([i've seen this number](http://www.esp8266.com/wiki/doku.php?id=getting-started-with-the-esp8266), not the one in the subject) is an even multiple of 9600, so most drivers should be able to set this one accurately.
