### ISSUE TITLE
Problem with read() under Python 3 (.8.5)

### ISSUE THREAD

**Issue by RobMeades** [pyserial/pyserial#520]
I have been using PySerial (3.4) very happily in Windows-based Python scripting to talk with embedded targets.  I have recently moved all my Python 2.7.15 scripts to Python 3, deciding to go straight to Python 3.8.5.  However, I have encountered what appears to be a problem with PySerial `read()` when run on Python 3.8.5.

**Scenario**
I have target HW which is streaming output to the COM port that is being read by the script at 115,200, no flow control.  I know the target is behaving because I can see it being read continuously, no lags/delays, with the Python 2.7.15 version of my script and I can also see it in PuTTY.  The output consists of lines of ASCII text terminated by "\r\n" all streamed together.  However under Python 3.8.5 (PySerial 3.4) `read(1)` is taking about 30 ms to return with each character (measured by dumping the difference between `time()` before and after the `read(1)` call into a list) so that receiving 30 characters is taking about 1 second.

Has anyone else seen a problem of this nature?

**Detail**
I open the serial port as follows:

```
in_handle = serial.Serial("COM8", 115200, timeout=0.05)
```

...and then I have a function running in a thread which reads `in_handle` as follows:

```
        terminator = "\r"
        line = ""
        eol = False
        return_value = None

        try:
            while not eol and line is not None:
                buf = in_handle.read(1)
                if buf:
                    character = buf.decode('ascii')
                    eol = character == terminator
                    if not eol:
                        line = line + character
                else:
                    line = None
            if eol:
                line = line.strip()
        except UnicodeDecodeError:
            # Just ignore it.
            pass
        return_value = line
```

When I use `time()` either side of the `read(1)` call to measure its duration the values I get for a line that is 34 characters long are:

0.03198051452636719
0.031983137130737305
0.031981468200683594
0.0159909725189209
0.031981706619262695
0.0319819450378418
0.0479733943939209
0.031982421875
0.0319826602935791
0.03198075294494629
0.031982421875
0.0319819450378418
0.0319826602935791
0.0159912109375
0.0159909725189209
0.03198122978210449
0.0319819450378418
0.0319821834564209
0.0319821834564209
0.0319821834564209
0.030982255935668945
0.03098273277282715
0.031981706619262695
0.0319826602935791
0.0319821834564209
0.031981706619262695
0.0319819450378418
0.0319819450378418
0.0319821834564209
0.0319828987121582
0.03198075294494629
0.031983375549316406
0.031981468200683594
0.0319821834564209

**Comment by zsquareplusc** [comment]
i can only recommend to not use such small timeout values. they do not work reliably across operating systems and ports.

if you want your own implementation, maybe you are interested in the `inter_byte_timeout instead` of the `timeout`, so you could read many bytes at once until there is a gap in the transmission.

alternatively use something like [`serial.threaded.LineReader`](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.threaded.LineReader)

**Comment by RobMeades** [comment]
Thanks for the swift comment.  I've tried again with a timeout of 0.5 and I've also got a colleague to try my script on his Python 3.7.3 base and, for him, the `read(1`) durations are between 0.01 and 0.005 seconds, much closer to what I am expecting.  So I tried installing Python 3.7.3 myself; doesn't help.

I also realised that I can actually run the Python 3 version of my script on top of Python 2.7 and, when I do that, it runs nice and fast, exactly as expected.

There is something _specifically_ causing a Python 3 slow-down of the `read()` method, possibly just for me.  Hmph.

**Comment by RobMeades** [comment]
OK, PySerial is off the hook: if I take my `read(1)` out of the Python thread it works as fast as I expect.  Something in Python 3 has changed with respect to threading which is slowing everything down.  I will pursue that problem instead.

Thanks again for your time and sorry for bothering you!
