### ISSUE TITLE
Serial() missing 2 required positional arguments: 'CONST_SER_PORT' and 'param'

### ISSUE THREAD

**Issue by brannc2000** [pyserial/pyserial#521]
Running Python3.8 on Unbuntu 20.4.1; pyserial docs state I can create an instance of serial.Serial() without sending params, but I'm getting this error: Serial() missing 2 required positional arguments: 'CONST_SER_PORT' and 'param'.  I've tried running a simple code example off github and get the same issue.  I searched the issues for similar and didn't see anything related.  Anybody seen this? Driving me nuts since I use the code in a class where I want to use the functions in serial to identify the port per the example https://github.com/dataq-instruments/Python/tree/master/binary_comm/other_models: DataqStarterKit.py 
It says I should be able to do this in the PySerial docs, page 7, section 2.2. at a loss.  Runs on Rasbian.

fails at: mySerial = serial.Serial() in below snipet

import serial
import serial.tools.list_ports
import time

slist = [0, 1]
acquiring = False
analog_ranges = tuple((100, 50, 20, 10, 5, 2))
rate_ranges = tuple((10000, 5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5))
range_table = list(())

mySerial = serial.Serial()

def discovery():

    available_ports = list(serial.tools.list_ports.comports())
    hooked_port = ""
    for p in available_ports:
        if "VID:PID=0683" in p.hwid:
            hooked_port = p.device
            break
    if hooked_port:
        print(mySerial.name)
        mySerial.timeout = 0
        mySerial.port = hooked_port
        mySerial.baudrate = 38400
        mySerial.open()
        return True
    else:
        return False
...

**Comment by zsquareplusc** [comment]
can't reproduce. can you post a literal copy of the traceback you get?

**Comment by brannc2000** [comment]
/home/chris/PycharmProjects/DataQ_GUI_Project/venv/bin/python /home/chris/PycharmProjects/DataQ_GUI_Project/test.py
Traceback (most recent call last):
  File "/home/chris/PycharmProjects/DataQ_GUI_Project/test.py", line 6, in <module>
    mydev = serial.Serial()
TypeError: Serial() missing 2 required positional arguments: 'CONST_SER_PORT' and 'param'

Process finished with exit code 1

**Comment by zsquareplusc** [comment]
hm I do not see where that 'CONST_SER_PORT' and 'param' could come from. maybe you have a file called serial somewhere in the python path.. you could check which module is imported with a `print(serial.__file__)` after the import statement.

**Comment by brannc2000** [comment]
will do.  It's got to be a config issue on my Ubuntu set up.  It works on Windows Python/PyCharm and Raspbian.  Give me a few to get back to that config and I'll post results.

**Comment by zsquareplusc** [comment]
looks like you have installed https://pypi.org/project/serial instead of https://pypi.org/project/pyserial

**Comment by brannc2000** [comment]
ugh.  I thought I uninstalled it.  I'll have to see what is up.  After you said you didn't see the issue, I suspected there was something not pyserial going on.  Sorry for dragging you through this...thx for your help

**Comment by brannc2000** [comment]
uninstalled serial and it runs fine.  Conflicting import files was the issue.  problem closed imo
