### ISSUE TITLE
Please refactor serial.tools.list_ports to be a callable function with a return value

### ISSUE THREAD

**Issue by edmundsj** [pyserial/pyserial#522]
Right now, I can only call the serial.tools.list_ports function from the command line, and it prints the available ports to the stdout, with some helpful messages going to stderr. This is nice if I'm calling the function from the command line. But often, I want to know __within a script_ what available ports there are. pyvisa has an analogous function that can be called from python after an import called list_resources(), and it's great! Rather than just having the pyserial main() function write directly to stdout, can someone refactor it so that it has a return value? Then print that return value to stdout in the __main__ function? This way, list_ports() can be called from within a script.

What I have _been_ doing is redirecting stdout to grab the names, but this is very hacky and doesn't play nice with other programs that themselves redirect stdout and stderr (it causes endless headaches with any kind of unit testing).

I will try and figure out how to do this myself in the meantime.

**Comment by ksunden** [comment]
What you are looking for is the `comports` function:

```python
>>> from serial.tools.list_ports import comports
>>> comports()
[<serial.tools.list_ports_linux.SysFS object at 0x7f4ecdd237c0>, <serial.tools.list_ports_linux.SysFS object at 0x7f4ecdd23940>]
```

The objects returned have a number of helpful attributes like serial number and manufacturer and device id.

**Comment by zsquareplusc** [comment]
There is an API for [serial.tools.list_ports (docs)](https://pyserial.readthedocs.io/en/latest/tools.html#module-serial.tools.list_ports) for use as a module. As mentioned by ksunden, `comports()` lists all but there is also `grep("...")` where you can request a filtered subset based on a regexp.
