### ISSUE TITLE
Miniterm: Why such a non-international exit key? Change to CTRL+c

### ISSUE THREAD

**Issue by hoegge** [pyserial/pyserial#524]
The exit key in miniterm by default is CTRL+]

This is not a very good key for international keyboards, where ] is often located on a Alt Gr key combo and therefore does not work with CTRL.

In PlatformIO they have changed it to CTRL+c which makes a lot more sense (option --exit-char=3)

Maybe that could be changed in the standard miniterm as default too?

I understand that makes it possible to send CTRL+c to the other end and ctrl+] is probably a way to avoid conflicts - but then maybe something like CTRL+. would be more widely available on all keyboards?

**Comment by hoegge** [comment]
I rest my case - looking through ASCII codes, I see there is no real good way to do this, so that it works with international keyboards. The CTRL combos are all letters and numbers and a few special characters, that are not easily accessible on international keyboards (maybe we should make a deal with the US and get rid of all international letters and us US keyboards if they get rid of all the imperial units and use only SI / metric :-) Deal? ). 
Sorry for the noise.

**Comment by zsquareplusc** [comment]
It's tricky to select a good key. Some controls are already occupied by newline, backspace, tab, bell, xon, xoff, etc. CTRL+C and CTRL+D i want to send to the target.

i've added "CTRL+T Q" as a new option to exit via menu.

**Comment by hoegge** [comment]
@zsquareplusc Yes - I know - good idea with the CTRL+T Q - thanks!
