### ISSUE TITLE
Cannot open device from named pipe

### ISSUE THREAD

**Issue by swertz** [pyserial/pyserial#526]
I would like to operate a device remotely by piping the data through a network. With pyserial, opening the device directly works fine with:
```
Serial('/dev/ttyUSB0', baudrate=4800, parity=serial.PARITY_EVEN, bytesize=serial.SEVENBITS, stopbits=serial.STOPBITS_ONE, rtscts=True)
```

I first try to configure the device and pipe it through netcat:
```
$ stty -F /dev/ttyUSB0 4800 crtscts cs7 -parodd
$ nc -lk 8888 > /dev/ttyUSB0 < /dev/ttyUSB0
```
On the remote PC, I create a FIFO and pipe that to netcat:
```
mkfifo /tmp/device
nc <IP> 8888 > /tmp/device < /tmp/device
```
And finally I try to open the pipe with pyserial on that PC, but that doesn't work:
```
ser = serial.Serial('/tmp/device', baudrate=4800, parity=serial.PARITY_EVEN, bytesize=serial.SEVENBITS, stopbits=serial.STOPBITS_ONE, rtscts=True)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 323, in _reconfigure_port
    orig_attr = termios.tcgetattr(self.fd)
termios.error: (25, 'Inappropriate ioctl for device')
```

Is there something to change when creating the `Serial` object, or am I missing something more fundamental here?

**Comment by zsquareplusc** [comment]
a pipe is not a serial port ;-)

alternatively use `serial.serial_for_url("socket://<IP>:8888")`. There is also RFC 2217 support, see [URL Handlers](https://pyserial.readthedocs.io/en/latest/url_handlers.html) and a tcp (RFC 2217) server in the examples.

**Comment by swertz** [comment]
> a pipe is not a serial port ;-)

Yes, naively thinking "everything is a file" has its limits! :)

Thanks a lot for the pointers, using `nc` to redirect the serial port on the one side and connecting with `serial_for_url` on the other worked like a charm!
