### ISSUE TITLE
pyserial package couldnot read all the data from the serial port

### ISSUE THREAD

**Issue by AlldreenDev** [pyserial/pyserial#527]
import serial
import io
#serial object init:
port = "COM21"
baudrate = 115200
com_serial = serial.Serial(port, baudrate, timeout = 12)
com_buff = io.TextIOWrapper(io.BufferedRWPair(com_serial,com_serial)
#sending a command into target
com_serial.reset_input_buffer()
com_buff.write("ifconfig" +"\n"))
com_buff.flush()
#reading data
data_all = " "
while True:
      data = " "
      bytetoread = com_serial.inWaiting()
     data = com_serial.read(bytetoread)
     data_all += data
     if bytetoread < 0 :
           print ("No more data")
           break
print ("The receive data: " , data_all)
*********************************************************
**i used the above code to get the data for the ifconfig command (which is more than 7000 bytes). But I am getting only 6000 bytes.**
 The last few lines are missing from the logs.  Please provide inputs for the same.

**Comment by zsquareplusc** [comment]
sure that's code that works? i'd expect `bytetoread < 0` to be always false...

the problem in the description may be because using `inWaiting()` is not a good choice to determine if reading is finished. especially here with `io.TextIOWrapper` which has an additional internal buffer.

**Comment by AlldreenDev** [comment]
import serial
import time
com_serial = serial.Serial("COM6", 115200, timeout = 20)
com_serial.reset_input_buffer()
com_serial.write(b"ifconfig\n")
time.sleep(5)
data = b" "
data = com_serial.read(100000)
print (data)
com_serial.close()

**I have modified the code with this approach. Still i could read only 5000 bytes of data. Is there any problem with my code?
I need to read 2000 more bytes of data.**

**Comment by AlldreenDev** [comment]
> 
> 
> sure that's code that works? i'd expect `bytetoread < 0` to be always false...
> 
> the problem in the description may be because using `inWaiting()` is not a good choice to determine if reading is finished. especially here with `io.TextIOWrapper` which has an additional internal buffer.

import serial
import time
com_serial = serial.Serial("COM6", 115200, timeout = 20)
com_serial.reset_input_buffer()
com_serial.write(b"ifconfig\n")
time.sleep(5)
data = b" "
data = com_serial.read(100000)
print (data)
com_serial.close()

I have modified the code with this approach. Still i could read only 5000 bytes of data. Is there any problem with my code?
I need to read 2000 more bytes of data.

**Comment by AlldreenDev** [comment]
Detailed Explanation: 

I wrote a small pyserial interface to read the data from the COM port after issuing a command. For eg : in my case my system has a lot of network interface so i need to validate whether all the interfaces are up using ifconfig command. But when i gave this command , the output of the command is getting truncated at the last few lines. The approximate size of the output in bytes would be 6500-7000 bytes but i am receiving only around 6000-6150 bytes all the time. Please find my code below '''

import serial
import time
com_serial = serial.Serial("COM6", 115200, timeout = 10)
com_serial.reset_input_buffer()
com_serial.write(b"ifconfig\n")
data_all = b" "
time.sleep(5)
while True:
   bytetoread = com_serial.inWaiting()
   time.sleep(2)
   print ("Bytetoread: " , bytetoread)
   data = com_serial.read(bytetoread)
   data_all += data
   if bytetoread < 1:
      break
print ("Data:", data_all)
com_serial.close()

''' **Output: Bytetoread: 3967 Bytetoread: 179 Bytetoread: 2049 Bytetoread: 0 ** Data: *********with missing data at the end. I am not sure why the logs are missing?

I have tried another approach. 
'''
import serial
import time
com_serial = serial.Serial("COM6", 115200, timeout = 10)
com_serial.reset_input_buffer()
com_serial.write(b"ifconfig\n")
time.sleep(5)
data_all = b" "   
data_all = com_serial.read(100000000)
print (data_all)
com_serial.close()
'''
Here also the last few logs are getting truncated.

**Comment by zsquareplusc** [comment]
try removing the `time.sleep` call. this delays reading from the serial port and the buffer of the operating system could overflow. unfortunately that OS buffer handling is very OS dependent and not configurable on all of them. on Windows there is an API (exposed by pySerial on Windows as `.set_buffer_size()`) but i would try to avoid changing the buffers for cross platform compatibility.

115200 baud are around 11kB/s the default buffer on windows is 4kB so it only holds data for a bit more than 0.3 seconds  if the other end is sending permanently.

**Comment by AlldreenDev** [comment]
> 
> 
> try removing the `time.sleep` call. this delays reading from the serial port and the buffer of the operating system could overflow. unfortunately that OS buffer handling is very OS dependent and not configurable on all of them. on Windows there is an API (exposed by pySerial on Windows as `.set_buffer_size()`) but i would try to avoid changing the buffers for cross platform compatibility.
> 
> 115200 baud are around 11kB/s the default buffer on windows is 4kB so it only holds data for a bit more than 0.3 seconds if the other end is sending permanently.

**Comment by AlldreenDev** [comment]
> 
> 
> try removing the `time.sleep` call. this delays reading from the serial port and the buffer of the operating system could overflow. unfortunately that OS buffer handling is very OS dependent and not configurable on all of them. on Windows there is an API (exposed by pySerial on Windows as `.set_buffer_size()`) but i would try to avoid changing the buffers for cross platform compatibility.
> 
> 115200 baud are around 11kB/s the default buffer on windows is 4kB so it only holds data for a bit more than 0.3 seconds if the other end is sending permanently.

As per @zsquareplusc suggesstion, i have added the set_buffer_size() api in my code and got all the expected data..Looks like increasing the buffer size resolved my issue.Thanks

import serial
import time
com_serial = serial.Serial("COM6", 115200, timeout = 10)
com_serial.set_buffer_size(rx_size = 12800, tx_size = 12800)
com_serial.reset_input_buffer()
com_serial.write(b"ifconfig\n")
data_all = b" "
data_all = com_serial.read(100000000)
print (data_all)
com_serial.close()
