### ISSUE TITLE
Request for testing 3.5b0

### ISSUE THREAD

**Issue by zsquareplusc** [pyserial/pyserial#528]
pySerial V3.5b0 is available in the releases on github and on [pypi.org](https://pypi.org/project/pyserial/3.5b0/).
Using pip install will require specifying the full version (`python -m pip install pyserial==3.5b0`) or the `--pre` option.

Before making the release final, i'd like to get feedback from users of the library. It would be nice if people could comment in this issue if it works successfully (or not...). Please mention Operating system and device types if possible (e.g. CP210x, FTDI , CH340 etc.)

tests are:
- use it with your application
- run `python -m serial.tools.list_ports` (or `pyserial-ports`) and see if expected devices are listed
- run `python -m serial.tools.miniterm` (or `pyserial-miniterm`) to see if connection to a device is possible
- optional, run `python test/run_all_tests.py <PORT>` from the source distribution if you have a loop back adapter at hand (TX->RX, RTS->CTS., DTR->DSR connections)

The list of changes can be found here: https://github.com/pyserial/pyserial/blob/master/CHANGES.rst#version-35b0-2020-09-21

**Comment by cmcqueen** [comment]
Windows 10 Pro. Python 3.8.3. I tried both 32-bit and 64-bit.

`python -m serial.tools.list_ports` worked well, and also with the `-v` option.

`python -m serial.tools.miniterm` worked well on a port at 115200bps.

**Comment by johannesacco** [comment]
Ubuntu 18.04, Python 2.7.17. CP2108, CP2105, FT230XS, TTL-232RG.
`python -m serial.tools.list_ports` works fine

Ubuntu 18.04, Python 2.7.17 TTL-232RG
`python -m serial.tools.miniterm` works fine

Ubuntu 18.04, Raspian Buster CP2105, FT230XS, TTL-232RG
Tested to communicate on different baud rates

**Comment by hoihu** [comment]
Windows 10.0.17134 Enterprise tested with 

- STM32 board running VCP emulation (com ports) and micropython
- Nordic PCA10059 dev board with NRF52840 and micropython

`python -m serial.tools.list_ports` worked
`python -m serial.tools.miniterm` worked

**Comment by hoihu** [comment]
Perhaps a small note about `miniterm`. 

What I did notice in a micropython REPL, that backspace is still not working, but perhaps that's intended?

**Comment by oskay** [comment]
I tested two devices each on the following OS and python configurations:
* macOS 10.14.6, Python 2.7.17
* macOS 10.14.6, Python 3.7.7
* macOS 10.15.6, Python 2.7.16
* macOS 11.0 (beta 7), Python 2.7.16
* macOS 11.0 (beta 7), Python 3.8.2

The two devices tested were:
* USB peripheral on 8-bit PIC microcontroller device
* FTDI TTL-232R, communicating to Arduino-class device

For each OS, python version, and device, I tested `list_ports` and `miniterm` communication. As far as I can tell, everything worked correctly and as expected in these tests.

**Comment by jacobian91** [comment]
Tested with Windows 10 Enterprise LTSC, 64bit, 3.8.1 Python.
Test with application, my change only required was updating the key-word name in `serialutil.read_until` changed in daaf33edd1a054a52fa8ec297a5767d06f96a942.
Tested two devices with RS232 via [FTDI](https://www.digikey.com/product-detail/en/ftdi-future-technology-devices-international-ltd/USB-RS232-WE-1800-BT-5-0/768-1078-ND/2441365), no issues on either device.
 - [Lab Instrument](https://sonicconcepts.com/wattmeter-series/) tested send and receive.
 - [Lab Weight Scale](https://www.sartorius.com/en/products/weighing/laboratory-balances/entry-level-balances/entris).

Tested: `pyserial-ports` (all ports shown)
Tested: `pyserial-miniterm` (able to connect to device)

**Comment by jacobian91** [comment]
Tested with Windows 10 Enterprise, 64bit, 3.8.1 Python.
Tested ESP8266 NodeMCU Board, with MicroPython loaded onto it. USB connection and CP2102.

Tested: `pyserial-ports` (all ports shown)
Tested: `pyserial-miniterm `(able to bring up and control the REPL that is on the board)

**Comment by oskay** [comment]
I came across one case where `list_ports` failed on Windows. The error appears to be resolved by https://github.com/pyserial/pyserial/commit/b3c01bf992c6ba9890de1d2a6e1d80d9ab36db5f

**Comment by ivankravets** [comment]
@zsquareplusc, could we request the final 3.5 release?  

macOS Big Sur people are affected. I asked them to try the latest beta and it works. See https://community.platformio.org/t/esp8266-big-sur-11-0-1/17129

Thanks!

**Comment by oskay** [comment]
It would be nice to include a patch for #545 in the release, since a lot of new Big Sur users will be starting on M1 hardware.

**Comment by davidfokkema** [comment]
Tested on MacOS 10.15.7 Catalina with python 3.9.0. Tested my application, `list_ports` and `miniterm` with an Arduino Nano 33 IoT. Worked perfectly. I have some students who have already upgraded to MacOS Big Sur so they (and I!) would be very pleased with a final 3.5 release. Thanks!

**Comment by zsquareplusc** [comment]
v3.5  released
