### ISSUE TITLE
Wrong release date of v3.4 on PyPI

### ISSUE THREAD

**Issue by keelung-yang** [pyserial/pyserial#529]
https://pypi.org/project/pyserial/#files
![image](https://user-images.githubusercontent.com/20385450/93756528-d37ff280-fc37-11ea-859d-1e3ad3f347e8.png)

**Comment by zsquareplusc** [comment]
That's not wrong, it's really that old...

maybe setting 3.4 as release on github was confusing, but i can't set the date on this. the tag still has the original date.
i wanted that 3.4 is shown on the side on the github page instead of 3.2.1. it should soon show 3.5 :-)

**Comment by keelung-yang** [comment]
Sorry It's my mistake. I checked my early downloaded source on master branch is v3.4.1. I thought is v3.3.x since v3.4 is released on yesterday on github. 
![image](https://user-images.githubusercontent.com/20385450/93836916-d8d05200-fcb6-11ea-85e4-7b13e0989fdd.png)
