### ISSUE TITLE
Feature request: open() methods support for context manager

### ISSUE THREAD

**Issue by Apteryks** [pyserial/pyserial#53]
I found a use case where I'm only interested in managing a pre-configured pyserial object.

I'd like to do it that way:
```
import serial

# My pre-configured serial object
ser = serial.Serial()
ser.baudrate = 115200
ser.port = '/dev/ttyUSB0'

with ser.open():
    assert ser.isOpen()

assert not ser.isOpen()
```

It seems the only changes required in PySerial to do this would be to return the serial object itself when calling any of the open() method implementations (posix, ironpython,  etc.).

Could this be considered for inclusion in PySerial?

**Comment by Apteryks** [comment]
I have made a small commits which addresses this: https://github.com/Apteryks/pyserial/commit/6e60ab2f781606419fd5486957492cde60fd073e. Feel free to pull this in, or discuss it here :)

**Comment by Apteryks** [comment]
I found the following workaround: 
```
ser.open()
with ser:
    assert ser.isOpen()
assert not ser.isOpen()
```

**Comment by zsquareplusc** [comment]
context manager support is [implemented] (https://github.com/pyserial/pyserial/blob/master/serial/serialutil.py#L500), [see also](https://pyserial.readthedocs.org/en/latest/shortintro.html).

The port is opened when the name is specified:

```python
with serial.Serial("/dev/ttyUSB0") as s:
    s.write(b"hello")
```

or call `open()` later:
```python
with serial.Serial() as s:
    s.port = "/dev/ttyUSB0"
    s.open()
    s.write(b"hello")
```

**Comment by Apteryks** [comment]
Thank you for your quick reply! My use case is opening a pre-configured (serial object already exists) with the "with" context manager, without call the open() method myself. I understand how the current design work, but it seems convenient only in the case where the serial object is created anew. I would think __enter__ should call the open() method, this would make sense as the __exit__ calls close(). Failing that, my suggested changes would allow using the context manager on the open() call, which would be convenient for the use case described above, without breaking any of the existing API.
