### ISSUE TITLE
list_ports_common.py:usb_description should not return None

### ISSUE THREAD

**Issue by frankholton** [pyserial/pyserial#54]
The update to 3.0 caused list_ports.grep to stop working for me on a Linux system. I am using a CDC USB serial device. Example output from `python3 -m serial.tools.list_ports -v`
On 3.0
```
/dev/ttyACM0
    desc: None
    hwid: USB VID:PID=03EB:2404 LOCATION=1-1.1.1
```
On 2.7
```
/dev/ttyACM0
    desc: ttyACM0
    hwid: USB VID:PID=03eb:2404
```
Patch that behaves the same way on my system as 2.7.
```
diff --git a/serial/tools/list_ports_common.py b/serial/tools/list_ports_common.py
index e5b0394..640b2a1 100644
--- a/serial/tools/list_ports_common.py
+++ b/serial/tools/list_ports_common.py
@@ -46,8 +46,10 @@ class ListPortInfo(object):
     def usb_description(self):
         if self.interface is not None:
             return '{} - {}'.format(self.product, self.interface)
-        else:
+        elif self.product is not None:
             return self.product
+        else:
+            return self.name
 
     def usb_info(self):
         return 'USB VID:PID={:04X}:{:04X}{}{}'.format(
-- 
2.3.0
```

**Comment by zsquareplusc** [comment]
The idea would be that the text from the USB descriptor is in `product`. Does it fail to read out from this specific device or does it fail generally on your system, with CDC devices? It works for the devices I have.

Anyway a fix to return the device name is still better than returning `None`

**Comment by frankholton** [comment]
Its likely the system itself causing it. It is an embedded system with an older kernel (3.14.28). I am missing the serial, product, and interface files in sysfs. pyserial 2.7 was unable to get anymore information either on this machine. I don't see a way to find that information though sysfs on this system. Either way the fix you applied fixes list_ports.grep. Thanks.
