### ISSUE TITLE
list_ports not listing extended USB port info (macOS Big Sur, M1 architecture)

### ISSUE THREAD

**Issue by oskay** [pyserial/pyserial#545]
Briefly, extended USB attributes are not being listed by serial.tools.list_ports.comports on a Mac running the new M1 processor.

Test computers have near-identical setup:
* Mac Mini
* macOS Big Sur 11.0.1
* Python 3.8
* Pyserial 3.5b0

Both are running the following (abridged) test code:

```python
from serial.tools.list_ports import comports
com_ports_list  = list(comports())
print_list = []
for port in com_ports_list:
    for port_item in port:
        print_list.append(port_item)
```

Printing the list, I get the following (redacted to remove some uninteresting entries):

Computer 1: Mac Mini (Intel, 2014)
```
/dev/cu.Bluetooth-Incoming-Port
n/a
n/a
/dev/cu.usbmodem14201
EiBotBoard,
USB VID:PID=04D8:FD92 LOCATION=20-2
```

Computer 2: Mac Mini (M1, 2020)
```
/dev/cu.Bluetooth-Incoming-Port
n/a
n/a
/dev/cu.usbmodem1101
n/a
n/a
```

**Comment by oskay** [comment]
Additional info:
The System Information app on the M1 computer does list the same USB device name, VID, PID, so that information *does* appear to be properly enumerated at least to the OS.

Digging into the behavior of pyserial a little further, in list_ports_osx.py, the line
```python
            usb_device = GetParentDeviceByType(service, "IOUSBDevice")
```
appears to give a value of `None` for each port on the M1 computer. This may be a key difference.

**Comment by oskay** [comment]
Renaming `IOUSBDevice` -> `IOUSBHostDevice` **appears to correct the issue**.

Without diving in too deeply, it looks like [IOUSBDevice has been deprecated](https://developer.apple.com/documentation/kernel/iousbdevice) and supported macOS 10.0 - 10.10, making it deprecated since about (2015).

From what I understand, we could implement this fix in a backwards-compatible fashion with:

```python
             usb_device = GetParentDeviceByType(service, "IOUSBHostDevice")
             if not usb_device:
                 usb_device = GetParentDeviceByType(service, "IOUSBDevice")
```

For better or worse, I do not currently have a system running macOS prior to 10.11 that I can test with right now.

**Comment by chairman888** [comment]
PR posted

chairman888:545-osx-use-iousbhostdevice-instead

**Comment by oskay** [comment]
https://github.com/pyserial/pyserial/pull/546
