### ISSUE TITLE
Change of writeTimeout (2.7) to write_timeout (3.0) breaks existing client code

### ISSUE THREAD

**Issue by MrYsLab** [pyserial/pyserial#55]
This change breaks pymata_aio (see https://github.com/MrYsLab/pymata-aio/issues/34#issuecomment-168404752) which originally used pyserial 2.7.

Please change the library to accept 2.7 parameters.

**Comment by zsquareplusc** [comment]
An other workaround would be to set the write timeout afterwards via function call.

**Comment by MrYsLab** [comment]
Sorry, but the fix did not work.

I have a very simple example program I am running with Python 3.5:

```
import serial

my_serial = serial.Serial('/dev/ttyACM0', 57500, timeout=1, writeTimeout=1)
```

If I  clone the pyserial repository and run the code in the pyserial directory, all works correctly. However, if I move the example to my home directory and execute it, I get the following results:

```
$ python3 sertest.py
Traceback (most recent call last):
  File "sertest.py", line 3, in <module>
    my_serial = serial.Serial('/dev/ttyACM0', 57500, timeout=1, writeTimeout=1)
TypeError: __init__() got an unexpected keyword argument 'writeTimeout'
```

Your suggestion of setting write_timeout out of the init would work, but I have several libraries currently dependent upon pyserial 2.7 and I do not want to have to update my code in all instances.

If necessary, I can limit my setup.py files to only install pyserial 2.7, but I would much prefer to allow my users use the latest and greatest version of pyserial.

Thanks.

**Comment by zsquareplusc** [comment]
When it works in one place and not the other, I suspect that there are multiple copies of pySerial found by Python. Maybe you need to set `PYTHONPATH` to the git branch to ensure it is preferred.

**Comment by MrYsLab** [comment]
I don't think that is the cause. I methodically went through my drives and removed any old versions of pyserial and pyserial clones.

I then executed my test program and got the following expected results:

```
python3 sertest.py
Traceback (most recent call last):
  File "sertest.py", line 1, in <module>
    import serial
ImportError: No module named 'serial'
```

I then did a pip install of pyserial and reran my test, and the results are the same:

```
$ sudo pip3 install pyserial
Collecting pyserial
  Downloading pyserial-3.0.tar.gz (133kB)
    100% |████████████████████████████████| 135kB 4.0MB/s 
Installing collected packages: pyserial
  Running setup.py install for pyserial
Successfully installed pyserial-3.0

$ python3 sertest.py
Traceback (most recent call last):
  File "sertest.py", line 3, in <module>
    my_serial = serial.Serial('/dev/ttyACM0', 57500, timeout=1, writeTimeout=1)
TypeError: __init__() got an unexpected keyword argument 'writeTimeout'
```

**Comment by zsquareplusc** [comment]
Ah, I did not update the PyPi package, that would need a new release and I'd wait a few days before doing that, maybe other issues show up once the new release is actually used by more people after the holidays.

**Comment by MrYsLab** [comment]
Ok. I did a local pip install using the current repository and it did fix the problem. I will anxiously await the release to pypi.

Thanks for your help

**Comment by MrYsLab** [comment]
Has a release date been set yet for the fixes above? I am getting inundated with complaints. If necessary, I will re-release my code forcing the loading of pyserial 2.7, but I would prefer to use pyserial 3.x.

**Comment by zsquareplusc** [comment]
released

**Comment by MrYsLab** [comment]
Thanks.
