### ISSUE TITLE
Threaded self.protocol_factory() should be self.protocol_factory

### ISSUE THREAD

**Issue by Vile-Dev** [pyserial/pyserial#559]
https://github.com/pyserial/pyserial/blob/0e7634747568547b8a7f9fd0c48ed74f16af4b23/serial/threaded/__init__.py#L185

This line causes a ReadHandler call error when invoked. Removing the parenthesis resolves the issue.

Error produced:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "...\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "...\serial\threaded\__init__.py", line 185, in run
    self.protocol = self.protocol_factory()
TypeError: 'readHandler' object is not callable
```

Resolution:
`self.protocol = self.protocol_factory`

**Comment by benjione** [comment]
I think that is intended, just use

```
def __call__(self):
        return self
```

This should resolve your problems.
