### ISSUE TITLE
Update documentation - KB2999226 required on Win 7 SP1

### ISSUE THREAD

**Issue by cxw42** [pyserial/pyserial#56]
In order to run the [win32 installer](https://pypi.python.org/packages/any/p/pyserial/pyserial-3.0.win32.exe#md5=a23d97fee6f816a17f546c02265cca43) (2015-12-29) from pypi, I had to install [KB299226](https://support.microsoft.com/en-us/kb/2999226) from MSDN.  This fixed an error that I was missing api-ms-win-crt-string-l1-1-0.dll.  I didn't see this mentioned in the docs, but I'm not sure where to add it - would you be willing to update appropriately, or let me know which file to update in a pull request?  Thanks!

**Comment by zsquareplusc** [comment]
For which Python version did you install?

The installer was created (`bdist_wininst`) using Python 3.5 on a Win 7 machine.

**Comment by cxw42** [comment]
OS is Win7 Pro SP1 x64.  Python 3.3 x64 installed on Windows (c:\Python33), plus Python 2.7 and 3.4 installed on cygwin x64 on the same machine.  Curiously, once I installed the KB and the installer fired up, it errored out with "No Python installation found in the registry."

**Comment by zsquareplusc** [comment]
is this still an issue, now distributing a wheel instead of .exe?

**Comment by hubslave** [comment]
Not anymore, it was only relevant for exe
