### ISSUE TITLE
Resetting serial device causes kernel panic on Raspberry Pi

### ISSUE THREAD

**Issue by benlye** [pyserial/pyserial#564]
I'm using pyserial 3.5 to communicate with a 3D printer board which is attached via USB to a Raspberry Pi 3 Model B.  One of the commands I send causes the board to reset.  Periodically when the board resets I get a Kernel Panic.

The problem can be reproduced with this code.  If I run it 5-20 times consecutively I will eventually get a kernel panic.
```python
import serial

s = serial.Serial('/dev/ttyACM0', 115200) 
s.write(b'M997\r\n')
s.close()
```

If instead of using pyserial I use this shell script to send the reset command I *never* get a panic:
```
stty -F /dev/ttyACM0 115200 -echo > /dev/null
echo M997 >> /dev/ttyACM0
```

So it seems to me like this is a pyserial problem, or at least pyserial is implicated in triggering it in some way.

I'd love to get some pointers towards debugging and diagnosing this issue further.  It's a problem I first saw a few years ago so it's not new.  Back then I could work around it by not using pyserial, but now I cannot, so I'd like to figure it out if I can.

This is an excerpt from /var/log/messages following a crash:
[messages.log](https://github.com/pyserial/pyserial/files/5929362/messages.log)

If it is interesting, the printer board is an LPC1769-based BTT SKR 1.4 Turbo running the latest Marlin 2.0.x-bugfix code, but I've see the problem occur on other LPC1768 boards as well.

**Comment by harryberlin** [comment]
the same with s.flush() before close?

**Comment by benlye** [comment]
After doing more testing I found that the commands which I thought did not trigger a crash actually do as well (it just takes longer).  

I suspect, but have not confirmed yet, that something else on the system is using pySerial to communicate with the device so I'm in the process of setting up a new clean install on my Pi to test with.

If the clean install has the same problem I'll close this issue because the root cause has to be something else.

**Comment by benlye** [comment]
Confirmed that on a different Pi 3B with a brand new Raspbian installation, fully updated, this will eventually crash it:
```
stty -F /dev/ttyACM0 115200 -echo > /dev/null
i=0; while true; do echo $i; echo M997 >> /dev/ttyACM0; ((i=i+1)); sleep 15; done
```
I've had up to 15-20 resets before it crashes, but it always crashes.

Not a pyserial issue then.
