### ISSUE TITLE
interCharTimeout kwarg doesn't work

### ISSUE THREAD

**Issue by dhylands** [pyserial/pyserial#58]
I'm running Ubuntu 14.04 and just did:
```
sudo pip3 install --upgrade pyserial
```
which installed 
and now the interCharTimeout kwarg no longer works.
```
507 >python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> serial.VERSION
'3.0'
>>> ser = serial.Serial('/dev/ttyACM0', baudrate=115200, interCharTimeout=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'interCharTimeout'
>>> 
```

**Comment by dhylands** [comment]
Hmm. It works fine using the version from github, but the version installed using pip3 is missing the interCharTimeout checks in the __init__

Ahh - I see the fix was only commited a couple days ago, so it probably hasn't made it out to PyPI yet.

I'll close this...

**Comment by zsquareplusc** [comment]
Will release an update in a few days, still waiting for other bugs ;-)

Related to #55 which was for an other parameter, but the fix includes this one too.
