### ISSUE TITLE
No COM ports found

### ISSUE THREAD

**Issue by TitouanLabourdette** [pyserial/pyserial#592]
Hi.

I want to read/sniff a USB port in particular, but I can't find the name of the ports on Windows 10.

I tried this code to check if there is any port but it display I have none : 
```Python
import sys
import serial
import glob
import time
from io import StringIO
from serial import *

import serial.tools.list_ports
comlist = serial.tools.list_ports.comports()
connected = []
for element in comlist:
    connected.append(element.device)
print("Connected COM ports: " + str(comlist))
```
Results when the code is ran : `Connected COM ports: []`

I also tried `python -m serial.tools.list_ports` in a CMD and I had this result : `no ports found`

Do you know how I could find the name of all my USB ports ? Do you know how I could sniff all or a specific USB port ? I want to use the data I receive and not only displays it (so no Wireshark).

Thank you for reading me.

**Comment by Resonanz** [comment]
I have some code that I could send you that detects the comports on Windows, Mac, and Linux. It’s bedtime here so I couldn’t do it until tomorrow, so let me know if nobody else helps you. Cheers, Rob

**Comment by TitouanLabourdette** [comment]
Hi.

Thank you for offering your code. I think I'm good now, I got an answer in another forum post : the problem was that the connected device was a hard drive so it did not use any COM port. With another peripheral it seemed to work. I was able to send and receive USB packet.

Thank you for taking the time to reply to me.

**Comment by zsquareplusc** [comment]
seems to be resolved -> closing

**Comment by xiaor2** [comment]
Hi, I have the same issue. Could you please tell me how to detect a USB port?
