### ISSUE TITLE
I want to write an angle to a servo motor eg. 90 degrees using python, without asking for an input is there a way to do it?

### ISSUE THREAD

**Issue by 5av10** [pyserial/pyserial#596]

**Comment by Colum31** [comment]
Servo motors are not controlled by serial, they are (usually) controlled using a PWM signal.
So this question is asked at the wrong place.

The answer also depends on the specific hardware you are using.
It would be helpful, if you would further specify your question.

Here is a way you could do it on a Raspberry Pi:

1. Import the RPi.GPIO libary
2. setup the pin you hooked your servo up
3. send a PWM pulse, that will put the servo in the 90° position

There are plenty of tutorials and documentation on the interwebs. I think you will find a better answer there.

**Comment by 5av10** [comment]
Actually I wanted to talk to a servo using python and arduino so here's how I did it:
Arduino code:
#include<Servo.h>
Servo servom;



void setup() {
  servom.attach(2);
  Serial.begin(9600);
  Serial.setTimeout(10);

}

void loop() {
  while(Serial.available()==0){}
  String data=Serial.readString();
  servom.write(data.toInt());
  Serial.print(data);

}

Pytthon code:
import serial
import time

ser=serial.Serial("COM10",9600)

angle=18
num=str(angle)

while True:
    #ser.flush()
    ser.write(num.encode())
    time.sleep(0.1)

**Comment by Colum31** [comment]
Is your solution working?
It looks okay to me, but you don't need that while loop in the python code.
The servo should stay in place, and you don't change the angle value anyway.

**Comment by 5av10** [comment]
Yeah it works fine, there is more to the while loop in my code but I left it as is so as to reference it better

**Comment by 5av10** [comment]
> Is your solution working?
> It looks okay to me, but you don't need that while loop in the python code.
> The servo should stay in place, and you don't change the angle value anyway.

could you tell me how to do the same thing for a stepper motor, using a stepper driver and a nema 23 stepper motor

**Comment by Colum31** [comment]
> could you tell me how to do the same thing for a stepper motor, using a stepper driver and a nema 23 stepper motor

This is not the right place to ask, as your asking for arduino code.

I haven't worked with stepper motors, but the way you send values to the arduino stays the same.
You just have to find a way to implement your stepper motor (I would suggest a library), and use library function to move the stepper motor, according to values you have received from the serial connection.

As I mentioned, you will find more resources on the internet, that will walk you through.

Again, don't ask here, as this has nothing to do with the pyserial library. 
For advice on code, use stackoverflow or the arduino forums.

**Comment by 5av10** [comment]
Thanks
