### ISSUE TITLE
PySerial Convert String to Bytes

### ISSUE THREAD

**Issue by Zipgit** [pyserial/pyserial#599]
Hello, Pythons:
I am trying to write some code that will write a table of memory values via RS232 to a radio that has a programmable memory. The memory "write" command looks like this (this is drawn directly from the radio's interface instructions):
**

> MW1 00000071500011;

**
The semi-colon at the end of the command line is a requirement of the radio interface.
My bare-bones code has a definition for the port's properties, as follows:
**

> R5000 = serial.Serial(
> 	port='COM12',
> 	baudrate=4800,
> 	parity=serial.PARITY_NONE,
> 	stopbits=serial.STOPBITS_TWO,
>         bytesize=serial.EIGHTBITS,

**
When I attempt to use the command, **R5000.write ("MW1 00000071500011;")** I receive the error message that Unicode isn't allowed, that it must be in bytes.
So I used an 'online converter" and pasted the command in as bytes, that is to say:
R5000.write ('01001101010101110011000100100000001100000011000000110000001100000011000000110000001101110011000100110101001100000011000000110000001100010011000100111011')
But, I still get an error whether I remove the single or double quotes, whether I break it into groups of 8 bits with Spaces (or not) ---- it keeps flagging an error that Unicode isn't allowed, but there isn't any Unicode after the R5000.write command
Clearly, I am missing something....not surprisingly, since I am new to Python and I have nearly zero experience working with serial interfaces.
If anyone can offer some helpful hints, it would be greatly appreciated.
M

**Comment by Zipgit** [comment]
Also, it seems that PySerial has no way to set the number of start bits (comments?). The radio interface documentation indicates an Asynchronous transfer mode, but I have been told that I do NOT need to bother with using PySerial "Asyncio"....that I should just ignore that fact and soldier on....

**Comment by Zipgit** [comment]
And.....I could use some help with the in-line conversion of Unicode (or ASCII....all the characters in the memory-write command, MW1 00000071500011; are within the 'core' of the ASCII characters) within the Python code. I have seen various references to a command **bytes()** but I have also found other conversion methods for Python that rely on a concatenation of several commands, and I am not sure what I am doing wrong with these.

**Comment by harryberlin** [comment]
Do you have tried:
.write(b"MW1 00000071500011;")

**Comment by Zipgit** [comment]
OMG. It works!
Where is the documentation in Python (or, in PySerial) for the  << b >> prefix? I assume that << b >> is shorthand for "convert to bytes"

**Comment by Zipgit** [comment]
Next step.... getting it to work with a list read from an Excel spread sheet (using Pandas)
Thank you.

**Comment by zsquareplusc** [comment]
i see a "it works" above so i'll close this.
