### ISSUE TITLE
pyserial 3 not working in windows 10

### ISSUE THREAD

**Issue by 3dmation** [pyserial/pyserial#60]
Hey folks, I've got three lcd screens communicating with each other and the host computer via pyserial and python under Windows 7. To utilize another piece of hardware, I was required to upgrade the host computer to windows 10. Now, I'm not getting my python script to work correctly in windows 10. This is the error I'm getting.

Traceback (most recent call last):
File "runscript.py line 13, in <module>
ser = serial.Serial(port = 6, baudrate = 9600, timeout = 0)
File "C:\Python27\lib\site-packages\serial\serialWin32.py", line 38, in __init__
SerialBase.__init__(self, "args, ""kwargs)
File "C:\Python27\lib\site-packages\serial\serialutil.py", line 282, in __init__
self.open()
File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 66, in open
raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinErrorr()))
serial.serialutil.SerialException: could not open port 'COM7': WindowsError(2, 'The system cannot find the file specified.')

My python code to call the serial port is just this...

5 import sys, re, os, time, serial, pygame, winsound

13 ser = serial.Serial(port=6, baudrate=9600, timeout=999)
14 serRightScreen = serial.Serial(port=3, baudrate=9600, timeout=999)
15 serLeftScreen = serial.Serial(port= 5, baudrate=9600, timeout=999)

Again, the screens themselves and the code works fine with python interface which was working fine under Windows 7, but not under Windows 10. I'd love to have your input.

Barry

**Comment by zsquareplusc** [comment]
With pySerial v3.0 the ability to specify ports by number has been removed (it does not work well across platforms). Just use a string like `"COM6"` instead, this also works with any older version of pySerial (well with very old ones you may need to write `"\\.\COM6"`  ;-).

**Comment by 3dmation** [comment]
Thanks for the suggestion.  This did work!  BTW, as part of troubleshooting, I also installed the 64 bit unofficial version.  Is that going to be official soon?

**Comment by zsquareplusc** [comment]
I do not know of any "unofficial 64 bit version". pySerial supports 32 and 64 bit Python installation, if that is meant.
