### ISSUE TITLE
UNable TO READ PING RESPONSE 

### ISSUE THREAD

**Issue by LP-Codes** [pyserial/pyserial#610]
Hi team,
I was trying to read ping response but I m not able to Read while trying with pyserial though same command when tried with teraterm return the response also with other commands I am able to Read the data 

What I am trying is 

Ser = serial.Serial(comport,baudrate, timeout =1)
Ser.write(b'AT+PING=6google.com')
Response = Ser.read(Sr.inwaitin())

Kindly assist

**Comment by zsquareplusc** [comment]
Please try it with CR LF appended (`\r\n`):
`Ser.write(b'AT+PING=6google.com\r\n')`

**Comment by LP-Codes** [comment]
@zsquareplusc  thanks  I had already tried this but didn't it didn't help

**Comment by zsquareplusc** [comment]
and you read an empty byte string? or is there some sort of error/exception (at least the example code above has typos i the last line)?
