### ISSUE TITLE
Unable  to stop data reading 

### ISSUE THREAD

**Issue by LP-Codes** [pyserial/pyserial#611]
Hi team,

I am sending an AT command & waiting for 10 minutes before reading the data 
The issue is the incoming data is not stopping  some values are coming every  second continuously  ,how can u forcefully read the data which has come until 10 minutes  of wait time 

I have tried 

Sr= serial.Serial(port,baudrate,timeout=1)
Sr.write(b'AT command\r\n')
Time.sleep(600)
Response = Sr.readall() #also tried Sr.readlines(Sr.inwaiting()) &  Sr.read(Sr.inwaiting())

if I forcefully remove connections after 10 minutes then only I can see the response command getting completed   r else the script won't end,  In logs I  can some bytes of data  are populated continuously kind assist

**Comment by zsquareplusc** [comment]
The serial buffer of the OS will be limited and loose data if you don't read from the port.

I'm not sure about the question.
- if you want to throw away and data that has been received during the `time.sleep`, then `Sr.reset_input_buffer()` would throw away the data.
- if you are interested in all the data that is sent during the delay, then you probably need to set up a loop or thread to read from the port all the time.

i usually  set up a read thread that processes all data from the serial port, that way it can also filter out different messages (or channels).

and example with a loop could look like this:
```
with serial.Serial(port, baudrate, timeout=1) as s:
    t_end = time.monotonic() + 600
    data = bytearray()
    while time.monotonic() < t_end:
        data.extend(s.read(s.in_waiting))
    print(bytes(data))
´´´
