### ISSUE TITLE
Update Copyright year to 2022

### ISSUE THREAD

**Issue by anirudhlakhotia** [pyserial/pyserial#631]
The year in LICENSE.txt must be updated to 2022

**Comment by real-yfprojects** [comment]
Also, why doesn't the license match the [bsd-3 clause](https://opensource.org/licenses/BSD-3-Clause) but instead has the following line inserted?

> All Rights Reserved.

**Comment by anirudhlakhotia** [comment]
> That's not correct, and a simple Google search will be quite educational for you.

Indeed! Didn't know about this earlier :) 
Thanks a lot!
