### ISSUE TITLE
Getting garbage values

### ISSUE THREAD

**Issue by ranjitkathiriya** [pyserial/pyserial#645]
Hello there,

I am using an RFID reader and raspberry pi. I am getting the data, but I am getting garbage values with data. 

Here is my code: 

```
import serial
import sys
from time import sleep

ser = serial.Serial("/dev/ttyUSB0", baudrate=19200, parity=serial.PARITY_NONE, bytesize=serial.EIGHTBITS,
                    stopbits=serial.STOPBITS_ONE, timeout=1)
sleep(0.5)
ser.write(b"$Z01005B#")
print(ser.read_until(expected=b'#').decode("utf8", "replace"))
sleep(0.5)
ser.write(b"$C01020141#")
print(ser.read_until(expected=b'#').decode("utf8", "replace"))
sleep(0.5)
ser.write(b"$A0101D05#")
print(ser.read_until(expected=b'#').decode("utf8", "replace"))
storedata = None

while (ser.is_open == True):
    sleep(0.5)
    line = ser.read_until(expected=b'#')
    string = line.decode("utf8", "replace")
    print(string)
```

and my output,

(tflite) kuka-ai@kukaai-ROG-Zephyrus-G15-GA502IU-GA502IU:~/Desktop/IOTMotion_tracking/tflite/examples/lite/examples/object_detection/raspberry_pi$ python rfid.py 
��]����������� ������<������x�������(n�
                                       ����\��������$Z0102OK5D#
�����P�0��
          `�
            >�������n���$�����������$C0104OK0143#
$�����  ���|����������������p���������.r���$A0102ER55#
�����@��.���x�������~������������������r����������0��>�����������<��|���.��
                                                                           ����_������������������
                                                                                                  ��ݸ���� ������
��(����/��p���������`���,��,`�����
�������������,��
                ��,��|h���/�����������������,��������������������.������������������� ����������������������/��������������z;���>�_����>����������
�>����,����,��^����������������^������.��
                                         ��_���B��`������$A0112OKD9001130028297543E#
 �����^���������<������������/��.��$A0112OKD9001130028297543E#
����������=���,����,X����������������$A0112OKD9001130028297543E#
}�,����
       ��,����.������������������.����������"�������Ȭ����������.��(��������������������������,�������?���������������� ������,������,����������������������<������������������ ���

I am getting output like this way, and A0112OKD9001130028297543E is my response from the device I am getting a response but with garbage, can you help how can I remove this

**Comment by b4sen** [comment]
usually this happens if your `baud rates` mismatch. what is the baud rate of the device on `/dev/ttyUSB0`? I see you call `python rfid.py`, as far as I know RFID baud rates are `9600 bps` and you have `19200`.
