### ISSUE TITLE
getTimeout not available in pyserial 3.0

### ISSUE THREAD

**Issue by nickoe** [pyserial/pyserial#66]
Hi

I just upgraded to pyserial 3.0 on archlinux the other day, this broke a software package I use called [Chirp](http://chirp.danplanet.com/projects/chirp/wiki/Home).

The error I get from Chirp is:
```
$ chirpw 
ERROR: -- Exception: --
ERROR: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/chirp/ui/clone.py", line 238, in run
    self.__radio.sync_in()
  File "/usr/lib/python2.7/site-packages/chirp/drivers/uv5r.py", line 705, in sync_in
    raise errors.RadioError("Failed to communicate with radio: %s" % e)
RadioError: Failed to communicate with radio: 'Serial' object has no attribute 'setTimeout'

ERROR: ----------------
ERROR: Clone failed: Failed to communicate with radio: 'Serial' object has no attribute 'setTimeout'
ERROR: --- Exception Dialog: Failed to communicate with radio: 'Serial' object has no attribute 'setTimeout' ---
ERROR: None

ERROR: ----------------------------
```

I traced it back to this commit which removed that method:
https://github.com/pyserial/pyserial/commit/779b1a29594b9f6c69e73e02ab1e95b8dbb3e8b7#diff-6565967c29e370a01030e6dcbc5acee8L232

I would ask to get those methods back, to maintain backwards compatibility.

This issue is similar to the API breakage mentioned in https://github.com/pyserial/pyserial/issues/55.

**Comment by zsquareplusc** [comment]
Hm... I would *not* like to add that function again.

The get/set functions for timeout, baudrate etc. were standard in pySerial V1.x and were replaced by properties in V2.x (it was released back in 2003). While V2.x still allowed to call the set/get functions, the `setTimeout` function was not even documented in the V2.x API.

pySerial V3.x supports the V2.x API for backward compatibility but renamed some attributes and functions (though `timeout` was not affected).

So IMHO the other program should be fixed, more than 12 years time to upgrade the API should have been enough ;-)

Alternatively it could depend on pyserial<3 or install a local copy of the `serial` module and point to it using `PYTHONPATH` or similar mechanisms.

**Comment by nickoe** [comment]
@zsquareplusc Ok, that is understandable. I am not too familiar with the pyserial API, I was just worried if it would break from v2 to v3. But since you said it was deprecated in v2, and there is a method that works in both v2 and v3, I will close this issue and forward your response to the chirp developers. Thank you.
