### ISSUE TITLE
Get parity bit status

### ISSUE THREAD

**Issue by siddolo** [pyserial/pyserial#695]
Is there any way to get the parity bit value for each byte received on the bus?

**Comment by harryberlin** [comment]
got this as result from google:
https://stackoverflow.com/questions/15591223/how-to-calculate-the-parity-bit-of-the-following-bit-sequence

**Comment by siddolo** [comment]
No way @harryberlin,
I'm handling a 9 data bits protocol (some time called Multi-Drop BUS or CMSPAR, MARK/SPACE parity). In these frames the 9th bit is 1 (MARK) if the received byte is an address, and 0 (SPACE) if the received byte is a data.
So I can't calculate it.

**Comment by harryberlin** [comment]
so, do describe your issue for better understanding!
parity (Odd, Even) is part of serial protocol.
good luck.

**Comment by siddolo** [comment]
> so, do describe your issue for better understanding! parity (Odd, Even) is part of serial protocol. good luck.

I'm handling a 9 data bits protocol (some time called Multi-Drop BUS or CMSPAR, MARK/SPACE parity). In these frames the 9th bit is 1 (MARK) if the received byte is an address, and 0 (SPACE) if the received byte is a data.
Is it possible to get the 9th bit (parity MARK/parity SPACE) status from pyserial?
How do I distinguish a data from an address?

Thanks for your time.

**Comment by siddolo** [comment]
Same issue here #357

**Comment by siddolo** [comment]
The solution is to set the [termios](https://man7.org/linux/man-pages/man3/termios.3.html) flag PARMRK, INPCK, and IGNPAR.

```
import serial
import termios

ser = serial.Serial (....)

# Get termios settings
iflag, oflag, cflag, lflag, ispeed, ospeed, cc = termios.tcgetattr(ser)

# Enable input parity checking & parity mark with \xff\x00
iflag |= termios.PARMRK | termios.INPCK
iflag &= ~termios.IGNPAR

# Apply termios settings
termios.tcsetattr(ser, termios.TCSANOW, [iflag, oflag, cflag, lflag, ispeed, ospeed, cc])
```
