### ISSUE TITLE
LF to CR-LF conversion on windows PC

### ISSUE THREAD

**Issue by dylanwal** [pyserial/pyserial#711]
## Overview
**Issue**: Can't send raw byte data without conversion errors. (on windows OS)
**Cause**: LF is converted into CR-LF
**Hopeful solution**: be able to turn the conversion of LF to CR-LF on/off 

CR = '\r'
LF = '\n'

## More details:
I am using a windows PC to read data from a microcontroller over USB. I have issues when I send the following byte data:

**sudo-code on microcontroller**
```
import struct
data = struct.pack("h", 10)  # b'\n\x00'
# write  b'\n\x00' to USB
```

**sudo-code on windows PC**
```
import struct
import serial

s = serial.Serial('COM3')
received_bytes = s.read(2)
data = struct.unpack("h", received_bytes)
print(data)  # 2573  (expected 10)  <-- 2573 is from b'\r\n'    (b'\x00' is still in the buffer)
```

On the windows PC `b'\n\x00'` is converted to `b'\r\n\x00'`.

It can make it impossible to differentiate between weather b'\n' or b'\r\n' was sent. 
(I can't just see if there is another byte in the buffer as I am streaming lots of data fast,
 and there is typically a small build up).
 
I know for historical reason (https://stackoverflow.com/questions/6521685/why-does-windows-use-cr-lf) windows still does this conversion, but the python 'open' function has a 'newline' argument to allow users to turn this on or off and I was hoping that would be added here too. (https://docs.python.org/3/library/functions.html#open-newline-parameter)

Current workaround: send data as strings, which which requires extra conversations and is slower especially as numbers get bigger.

**Comment by KLimit** [comment]
You might want to verify the output of your microcontroller using an interface other than pyserial to confirm where the erroneous CR is coming from.

I tried to recreate this behavior using your pseudocode (albeit with an emulated COM port rather than a separate microcontroller), but `data` successfully unpacked to 10 rather than 2573.
Perhaps it's possible that the serial-to-USB instrument or its driver is inserting the character? Some forums posts I skimmed suggest that it's not out of the question for drivers to do that (though I could have misinterpreted them).

In any case, [this EOL section of the docs](https://pythonhosted.org/pyserial/shortintro.html#eol) may give some insight on how to achieve the "newline" functionality you describe (note that `unicode` is a Python 2 thing; Python 3 strings are always unicode).

**Comment by dylanwal** [comment]
Hi @KLimit, 
Thanks for the reply! I did more testing and I was able to reproduce the issue on another windows computer. 
Here is my code:

Raspberry Pi Pico code:
```
import select
import sys
import struct

poll_obj = select.poll()
poll_obj.register(sys.stdin, select.POLLIN)
      
while True:
    poll_results = poll_obj.poll(10)
    if poll_results:
        message = sys.stdin.readline()
        n = int(message[:-1])
        for i in range(n):
            sys.stdout.write(struct.pack("h", i))
```

PC code:
```
import struct
import serial

s = serial.Serial('COM3')
s.flushInput()
s.flushOutput()


n = 15
s.write(f"{n}\n".encode())
for i in range(n):
    received_bytes = s.read(2)
    received_data = struct.unpack("h", received_bytes)
    print(i, received_bytes, received_data)  

```

PC Output:
```
0 b'\x00\x00' (0,)
1 b'\x01\x00' (1,)
2 b'\x02\x00' (2,)
3 b'\x03\x00' (3,)
4 b'\x04\x00' (4,)
5 b'\x05\x00' (5,)
6 b'\x06\x00' (6,)
7 b'\x07\x00' (7,)
8 b'\x08\x00' (8,)
9 b'\t\x00' (9,)
10 b'\r\n' (2573,)       <<<<<<<<<<< an extra '\r' inserted by windows
11 b'\x00\x0b' (2816,)
12 b'\x00\x0c' (3072,)
13 b'\x00\r' (3328,)
14 b'\x00\x0e' (3584,)
```


I double checked that it is a windows specific issue by running doing the same thing between two microcontrollers and I get the desired output:

```
0 b'\x00\x00' (0,)
1 b'\x01\x00' (1,)
2 b'\x02\x00' (2,)
3 b'\x03\x00' (3,)
4 b'\x04\x00' (4,)
5 b'\x05\x00' (5,)
6 b'\x06\x00' (6,)
7 b'\x07\x00' (7,)
8 b'\x08\x00' (8,)
9 b'\t\x00' (9,)
10 b'\n\x00' (10,)
11 b'\x0b\x00' (11,)
12 b'\x0c\x00' (12,)
13 b'\r\x00' (13,)
14 b'\x0e\x00' (14,)
```

I switched to an Ardunio Uno and I ran the same tests and did NOT have the '\r' inserted into the data stream.

**Conclusion:**
It is likely the Raspberry Pi Serial driver is converting '\n' into '\r\n'. 
This is probably not an issue for Pyserial to fix, so I am closing the Issue.
