### ISSUE TITLE
[2.6] Undefined name in list_ports_posix.py:80 (usb_lsusb_string)

### ISSUE THREAD

**Issue by Ippo343** [pyserial/pyserial#74]
In function `usb_lsusb_string` in the file `list_ports_posix.py` there is an undefined symbol at line 80.

Here's the code:

    def usb_lsusb_string(sysfs_path):
        bus, dev = os.path.basename(os.path.realpath(sysfs_path)).split('-')
        try:
            desc = popen(['lsusb', '-v', '-s', '%s:%s' % (bus, dev)])
            # descriptions from device
            iManufacturer = re_group('iManufacturer\s+\w+ (.+)', desc)
            iProduct = re_group('iProduct\s+\w+ (.+)', desc)
            iSerial = re_group('iSerial\s+\w+ (.+)', desc) or ''
            # descriptions from kernel
            idVendor = re_group('idVendor\s+0x\w+ (.+)', desc)
            idProduct = re_group('idProduct\s+0x\w+ (.+)', desc)
            # create descriptions. prefer text from device, fall back to the others
            return '%s %s %s' % (iManufacturer or idVendor, iProduct or idProduct, iSerial)
        except IOError:
            return base

If an IOError occurs when trying to use popen, the function tries to return `base` which is undefined.
Occurs on pyserial 2.6, Ubuntu 15.10 x64.

**Comment by zsquareplusc** [comment]
Thank you. The implementation has been updated since 2.6 and that part of the code is gone (no longer calling `lsusb`). You can download 3.0 from [pypi](https://pypi.python.org/pypi/pyserial).

**Comment by Ippo343** [comment]
Hello,

yes, we had noticed and had already switched to version 3.
I pretty much decided to open the issue just for completeness :)

Thanks!
