### ISSUE TITLE
Write method cause gap between bytes on Mac os

### ISSUE THREAD

**Issue by 491239** [pyserial/pyserial#743]
### Performance on Windows

**I use the write method to send this array, on Windows, I can receive the package completely.**

> data array:

![image](https://github.com/pyserial/pyserial/assets/57991348/b16df464-b55b-486b-a2b6-bb75c0b3d036)

> I print every package length my device received:

![image](https://github.com/pyserial/pyserial/assets/57991348/2a39da28-e3a1-4c21-9736-008cc924d2d5)

### Macos

> The data i sent:

![image](https://github.com/pyserial/pyserial/assets/57991348/10adb633-6236-4e2e-bf1b-778bbb818c95)

> The data received:

![image](https://github.com/pyserial/pyserial/assets/57991348/869e91d6-e956-464a-8280-2a1a3a8920ce)

**As we can see, the package has been split, and the maximum bytes of every package always be 384 whatever the length of array you sent.**

Is this a problem of macos? Is there any solution? Can anyone give me an answer? Thanks.

**Comment by philbourg** [comment]
Same problem here. We will try to send data from one port and get it back from another. 

MacBook Pro 
16-inch, 2023
Apple M2 Pro 
Ventura 13.6.6

**Comment by 258188170** [comment]
解决了吗？

**Comment by 491239** [comment]
> 解决了吗？

No

**Comment by 491239** [comment]
> Same problem here. We will try to send data from one port and get it back from another.
> 
> MacBook Pro 16-inch, 2023 Apple M2 Pro Ventura 13.6.6

It seems that this is a macOS system restriction. I tried testing it using C++ and got the same result.
