### ISSUE TITLE
Sourceforge status

### ISSUE THREAD

**Issue by diegoherranz** [pyserial/pyserial#8]
This is the current official development of pyserial, right?

If so, could the sourceforge page be updated/removed or at least indicate that sourceforge is no longer used and link to here? I think it's quite confusing right now.

The website link on PyPI could be updated too.

Happy to see active development on pyserial lately!

Thanks!

**Comment by zsquareplusc** [comment]
I'll put up an announcement over there when the first beta is released here.

**Comment by diegoherranz** [comment]
Great. Thanks!

**Comment by zsquareplusc** [comment]
done
