### ISSUE TITLE
Compatibility issue between Windows/Linux list_ports.comports()

### ISSUE THREAD

**Issue by snelson-senet** [pyserial/pyserial#80]
Linux returns a list while Windows returns a generator. 

I wrote a script on linux that checks the number of returned ports using len(). When I tried to run same script on Windows it failed since len() does not accept a generator object.

It would be nice if the comports() was compatible across OSes. 

Other than that, pyserial has worked great for me.

**Comment by zsquareplusc** [comment]
OK, returning a list on all platform makes sense (there are not thousands of entries) and working with lists is easier.
