### ISSUE TITLE
unify ``self.is_open`` and ``self.fd is not None`` in serialposix

### ISSUE THREAD

**Issue by sbourdeauducq** [pyserial/pyserial#83]
Or is there a point in having these two different mechanisms?

**Comment by sbourdeauducq** [comment]
I'd replace everything with ``fd is not None``.

**Comment by zsquareplusc** [comment]
I choose the opposite. `is_open` is available on all platforms so it makes it easier to compare the different implementations and identify similar functionality.

A platform specific handle/file descriptor etc. is still needed because the operating systems are different.
