### ISSUE TITLE
creating a Serial object with an integer argument causes error

### ISSUE THREAD

**Issue by nanthony21** [pyserial/pyserial#84]
creating serial object like this ser=Serial(1) raises: AttributeError: 'int' object has no attribute 'upper'.

This issue appears to have originated in serialutil.py in the commit labeled "Work on python 3 compatibility" on august  3, 2015.

the assignment of self.portstr of the SerialBase class needs something to make sure that it's actually a string.

**Comment by fladd** [comment]
I also ran into this issue. The issue is also discussed [here](http://stackoverflow.com/questions/34574311/pyserial-serialwin32-py-has-attribute-error).

My question is, whether this is an acknowledged bug, or whether this is changed behaviour and will stay that way?

**Comment by zsquareplusc** [comment]
The possibility to pass numbers will not come back. I may add a extra check with dedicated exception message for more clarity.

That numbers are no longer supported is also stated in the [APi docs](https://pyserial.readthedocs.org/en/latest/pyserial_api.html#serial.Serial)

opening "the first serial device" (e.g. with `Serial(0)`) just makes no sense anymore where internal serial ports are barely used and USB-serial adapters are common. The old way of assigning a number also did not include all devices (on some OS) or it was confusing (0->COM1).

To enumerate ports, it is better to use [`serial.tools.list_ports`](https://pyserial.readthedocs.org/en/latest/tools.html#module-serial.tools.list_ports). To open a connection to a specific device it may also be easier to use [`serial_for_url`](https://pyserial.readthedocs.org/en/latest/url_handlers.html) with `hwgrep://` especially if it is a USB device which can be identified by its name or VID:PID combination.
