### ISSUE TITLE
BUG: serialposix.py _set_rs485_mode() tries to read non-existing rs485_settings.delay_rts_before_send

### ISSUE THREAD

**Issue by vanmierlo** [pyserial/pyserial#85]
Hi,

In serialposix.py the function \_set_rs485_mode() tries to read the non-existing _delay_rts_before_send_ and _delay_rts_after_send_ from rs485_settings. But in rs485.py in class RS485Settings there are only _delay_before_tx_ and _delay_before_rx_ defined. The easiest fix is to rename the fields in serialposix.py I guess.

Can someone please fix this bug?

Maarten Brock

**Comment by zsquareplusc** [comment]
yes someone can :-) fix committed
